//============================================================================================
/**
 * @file		box2_seq.h
 * @brief		ボックス画面 メインシーケンス処理
 * @author	Hiroyuki Nakamura
 * @date		09.10.05
 *
 *	モジュール名：BOX2SEQ
 */
//============================================================================================
#pragma	once

#include "box2_main.h"


//============================================================================================
//	定数定義
//============================================================================================

// メインシーケンス
enum {
	BOX2SEQ_MAINSEQ_INIT = 0,		// 初期化
	BOX2SEQ_MAINSEQ_RELEASE,		// 解放
	BOX2SEQ_MAINSEQ_WIPE,			// ワイプ処理待ち
	BOX2SEQ_MAINSEQ_PALETTE_FADE,	// パレットフェード
	BOX2SEQ_MAINSEQ_WAIT,			// ウェイト
	BOX2SEQ_MAINSEQ_VFUNC,			// VBLANC処理中

	BOX2SEQ_MAINSEQ_TRGWAIT,		// キー/タッチ待ち

	BOX2SEQ_MAINSEQ_YESNO,			// はい・いいえ
	BOX2SEQ_MAINSEQ_BUTTON_ANM,		// ボタンアニメ

	BOX2SEQ_MAINSEQ_SUB_PROCCALL,	// サブプロセス呼び出し
	BOX2SEQ_MAINSEQ_SUB_PROCMAIN,	// サブプロセスメイン

	BOX2SEQ_MAINSEQ_START,							// 開始
	BOX2SEQ_MAINSEQ_START_WAIT,					// 開始キュー待ち

	BOX2SEQ_MAINSEQ_CURSORMOVE_RET,			// カーソル移動後にメインに戻る
	BOX2SEQ_MAINSEQ_ARRANGE_POKEMENU_RCV,				// ボックス整理・ポケモンメニューに戻る
	BOX2SEQ_MAINSEQ_TRAYSCROLL_TOUCH,
	BOX2SEQ_MAINSEQ_BOXEND_DIRECT,

	// ボックス整理
	BOX2SEQ_MAINSEQ_ARRANGE_MAIN,								// ボックス整理・メイン
	BOX2SEQ_MAINSEQ_ARRANGE_TRAYPOKE_CHG_END,		// ボックス整理・トレイのポケモン移動後
	BOX2SEQ_MAINSEQ_ARRANGE_MENU_CLOSE,

	BOX2SEQ_MAINSEQ_ARRANGE_POKEGET_INIT,
	BOX2SEQ_MAINSEQ_ARRANGE_POKEGET_MAIN,
	BOX2SEQ_MAINSEQ_ARRANGE_POKEGET_EXIT,
	BOX2SEQ_MAINSEQ_ARRANGE_POKEGET_DATA_CHANGE,
	BOX2SEQ_MAINSEQ_ARRANGE_POKEGET_DATA_CHANGE_ERR,
	BOX2SEQ_MAINSEQ_ARRANGE_POKEGET_PARTY_CHANGE,

	BOX2SEQ_MAINSEQ_ARRANGE_PARTY_INIT,
	BOX2SEQ_MAINSEQ_ARRANGE_PARTY_MAIN,
	BOX2SEQ_MAINSEQ_ARRANGE_PARTY_END,
	BOX2SEQ_MAINSEQ_ARRANGE_PARTY_MENU_CLOSE,
	BOX2SEQ_MAINSEQ_ARRANGE_PARTYPOKE_CHG_END,		// ボックス整理・手持ちポケモン入れ替え後

	BOX2SEQ_MAINSEQ_ARRANGE_PARTY_POKEGET_INIT,
	BOX2SEQ_MAINSEQ_ARRANGE_PARTY_POKEGET_MAIN,
	BOX2SEQ_MAINSEQ_ARRANGE_PARTY_POKEGET_EXIT,
	BOX2SEQ_MAINSEQ_ARRANGE_PARTY_POKEGET_BOXLIST_CHANGE,

	// バトルボックス
	BOX2SEQ_MAINSEQ_BATTLEBOX_MAIN,
	BOX2SEQ_MAINSEQ_BATTLEBOX_TRAYPOKE_CHG_END,
	BOX2SEQ_MAINSEQ_BATTLEBOX_MENU_CLOSE,

	BOX2SEQ_MAINSEQ_BATTLEBOX_PARTY_INIT,
	BOX2SEQ_MAINSEQ_BATTLEBOX_PARTY_MAIN,
	BOX2SEQ_MAINSEQ_BATTLEBOX_PARTY_END,
	BOX2SEQ_MAINSEQ_BATTLEBOX_PARTY_MENU_CLOSE,
	BOX2SEQ_MAINSEQ_BATTLEBOX_PARTYPOKE_CHG_END,

	BOX2SEQ_MAINSEQ_BATTLEBOX_ROCK,

	// つれていく
	BOX2SEQ_MAINSEQ_PARTYIN_MAIN,
	BOX2SEQ_MAINSEQ_PARTYIN_MENU_CLOSE,
	BOX2SEQ_MAINSEQ_PARTYIN_SELECT,
	BOX2SEQ_MAINSEQ_PARTYIN_ACTION,
	BOX2SEQ_MAINSEQ_PARTYIN_POKECHG_END,

	// あずける
	BOX2SEQ_MAINSEQ_PARTYOUT_MAIN,
	BOX2SEQ_MAINSEQ_PARTYOUT_MENU_CLOSE,
	BOX2SEQ_MAINSEQ_PARTYOUT_ERR_RCV_MAIN,

	BOX2SEQ_MAINSEQ_PARTYOUT_PUT_INIT,
	BOX2SEQ_MAINSEQ_PARTYOUT_PUT_MAIN,
	BOX2SEQ_MAINSEQ_PARTYOUT_PUT_END,
	BOX2SEQ_MAINSEQ_PARTYOUT_ERR_RCV_PUT,
	BOX2SEQ_MAINSEQ_PARTYOUT_POKECHG_END,

	// 持ち物整理
	BOX2SEQ_MAINSEQ_ITEM_MAIN,
	BOX2SEQ_MAINSEQ_ITEM_MENU_CLOSE,
	BOX2SEQ_MAINSEQ_ITEM_BAGIN_ANM,
	BOX2SEQ_MAINSEQ_ITEM_POKESET_ANM,
	BOX2SEQ_MAINSEQ_ITEM_POKESET_RET,
	BOX2SEQ_MAINSEQ_ITEMARRANGE_ICONMOVE_RET,
	BOX2SEQ_MAINSEQ_ITEMGET_INIT,
	BOX2SEQ_MAINSEQ_ITEMGET_MAIN,
	BOX2SEQ_MAINSEQ_ITEMGET_END,
	BOX2SEQ_MAINSEQ_ITEM_BOXPARTY_ICONMOVE_POKEADD,
	BOX2SEQ_MAINSEQ_ITEM_BOXPARTY_ICONMOVE_END,
	BOX2SEQ_MAINSEQ_ITEM_BOXPARTY_CHG_ERROR,
	BOX2SEQ_MAINSEQ_ITEM_KEYGET_CHANGE_CHECK,
	BOX2SEQ_MAINSEQ_ITEM_PARTY_MAIN,
	BOX2SEQ_MAINSEQ_ITEM_PARTY_MENU_CLOSE,
	BOX2SEQ_MAINSEQ_ITEM_PARTY_ICONMOVE_RET,
	BOX2SEQ_MAINSEQ_ITEM_PARTY_ICONMOVE_POKEADD,
	BOX2SEQ_MAINSEQ_ITEM_PARTY_ICONMOVE_CHANGE,

	// 寝かせる
	BOX2SEQ_MAINSEQ_SLEEP_MAIN,
	BOX2SEQ_MAINSEQ_SLEEP_POKE_SELECT,
	BOX2SEQ_MAINSEQ_SLEEP_MENU_SET,
	BOX2SEQ_MAINSEQ_SLEEP_MENU_CLOSE,

	// サブプロセス
	BOX2SEQ_MAINSEQ_STATUS_CALL,
	BOX2SEQ_MAINSEQ_ITEM_MENU_CHECK,

	BOX2SEQ_MAINSEQ_STATUS_RCV,									// ステータス画面からの復帰
	BOX2SEQ_MAINSEQ_STRIN_RCV,									// 文字入力画面からの復帰
	BOX2SEQ_MAINSEQ_BAG_RCV,										// バッグ画面からの復帰
	BOX2SEQ_MAINSEQ_ITEMSET_MSG,								// 道具をもたせたメッセージ表示

	// マーキング
	BOX2SEQ_MAINSEQ_MARKING_INIT,								// マーキング処理初期設定
	BOX2SEQ_MAINSEQ_MARKING_MAIN,								// マーキング処理メイン
	BOX2SEQ_MAINSEQ_MARKING_END,								// マーキングから復帰
	BOX2SEQ_MAINSEQ_MARKING_CURMOVE_RET,

	// 逃がす
	BOX2SEQ_MAINSEQ_POKEFREE_INIT,							// ポケモンを逃がす開始
	BOX2SEQ_MAINSEQ_POKEFREE_ANM,								// ポケモンを逃がすアニメ
	BOX2SEQ_MAINSEQ_POKEFREE_ENTER,							// ポケモンを逃がす・成功
	BOX2SEQ_MAINSEQ_POKEFREE_ERROR,							// ポケモンを逃がす・失敗

	// ボックステーマ変更
	BOX2SEQ_MAINSEQ_BOXTHEMA_INIT,
	BOX2SEQ_MAINSEQ_BOXTHEMA_MAIN,
	BOX2SEQ_MAINSEQ_BOXTHEMA_EXIT,
	BOX2SEQ_MAINSEQ_BOXTHEMA_JUMP_INIT,
	BOX2SEQ_MAINSEQ_BOXTHEMA_JUMP_MAIN,
	BOX2SEQ_MAINSEQ_BOXTHEMA_JUMP_EXIT,
	BOX2SEQ_MAINSEQ_BOXTHEMA_JUMP_RET,
	BOX2SEQ_MAINSEQ_BOXTHEMA_WALLPAPER_INIT,
	BOX2SEQ_MAINSEQ_BOXTHEMA_WALLPAPER_MAIN,
	BOX2SEQ_MAINSEQ_BOXTHEMA_WALLPAPER_CHANGE,
	BOX2SEQ_MAINSEQ_BOXTHEMA_NAMEIN_CALL,

	// 終了処理
	BOX2SEQ_MAINSEQ_BOXEND_INIT,

	BOX2SEQ_MAINSEQ_END
};


//============================================================================================
//	プロトタイプ宣言
//============================================================================================

//--------------------------------------------------------------------------------------------
/**
 * @brief		メインシーケンス制御
 *
 * @param		syswk		ボックス画面システムワーク
 * @param		seq			メインシーケンス
 *
 * @retval	"TRUE = 処理中"
 * @retval	"FALSE = 終了"
 */
//--------------------------------------------------------------------------------------------
extern BOOL BOX2SEQ_Main( BOX2_SYS_WORK * syswk, int * seq );

//--------------------------------------------------------------------------------------------
/**
 * @brief		メニューセット【持ち物整理】
 *
 * @param		syswk		ボックス画面システムワーク
 * @param		item		アイテム
 *
 * @return	none
 */
//--------------------------------------------------------------------------------------------
extern void BOX2SEQ_ItemModeMenuSet( BOX2_SYS_WORK * syswk, s16 item );
