//============================================================================================
/**
 * @file shooter_item_data.h
 * @brief シューター用アイテム使用許可ビット
 * @author toru=nagihashi
 * @date Fri Jun 11 11:10:57 +0900 2010
 * @note このファイルはshooter_item_conv.rbにて自動生成されております
*/
//============================================================================================
#ifndef __SHOOTER_ITEM_DATA_H__
#define __SHOOTER_ITEM_DATA_H__

#define	SHOOTER_ITEM_AITEMUKOORU		(0)
#define	SHOOTER_ITEM_KIZUGUSURI		(1)
#define	SHOOTER_ITEM_SUKIRUKOORU		(2)
#define	SHOOTER_ITEM_PURASUPAWAA		(3)
#define	SHOOTER_ITEM_DHIFENDAA		(4)
#define	SHOOTER_ITEM_SUPESYARUAPPU		(5)
#define	SHOOTER_ITEM_SUPESYARUGAADO		(6)
#define	SHOOTER_ITEM_SUPIIDAA		(7)
#define	SHOOTER_ITEM_YOKUATAARU		(8)
#define	SHOOTER_ITEM_KURITHIKATTO		(9)
#define	SHOOTER_ITEM_EFEKUTOGAADO		(10)
#define	SHOOTER_ITEM_IIKIZUGUSURI		(11)
#define	SHOOTER_ITEM_KOORINAOSI		(12)
#define	SHOOTER_ITEM_DOKUKESI		(13)
#define	SHOOTER_ITEM_NEMUKEZAMASI		(14)
#define	SHOOTER_ITEM_MAHINAOSI		(15)
#define	SHOOTER_ITEM_YAKEDONAOSI		(16)
#define	SHOOTER_ITEM_AITEMUDOROPPU		(17)
#define	SHOOTER_ITEM_PURASUPAWAA2		(18)
#define	SHOOTER_ITEM_DHIFENDAA2		(19)
#define	SHOOTER_ITEM_spAPPU2		(20)
#define	SHOOTER_ITEM_spGAADO2		(21)
#define	SHOOTER_ITEM_SUPIIDAA2		(22)
#define	SHOOTER_ITEM_YOKUATAARU2		(23)
#define	SHOOTER_ITEM_KURITHIKATTO2		(24)
#define	SHOOTER_ITEM_NANDEMONAOSI		(25)
#define	SHOOTER_ITEM_PURASUPAWAA3		(26)
#define	SHOOTER_ITEM_DHIFENDAA3		(27)
#define	SHOOTER_ITEM_spAPPU3		(28)
#define	SHOOTER_ITEM_spGAADO3		(29)
#define	SHOOTER_ITEM_SUPIIDAA3		(30)
#define	SHOOTER_ITEM_YOKUATAARU3		(31)
#define	SHOOTER_ITEM_KURITHIKATTO3		(32)
#define	SHOOTER_ITEM_SUGOIKIZUGUSURI		(33)
#define	SHOOTER_ITEM_HURATTOKOORU		(34)
#define	SHOOTER_ITEM_MANTANNOKUSURI		(35)
#define	SHOOTER_ITEM_GENKINOKAKERA		(36)
#define	SHOOTER_ITEM_PIIPIIEIDO		(37)
#define	SHOOTER_ITEM_PURASUPAWAA6		(38)
#define	SHOOTER_ITEM_DHIFENDAA6		(39)
#define	SHOOTER_ITEM_spAPPU6		(40)
#define	SHOOTER_ITEM_spGAADO6		(41)
#define	SHOOTER_ITEM_SUPIIDAA6		(42)
#define	SHOOTER_ITEM_YOKUATAARU6		(43)
#define	SHOOTER_ITEM_KAIHUKUNOKUSURI		(44)
#define	SHOOTER_ITEM_GENKINOKATAMARI		(45)
#define	SHOOTER_ITEM_MAX		(46)

#endif //__SHOOTER_ITEM_DATA_H__
