//============================================================================================
/**
 * @file shooter_item_data.h
 * @brief シューター用アイテム使用許可ビット
 * @author toru=nagihashi
 * @date Wed Mar 10 16:18:17 +0900 2010
 * @note このファイルはshooter_item_conv.rbにて自動生成されております
*/
//============================================================================================
#ifndef __SHOOTER_ITEM_DATA_H__
#define __SHOOTER_ITEM_DATA_H__

#define	SHOOTER_ITEM_KURITHIKATTAA		(0)
#define	SHOOTER_ITEM_SUPIIDAA		(1)
#define	SHOOTER_ITEM_SUPESYARUAPPU		(2)
#define	SHOOTER_ITEM_SUPESYARUGAADO		(3)
#define	SHOOTER_ITEM_DHIFENDAA		(4)
#define	SHOOTER_ITEM_PURASUPAWAA		(5)
#define	SHOOTER_ITEM_YOKUATAARU		(6)
#define	SHOOTER_ITEM_EFEKUTOGAADO		(7)
#define	SHOOTER_ITEM_KIZUGUSURI		(8)
#define	SHOOTER_ITEM_PIIPIIEIDO		(9)
#define	SHOOTER_ITEM_AITEMUKOORU		(10)
#define	SHOOTER_ITEM_KURITHIKATTO2		(11)
#define	SHOOTER_ITEM_SUPIIDAA2		(12)
#define	SHOOTER_ITEM_spAPPU2		(13)
#define	SHOOTER_ITEM_spGAADO2		(14)
#define	SHOOTER_ITEM_DHIFENDAA2		(15)
#define	SHOOTER_ITEM_PURASUPAWAA2		(16)
#define	SHOOTER_ITEM_YOKUATAARU2		(17)
#define	SHOOTER_ITEM_IIKIZUGUSURI		(18)
#define	SHOOTER_ITEM_KOORINAOSI		(19)
#define	SHOOTER_ITEM_DOKUKESI		(20)
#define	SHOOTER_ITEM_NEMUKEZAMASI		(21)
#define	SHOOTER_ITEM_MAHINAOSI		(22)
#define	SHOOTER_ITEM_YAKEDONAOSI		(23)
#define	SHOOTER_ITEM_SUKIRUKOORU		(24)
#define	SHOOTER_ITEM_KURITHIKATTO3		(25)
#define	SHOOTER_ITEM_SUPIIDAA3		(26)
#define	SHOOTER_ITEM_spAPPU3		(27)
#define	SHOOTER_ITEM_spGAADO3		(28)
#define	SHOOTER_ITEM_DHIFENDAA3		(29)
#define	SHOOTER_ITEM_PURASUPAWAA3		(30)
#define	SHOOTER_ITEM_YOKUATAARU3		(31)
#define	SHOOTER_ITEM_SUGOIKIZUGUSURI		(32)
#define	SHOOTER_ITEM_NANDEMONAOSI		(33)
#define	SHOOTER_ITEM_PIIPIIEIDAA		(34)
#define	SHOOTER_ITEM_PIIPIIRIKABAA		(35)
#define	SHOOTER_ITEM_AITEMUDOROPPU		(36)
#define	SHOOTER_ITEM_MANTANNOKUSURI		(37)
#define	SHOOTER_ITEM_HURATTOKOORU		(38)
#define	SHOOTER_ITEM_PIIPIIMAKKUSU		(39)
#define	SHOOTER_ITEM_GENKINOKAKERA		(40)
#define	SHOOTER_ITEM_SUPIIDAA6		(41)
#define	SHOOTER_ITEM_spAPPU6		(42)
#define	SHOOTER_ITEM_spGAADO6		(43)
#define	SHOOTER_ITEM_DHIFENDAA6		(44)
#define	SHOOTER_ITEM_PURASUPAWAA6		(45)
#define	SHOOTER_ITEM_YOKUATAARU6		(46)
#define	SHOOTER_ITEM_KAIHUKUNOKUSURI		(47)
#define	SHOOTER_ITEM_GENKINOKATAMARI		(48)
#define	SHOOTER_ITEM_MAX		(49)

#endif //__SHOOTER_ITEM_DATA_H__
