//zone id define table
#ifndef __ZONE_ID_H__
#define __ZONE_ID_H__
#define ZONE_ID_MAPSPRING        (  0)
#define ZONE_ID_MAPSUMMER        (  1)
#define ZONE_ID_MAPAUTUMN        (  2)
#define ZONE_ID_MAPWINTER        (  3)
#define ZONE_ID_TESTPC           (  4)
#define ZONE_ID_TESTROOM         (  5)
#define ZONE_ID_PLANNERTEST      (  6)
#define ZONE_ID_BRIDGE           (  7)
#define ZONE_ID_LOOPBRIDGE       (  8)
#define ZONE_ID_LOOPBRIDGE2      (  9)
#define ZONE_ID_LOOPBRIDGE3      ( 10)
#define ZONE_ID_TESTC3           ( 11)
#define ZONE_ID_T01              ( 12)
#define ZONE_ID_R01              ( 13)
#define ZONE_ID_T02              ( 14)
#define ZONE_ID_R02              ( 15)
#define ZONE_ID_C01              ( 16)
#define ZONE_ID_D01              ( 17)
#define ZONE_ID_R03              ( 18)
#define ZONE_ID_C02              ( 19)
#define ZONE_ID_D02              ( 20)
#define ZONE_ID_C03P02           ( 21)
#define ZONE_ID_C03P03           ( 22)
#define ZONE_ID_C03P04           ( 23)
#define ZONE_ID_C03P05           ( 24)
#define ZONE_ID_C03P06           ( 25)
#define ZONE_ID_C03P07           ( 26)
#define ZONE_ID_C03P08           ( 27)
#define ZONE_ID_C03P09           ( 28)
#define ZONE_ID_C03P10           ( 29)
#define ZONE_ID_C03P11           ( 30)
#define ZONE_ID_C03P12           ( 31)
#define ZONE_ID_C03P13           ( 32)
#define ZONE_ID_MAX	(33)
#endif // __ZONE_ID_H__

