
include $(PROJECT_RSCDIR)\macro_define

SUBDIRS	=	area_data land_data camera_data zonetable map_matrix build_model land_data_ex script mm_list eventdata effect rail_data scenearea zonefog_table zonelight_table

.PHONY:	do-build clean

do-build:
	@$(MAKE_SUBDIR)

clean:
	@$(MAKE_SUBDIR)
