//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 03/15/10.
//-----------------------------------------------------
#define    NANR_pms2_obj_main_hidari    0 // 
#define    NANR_pms2_obj_main_hidari_tp    1 // 
#define    NANR_pms2_obj_main_mail_off    2 // 
#define    NANR_pms2_obj_main_mail_on    3 // 
#define    NANR_pms2_obj_main_sentoumae_off    4 // 
#define    NANR_pms2_obj_main_sentoumae_on    5 // 
#define    NANR_pms2_obj_main_win_off    6 // 
#define    NANR_pms2_obj_main_win_on    7 // 
#define    NANR_pms2_obj_main_lose_off    8 // 
#define    NANR_pms2_obj_main_lose_on    9 // 
#define    NANR_pms2_obj_main_yunion_off    10 // 
#define    NANR_pms2_obj_main_yunion_on    11 // 
#define    NANR_pms2_obj_main_migi    12 // 
#define    NANR_pms2_obj_main_migi_tp    13 // 
#define    NANR_pms2_obj_main_change_off    14 // 
#define    NANR_pms2_obj_main_change_on    15 // 
#define    NANR_pms2_obj_main_bar    16 // 
#define    NANR_pms2_obj_main_s_yajirushi01    17 // 
#define    NANR_pms2_obj_main_s_yajirushi02    18 // 
