ntexconv 001_01_x_menu.bmp -no -bg -bgb -bgf direct
ntexconv 002_01_title_black.bmp -no -bg -bgb -bgf direct
ntexconv 003_01_titlemenu.bmp -no -bg -bgb -bgf direct
ntexconv 003_02_haitatuin.bmp -no -bg -bgb -bgf direct
ntexconv 003_03_hushigina_card.bmp -no -bg -bgb -bgf direct
ntexconv 038_01_battletaikai.bmp -no -bg -bgb -bgf direct
ntexconv 000_01_url.bmp -no -bg -bgb -bgf direct
ntexconv 018_01_battlebox.bmp -no -bg -bgb -bgf direct
ntexconv 043_01_wifisettei.bmp -no -bg -bgb -bgf direct
ntexconv 004_01_mictest.bmp -no -bg -bgb -bgf direct
ntexconv 006_01_pokecenter.bmp -no -bg -bgb -bgf direct
ntexconv 007_01_pasocom.bmp -no -bg -bgb -bgf direct
ntexconv 028_02_ir.bmp -no -bg -bgb -bgf direct
ntexconv 028_01_unionroom.bmp -no -bg -bgb -bgf direct
ntexconv 009_01_wificlub.bmp -no -bg -bgb -bgf direct
ntexconv 010_01_globalterminal.bmp -no -bg -bgb -bgf direct
ntexconv 030_01_singlebattle.bmp -no -bg -bgb -bgf direct
ntexconv 031_01_doublebattle.bmp -no -bg -bgb -bgf direct
ntexconv 032_01_triplebattle.bmp -no -bg -bgb -bgf direct
ntexconv 032_02_idou.bmp -no -bg -bgb -bgf direct
ntexconv 033_01_rotationbattle.bmp -no -bg -bgb -bgf direct
ntexconv 033_02_kaitenmark.bmp -no -bg -bgb -bgf direct
ntexconv 034_01_support.bmp -no -bg -bgb -bgf direct
ntexconv 008_01_unionroom.bmp -no -bg -bgb -bgf direct
ntexconv 009_02_roomnonaka.bmp -no -bg -bgb -bgf direct
ntexconv 009_03_voicechat.bmp -no -bg -bgb -bgf direct
ntexconv 014_01_tomodati_techo.bmp -no -bg -bgb -bgf direct
ntexconv 014_02_nyuryoku.bmp -no -bg -bgb -bgf direct
ntexconv 012_01_cgear_power.bmp -no -bg -bgb -bgf direct
ntexconv 012_02_cgear_custom.bmp -no -bg -bgb -bgf direct
ntexconv 012_03_cgear_shitabou.bmp -no -bg -bgb -bgf direct
ntexconv 012_07_cgear_tanin.bmp -no -bg -bgb -bgf direct
ntexconv 012_04_cgear_sankaku.bmp -no -bg -bgb -bgf direct
ntexconv 012_05_cgear_fukidashi.bmp -no -bg -bgb -bgf direct
ntexconv 012_06_cgear_egao.bmp -no -bg -bgb -bgf direct
ntexconv 013_01_honbumae.bmp -no -bg -bgb -bgf direct
ntexconv 013_02_engraph.bmp -no -bg -bgb -bgf direct
ntexconv 015_02_mukeau.bmp -no -bg -bgb -bgf direct
ntexconv 039_01_gamesync.bmp -no -bg -bgb -bgf direct
ntexconv 039_02_midori.bmp -no -bg -bgb -bgf direct
ntexconv 039_03_ao.bmp -no -bg -bgb -bgf direct
ntexconv 039_04_aka.bmp -no -bg -bgb -bgf direct
ntexconv 040_01_wireless.bmp -no -bg -bgb -bgf direct
ntexconv 029_02_linkbridge.bmp -no -bg -bgb -bgf direct
ntexconv 029_03_shitagamen.bmp -no -bg -bgb -bgf direct
ntexconv 029_04_mission.bmp -no -bg -bgb -bgf direct
ntexconv 029_05_jump.bmp -no -bg -bgb -bgf direct
ntexconv 029_01_linktree.bmp -no -bg -bgb -bgf direct
ntexconv 019_01_taisetu.bmp -no -bg -bgb -bgf direct
ntexconv 019_02_motaseru.bmp -no -bg -bgb -bgf direct
ntexconv 021_01_zukan.bmp -no -bg -bgb -bgf direct
ntexconv 005_01_battle.bmp -no -bg -bgb -bgf direct
ntexconv 022_01_aishou.bmp -no -bg -bgb -bgf direct
ntexconv 000_01_wazabunrui.bmp -no -bg -bgb -bgf direct
ntexconv 024_01_oya.bmp -no -bg -bgb -bgf direct
ntexconv 024_02_are.bmp -no -bg -bgb -bgf direct
ntexconv 023_01_status.bmp -no -bg -bgb -bgf direct
ntexconv 041_01_pokerus.bmp -no -bg -bgb -bgf direct
ntexconv 042_01_dowsing.bmp -no -bg -bgb -bgf direct
ntexconv 025_02_yobidasi.bmp -no -bg -bgb -bgf direct
ntexconv 025_03_livecasterwificlub.bmp -no -bg -bgb -bgf direct
ntexconv 025_04_lockon.bmp -no -bg -bgb -bgf direct
ntexconv 025_05_migibutton.bmp -no -bg -bgb -bgf direct
ntexconv 026_01_badge_black.bmp -no -bg -bgb -bgf direct
ntexconv 027_01_benrimenu.bmp -no -bg -bgb -bgf direct
ntexconv 027_02_checkbox.bmp -no -bg -bgb -bgf direct
ntexconv 027_04_select.bmp -no -bg -bgb -bgf direct
ntexconv 016_01_dsimenu.bmp -no -bg -bgb -bgf direct
ntexconv 016_02_erabu.bmp -no -bg -bgb -bgf direct
ntexconv 017_01_sitagamen.bmp -no -bg -bgb -bgf direct
ntexconv 017_02_uegamen.bmp -no -bg -bgb -bgf direct
ntexconv 017_03_kemuri.bmp -no -bg -bgb -bgf direct
ntexconv bg.bmp -no -bg -bgb -bgf direct
