ntexconv 001_01_x_menu.bmp -no -bg -bgb -bgf direct
ntexconv 002_01_title.bmp -no -bg -bgb -bgf direct
ntexconv 003_01_titlemenu.bmp -no -bg -bgb -bgf direct
ntexconv 003_02_haitatuin.bmp -no -bg -bgb -bgf direct
ntexconv 003_03_hushigina_card.bmp -no -bg -bgb -bgf direct
ntexconv 004_01_mictest.bmp -no -bg -bgb -bgf direct
ntexconv 006_01_pokecenter.bmp -no -bg -bgb -bgf direct
ntexconv 007_01_pasocom.bmp -no -bg -bgb -bgf direct
ntexconv 028_02_ir.bmp -no -bg -bgb -bgf direct
ntexconv 028_01_unionroom.bmp -no -bg -bgb -bgf direct
ntexconv 009_01_wificlub.bmp -no -bg -bgb -bgf direct
ntexconv 010_01_globalterminal.bmp -no -bg -bgb -bgf direct
ntexconv 008_01_unionroom.bmp -no -bg -bgb -bgf direct
ntexconv 009_02_roomnonaka.bmp -no -bg -bgb -bgf direct
ntexconv 009_03_voicechat.bmp -no -bg -bgb -bgf direct
ntexconv 014_01_tomodati_techo.bmp -no -bg -bgb -bgf direct
ntexconv 014_02_nyuryoku.bmp -no -bg -bgb -bgf direct
ntexconv 012_01_cgear_power.bmp -no -bg -bgb -bgf direct
ntexconv 012_02_cgear_custom.bmp -no -bg -bgb -bgf direct
ntexconv 012_03_cgear_shitabou.bmp -no -bg -bgb -bgf direct
ntexconv 013_01_honbumae.bmp -no -bg -bgb -bgf direct
ntexconv 013_02_engraph.bmp -no -bg -bgb -bgf direct
ntexconv 013_03_chosamiru.bmp -no -bg -bgb -bgf direct
ntexconv 015_01_irmenu.bmp -no -bg -bgb -bgf direct
ntexconv 015_02_mukeau.bmp -no -bg -bgb -bgf direct
ntexconv 016_01_dsimenu.bmp -no -bg -bgb -bgf direct
ntexconv 016_02_erabu.bmp -no -bg -bgb -bgf direct
ntexconv 017_01_sitagamen.bmp -no -bg -bgb -bgf direct
ntexconv 017_02_uegamen.bmp -no -bg -bgb -bgf direct
ntexconv 017_03_kemuri.bmp -no -bg -bgb -bgf direct
ntexconv 018_01_battlebox.bmp -no -bg -bgb -bgf direct
ntexconv 019_01_taisetu.bmp -no -bg -bgb -bgf direct
ntexconv 019_02_motaseru.bmp -no -bg -bgb -bgf direct
ntexconv 020_02_ura.bmp -no -bg -bgb -bgf direct
ntexconv 020_03_badge.bmp -no -bg -bgb -bgf direct
ntexconv 021_01_zukan.bmp -no -bg -bgb -bgf direct
ntexconv 005_01_battle.bmp -no -bg -bgb -bgf direct
ntexconv 022_01_aishou.bmp -no -bg -bgb -bgf direct
ntexconv 024_01_oya.bmp -no -bg -bgb -bgf direct
ntexconv 024_02_are.bmp -no -bg -bgb -bgf direct
ntexconv 023_01_status.bmp -no -bg -bgb -bgf direct
ntexconv 011_01_run.bmp -no -bg -bgb -bgf direct
ntexconv 025_01_wireless.bmp -no -bg -bgb -bgf direct
ntexconv 025_02_yobidasi.bmp -no -bg -bgb -bgf direct
ntexconv 025_03_livecasterwificlub.bmp -no -bg -bgb -bgf direct
ntexconv 025_04_lockon.bmp -no -bg -bgb -bgf direct
ntexconv 025_05_migibutton.bmp -no -bg -bgb -bgf direct
ntexconv 026_01_badge.bmp -no -bg -bgb -bgf direct
ntexconv 026_02_iukoto.bmp -no -bg -bgb -bgf direct
ntexconv 027_01_benrimenu.bmp -no -bg -bgb -bgf direct
ntexconv 027_02_checkbox.bmp -no -bg -bgb -bgf direct
ntexconv 027_03_checkbox2.bmp -no -bg -bgb -bgf direct
ntexconv 027_04_select.bmp -no -bg -bgb -bgf direct
ntexconv bg.bmp -no -bg -bgb -bgf direct
