//======================================================================
/*
 * @file	enceffno_def.h
 * @brief	エンカウントエフェクトナンバー定義
 * @author saito
 */
//======================================================================

#pragma once

typedef enum {
  ENCEFFID_WILD_NORMAL = 0,
  ENCEFFID_WILD_HEIGH,
  ENCEFFID_WILD_WATER,
  ENCEFFID_WILD_INNER,
  ENCEFFID_WILD_DESERT,

  ENCEFFID_TR_NORMAL,
  ENCEFFID_TR_WATER,
  ENCEFFID_TR_INNER,
  ENCEFFID_TR_DESERT,

  ENCEFFID_SUBWAY,

  ENCEFFID_RIVAL,         //10
  ENCEFFID_SUPPORT,
  ENCEFFID_LEADER1A,
  ENCEFFID_LEADER1B,
  ENCEFFID_LEADER1C,
  ENCEFFID_LEADER2,
  ENCEFFID_LEADER3,
  ENCEFFID_LEADER4,
  ENCEFFID_LEADER5,
  ENCEFFID_LEADER6,
  ENCEFFID_LEADER7,       //20
  ENCEFFID_LEADER8A,
  ENCEFFID_LEADER8B,
  ENCEFFID_BIGFOUR1,
  ENCEFFID_BIGFOUR2,
  ENCEFFID_BIGFOUR3,
  ENCEFFID_BIGFOUR4,
  ENCEFFID_CHAMP,
  ENCEFFID_PRAZUMA,
  ENCEFFID_BOSS,
  ENCEFFID_SAGE,          //30

  ENCEFFID_EFF_POKE,
  ENCEFFID_PACKAGE_POKE,
  ENCEFFID_MOVE_POKE,
  ENCEFFID_THREE_POKE,

  ENCEFFID_MAX,
}ENCEFF_ID;
