//======================================================================
/**
 * @file  fieldobj_drawdata.c
 * @brief  フィールド動作モデル描画データ
 * @author  kagaya
 * @date  05.07.20
 */
//======================================================================
#include "fldmmdl.h"
#include "fldmmdl_procdraw.h"

//======================================================================
//  define
//======================================================================
#define ANMFLIP_ON (GFL_BBDACT_ANMFLIP_ON)
#define ANMFLIP_OFF (GFL_BBDACT_ANMFLIP_OFF)

//======================================================================
//  フィールド動作モデル　描画関数テーブル
//======================================================================
const MMDL_DRAW_PROC_LIST * const
  DATA_MMDL_DRAW_PROC_LIST_Tbl[MMDL_DRAWPROCNO_MAX] =
{
  &DATA_MMDL_DRAWPROCLIST_Non,    //描画無し
  &DATA_MMDL_DRAWPROCLIST_Hero,  //自機
  &DATA_MMDL_DRAWPROCLIST_BlAct,  //通常ビルボードアクター
  &DATA_MMDL_DRAWPROCLIST_CycleHero,  //自機自転車
  &DATA_MMDL_DRAWPROCLIST_SwimHero,  //自機波乗り
  &DATA_MMDL_DRAWPROCLIST_BlActAlwaysAnime, //通常ビルボード＋常にアニメ
  &DATA_MMDL_DRAWPROCLIST_ItemGetHero, //自機アイテムゲット
  &DATA_MMDL_DRAWPROCLIST_PCAzukeHero, //自機PC預け
  &DATA_MMDL_DRAWPROCLIST_BlActOnePatternLoop, //ビルボード1パターンアニメ
//&DATA_MMDL_DRAWPROCLIST_BlActOnePattern, //ビルボード1パターンアニメ
  &DATA_MMDL_DRAWPROCLIST_BlActAct, //汎用+演技
  &DATA_MMDL_DRAWPROCLIST_TsurePoke, //連れ歩きポケモン
  &DATA_MMDL_DRAWPROCLIST_TsurePoke, //連れ歩きポケモン(上下アニメスピード1/2 関数内で分岐してます)
  &DATA_MMDL_DRAWPROCLIST_Model, //モデル描画
  &DATA_MMDL_DRAWPROCLIST_FishingHero, //釣り自機
  &DATA_MMDL_DRAWPROCLIST_YureHero, //揺れ自機
  &DATA_MMDL_DRAWPROCLIST_BlActAlwaysAnime, //通常ビルボード＋常にアニメ
  &DATA_MMDL_DRAWPROCLIST_BlActShinMu, //ポケモン シン・ム
  &DATA_MMDL_DRAWPROCLIST_BlActSpider, //くもの巣
  &DATA_MMDL_DRAWPROCLIST_BlActMelodyer, //<ポケモン メロディア
};

//======================================================================
//  ビルボードアニメデータ　自機アニメ
//======================================================================
enum
{
  TEXIDX_HERO_U_STOP0,
  TEXIDX_HERO_U_WALK0,
  TEXIDX_HERO_U_WALK1,
  TEXIDX_HERO_D_STOP0,
  TEXIDX_HERO_D_WALK0,
  TEXIDX_HERO_D_WALK1,
  TEXIDX_HERO_L_STOP0,
  TEXIDX_HERO_L_WALK0,
  TEXIDX_HERO_L_WALK1,
  TEXIDX_HERO_R_STOP0,
  TEXIDX_HERO_R_WALK0,
  TEXIDX_HERO_R_WALK1,
  TEXIDX_HERO_U_DASH_STOP0,
  TEXIDX_HERO_U_DASH_WALK0,
  TEXIDX_HERO_U_DASH_WALK1,
  TEXIDX_HERO_D_DASH_STOP0,
  TEXIDX_HERO_D_DASH_WALK0,
  TEXIDX_HERO_D_DASH_WALK1,
  TEXIDX_HERO_L_DASH_STOP0,
  TEXIDX_HERO_L_DASH_WALK0,
  TEXIDX_HERO_L_DASH_WALK1,
  TEXIDX_HERO_R_DASH_STOP0,
  TEXIDX_HERO_R_DASH_WALK0,
  TEXIDX_HERO_R_DASH_WALK1,
};

//stop
static const GFL_BBDACT_ANM DATA_BlActHero_StopU[] = {
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_StopD[] = {
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_StopL[] = {
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_StopR[] = {
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
//walk 32
static const GFL_BBDACT_ANM DATA_BlActHero_WalkU32F[] = {
  {TEXIDX_HERO_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkD32F[] = {
  {TEXIDX_HERO_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkL32F[] = {
  {TEXIDX_HERO_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkR32F[] = {
  {TEXIDX_HERO_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//walk 16
static const GFL_BBDACT_ANM DATA_BlActHero_WalkU16F[] = {
  {TEXIDX_HERO_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkD16F[] = {
  {TEXIDX_HERO_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkL16F[] = {
  {TEXIDX_HERO_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkR16F[] = {
  {TEXIDX_HERO_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//walk 8
static const GFL_BBDACT_ANM DATA_BlActHero_WalkU8F[] = {
  {TEXIDX_HERO_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkD8F[] = {
  {TEXIDX_HERO_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkL8F[] = {
  {TEXIDX_HERO_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkR8F[] = {
  {TEXIDX_HERO_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//walk 4
static const GFL_BBDACT_ANM DATA_BlActHero_WalkU4F[] = {
  {TEXIDX_HERO_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkD4F[] = {
  {TEXIDX_HERO_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkL4F[] = {
  {TEXIDX_HERO_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkR4F[] = {
  {TEXIDX_HERO_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//walk 2
static const GFL_BBDACT_ANM DATA_BlActHero_WalkU2F[] = {
  {TEXIDX_HERO_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkD2F[] = {
  {TEXIDX_HERO_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkL2F[] = {
  {TEXIDX_HERO_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkR2F[] = {
  {TEXIDX_HERO_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//walk 6
static const GFL_BBDACT_ANM DATA_BlActHero_WalkU6F[] = {
  {TEXIDX_HERO_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkD6F[] = {
  {TEXIDX_HERO_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkL6F[] = {
  {TEXIDX_HERO_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkR6F[] = {
  {TEXIDX_HERO_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//walk 3
static const GFL_BBDACT_ANM DATA_BlActHero_WalkU3F[] = {
  {TEXIDX_HERO_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkD3F[] = {
  {TEXIDX_HERO_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkL3F[] = {
  {TEXIDX_HERO_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkR3F[] = {
  {TEXIDX_HERO_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HERO_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//walk 7
static const GFL_BBDACT_ANM DATA_BlActHero_WalkU7F[] = {
  {TEXIDX_HERO_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkD7F[] = {
  {TEXIDX_HERO_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkL7F[] = {
  {TEXIDX_HERO_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkR7F[] = {
  {TEXIDX_HERO_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HERO_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//walk 10
static const GFL_BBDACT_ANM DATA_BlActHero_WalkU12F[] = {
  {TEXIDX_HERO_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_U_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkD12F[] = {
  {TEXIDX_HERO_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_D_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkL12F[] = {
  {TEXIDX_HERO_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_L_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_WalkR12F[] = {
  {TEXIDX_HERO_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HERO_R_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//dash 4 本当は2frame単位でのアニメだが早く見えてしまう為4frame
static const GFL_BBDACT_ANM DATA_BlActHero_DashU4F[] = {
  {TEXIDX_HERO_U_DASH_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_DASH_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_DashD4F[] = {
  {TEXIDX_HERO_D_DASH_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_DASH_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_DashL4F[] = {
  {TEXIDX_HERO_L_DASH_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_DASH_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_DashR4F[] = {
  {TEXIDX_HERO_R_DASH_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_DASH_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
//dash 6
static const GFL_BBDACT_ANM DATA_BlActHero_DashU6F[] = {
  {TEXIDX_HERO_U_DASH_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_DASH_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_U_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_DashD6F[] = {
  {TEXIDX_HERO_D_DASH_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_DASH_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_D_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_DashL6F[] = {
  {TEXIDX_HERO_L_DASH_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_DASH_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_L_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActHero_DashR6F[] = {
  {TEXIDX_HERO_R_DASH_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_DASH_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HERO_R_DASH_STOP0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM * DATA_BlActHeroTbl[DRAW_STA_HERO_DIR4_MAX] = {
  DATA_BlActHero_StopU,  //DRAW_STA_STOP
  DATA_BlActHero_StopD,
  DATA_BlActHero_StopL,
  DATA_BlActHero_StopR,
  DATA_BlActHero_WalkU32F,  //DRAW_STA_WALK_32F
  DATA_BlActHero_WalkD32F,
  DATA_BlActHero_WalkL32F,
  DATA_BlActHero_WalkR32F,
  DATA_BlActHero_WalkU16F,  //DRAW_STA_WALK_16F
  DATA_BlActHero_WalkD16F,
  DATA_BlActHero_WalkL16F,
  DATA_BlActHero_WalkR16F,
  DATA_BlActHero_WalkU8F,  //DRAW_STA_WALK_8F
  DATA_BlActHero_WalkD8F,
  DATA_BlActHero_WalkL8F,
  DATA_BlActHero_WalkR8F,
  DATA_BlActHero_WalkU4F,  //DRAW_STA_WALK_4F
  DATA_BlActHero_WalkD4F,
  DATA_BlActHero_WalkL4F,
  DATA_BlActHero_WalkR4F,
  DATA_BlActHero_WalkU2F,  //DRAW_STA_WALK_2F
  DATA_BlActHero_WalkD2F,
  DATA_BlActHero_WalkL2F,
  DATA_BlActHero_WalkR2F,
  DATA_BlActHero_WalkU6F,  //DRAW_STA_WALK_6F
  DATA_BlActHero_WalkD6F,
  DATA_BlActHero_WalkL6F,
  DATA_BlActHero_WalkR6F,
  DATA_BlActHero_WalkU3F,  //DRAW_STA_WALK_3F
  DATA_BlActHero_WalkD3F,
  DATA_BlActHero_WalkL3F,
  DATA_BlActHero_WalkR3F,
  DATA_BlActHero_WalkU7F,  //DRAW_STA_WALK_7F
  DATA_BlActHero_WalkD7F,
  DATA_BlActHero_WalkL7F,
  DATA_BlActHero_WalkR7F,
  DATA_BlActHero_WalkU12F,  //DRAW_STA_WALK_12F
  DATA_BlActHero_WalkD12F,
  DATA_BlActHero_WalkL12F,
  DATA_BlActHero_WalkR12F,
  DATA_BlActHero_DashU4F,  //DRAW_STA_HERO_DASH_4F
  DATA_BlActHero_DashD4F,
  DATA_BlActHero_DashL4F,
  DATA_BlActHero_DashR4F,
  DATA_BlActHero_DashU6F,  //DRAW_STA_HERO_DASH_6F
  DATA_BlActHero_DashD6F,
  DATA_BlActHero_DashL6F,
  DATA_BlActHero_DashR6F,
};

//======================================================================
//  ビルボードアニメデータ　自機波乗りアニメ
//======================================================================
//--------------------------------------------------------------
//  自機波乗りアニメ 上
//--------------------------------------------------------------
static const GFL_BBDACT_ANM DATA_BlActSwimHero_U[] = {
  {0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

//--------------------------------------------------------------
//  自機波乗りアニメ　下
//--------------------------------------------------------------
static const GFL_BBDACT_ANM DATA_BlActSwimHero_D[] = {
  {1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

//--------------------------------------------------------------
//  自機波乗りアニメ　左
//--------------------------------------------------------------
static const GFL_BBDACT_ANM DATA_BlActSwimHero_L[] = {
  {2,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

//--------------------------------------------------------------
//  自機波乗りアニメ　右
//--------------------------------------------------------------
static const GFL_BBDACT_ANM DATA_BlActSwimHero_R[] = {
  {2,ANMFLIP_ON,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

//--------------------------------------------------------------
//  自機波乗りアニメ　データテーブル
//--------------------------------------------------------------
static const GFL_BBDACT_ANM * DATA_BlActSwimHeroTbl[DRAW_STA_SWIMHERO_MAX] =
{
  DATA_BlActSwimHero_U,  //DRAW_STA_STOP
  DATA_BlActSwimHero_D,
  DATA_BlActSwimHero_L,
  DATA_BlActSwimHero_R,
};

//======================================================================
// 人型汎用　フリップ有り
//======================================================================
enum
{
  TEXIDX_FLIP_U_STOP,
  TEXIDX_FLIP_U_WALK,
  TEXIDX_FLIP_D_STOP,
  TEXIDX_FLIP_D_WALK,
  TEXIDX_FLIP_L_STOP,
  TEXIDX_FLIP_L_WALK0,
  TEXIDX_FLIP_L_WALK1,
  TEXIDX_FLIP_MAX,
  
  //ポケセンお姉さん用
  TEXIDX_FLIP_BOW_0 = TEXIDX_FLIP_MAX,
  TEXIDX_FLIP_BOW_1,
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_StopU[] =
{
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_StopD[] = {
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_StopL[] = {
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_StopR[] = {
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkU32F[] = {
  {TEXIDX_FLIP_U_WALK,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_U_WALK,ANMFLIP_ON,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkD32F[] = {
  {TEXIDX_FLIP_D_WALK,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_D_WALK,ANMFLIP_ON,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkL32F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkR32F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_ON,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_ON,ANMFLIP_OFF,16},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkU16F[] = {
  {TEXIDX_FLIP_U_WALK,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_U_WALK,ANMFLIP_ON,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkD16F[] = {
  {TEXIDX_FLIP_D_WALK,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_D_WALK,ANMFLIP_ON,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkL16F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkR16F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_ON,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_ON,ANMFLIP_OFF,8},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkU8F[] = {
  {TEXIDX_FLIP_U_WALK,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_U_WALK,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkD8F[] = {
  {TEXIDX_FLIP_D_WALK,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_D_WALK,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkL8F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkR8F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkU4F[] = {
  {TEXIDX_FLIP_U_WALK,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_U_WALK,ANMFLIP_ON,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkD4F[] = {
  {TEXIDX_FLIP_D_WALK,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_D_WALK,ANMFLIP_ON,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkL4F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkR4F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_ON,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_ON,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkU2F[] = {
  {TEXIDX_FLIP_U_WALK,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_U_WALK,ANMFLIP_ON,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkD2F[] = {
  {TEXIDX_FLIP_D_WALK,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_D_WALK,ANMFLIP_ON,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkL2F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkR2F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_ON,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_ON,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkU6F[] = {
  {TEXIDX_FLIP_U_WALK,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_U_WALK,ANMFLIP_ON,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkD6F[] = {
  {TEXIDX_FLIP_D_WALK,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_D_WALK,ANMFLIP_ON,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkL6F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkR6F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_ON,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_ON,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkU3F[] = {
  {TEXIDX_FLIP_U_WALK,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_U_WALK,ANMFLIP_ON,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkD3F[] = {
  {TEXIDX_FLIP_D_WALK,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_D_WALK,ANMFLIP_ON,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkL3F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkR3F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_ON,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,1},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_ON,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkU7F[] = {
  {TEXIDX_FLIP_U_WALK,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_U_WALK,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkD7F[] = {
  {TEXIDX_FLIP_D_WALK,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_D_WALK,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkL7F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkR7F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,3},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkU12F[] = {
  {TEXIDX_FLIP_U_WALK,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_U_WALK,ANMFLIP_ON,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkD12F[] = {
  {TEXIDX_FLIP_D_WALK,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_D_WALK,ANMFLIP_ON,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkL12F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_WalkR12F[] = {
  {TEXIDX_FLIP_L_WALK0,ANMFLIP_ON,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_L_WALK1,ANMFLIP_ON,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_L_STOP,ANMFLIP_ON,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM * const DATA_BlActAnmFlipTbl[DRAW_STA_DIR4_MAX] =
{
  DATA_BlActAnmFlip_StopU,//DRWA_STA_STOP
  DATA_BlActAnmFlip_StopD,
  DATA_BlActAnmFlip_StopL,
  DATA_BlActAnmFlip_StopR,
  DATA_BlActAnmFlip_WalkU32F,//DRWA_STA_WALK_32F
  DATA_BlActAnmFlip_WalkD32F,
  DATA_BlActAnmFlip_WalkL32F,
  DATA_BlActAnmFlip_WalkR32F,
  DATA_BlActAnmFlip_WalkU16F,//DRWA_STA_WALK_16F
  DATA_BlActAnmFlip_WalkD16F,
  DATA_BlActAnmFlip_WalkL16F,
  DATA_BlActAnmFlip_WalkR16F,
  DATA_BlActAnmFlip_WalkU8F,//DRWA_STA_WALK_8F
  DATA_BlActAnmFlip_WalkD8F,
  DATA_BlActAnmFlip_WalkL8F,
  DATA_BlActAnmFlip_WalkR8F,
  DATA_BlActAnmFlip_WalkU4F,//DRWA_STA_WALK_4F
  DATA_BlActAnmFlip_WalkD4F,
  DATA_BlActAnmFlip_WalkL4F,
  DATA_BlActAnmFlip_WalkR4F,
  DATA_BlActAnmFlip_WalkU2F,//DRWA_STA_WALK_2F
  DATA_BlActAnmFlip_WalkD2F,
  DATA_BlActAnmFlip_WalkL2F,
  DATA_BlActAnmFlip_WalkR2F,
  DATA_BlActAnmFlip_WalkU6F,//DRWA_STA_WALK_6F
  DATA_BlActAnmFlip_WalkD6F,
  DATA_BlActAnmFlip_WalkL6F,
  DATA_BlActAnmFlip_WalkR6F,
  DATA_BlActAnmFlip_WalkU3F,//DRWA_STA_WALK_3F
  DATA_BlActAnmFlip_WalkD3F,
  DATA_BlActAnmFlip_WalkL3F,
  DATA_BlActAnmFlip_WalkR3F,
  DATA_BlActAnmFlip_WalkU7F,//DRWA_STA_WALK_7F
  DATA_BlActAnmFlip_WalkD7F,
  DATA_BlActAnmFlip_WalkL7F,
  DATA_BlActAnmFlip_WalkR7F,
  DATA_BlActAnmFlip_WalkU12F,//DRWA_STA_WALK_12F
  DATA_BlActAnmFlip_WalkD12F,
  DATA_BlActAnmFlip_WalkL12F,
  DATA_BlActAnmFlip_WalkR12F,
};

//--------------------------------------------------------------
/// ポケセンお姉さん用お辞儀アニメ
//--------------------------------------------------------------
static const GFL_BBDACT_ANM DATA_BlActAnmFlip_PCBow[] = {
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_FLIP_BOW_0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_BOW_1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_FLIP_BOW_0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM * const
  DATA_BlActAnmPcwomanTbl[DRAW_STA_PCWOMAN_DIR4_MAX] =
{
  DATA_BlActAnmFlip_StopU,//DRWA_STA_STOP
  DATA_BlActAnmFlip_StopD,
  DATA_BlActAnmFlip_StopL,
  DATA_BlActAnmFlip_StopR,
  DATA_BlActAnmFlip_WalkU32F,//DRWA_STA_WALK_32F
  DATA_BlActAnmFlip_WalkD32F,
  DATA_BlActAnmFlip_WalkL32F,
  DATA_BlActAnmFlip_WalkR32F,
  DATA_BlActAnmFlip_WalkU16F,//DRWA_STA_WALK_16F
  DATA_BlActAnmFlip_WalkD16F,
  DATA_BlActAnmFlip_WalkL16F,
  DATA_BlActAnmFlip_WalkR16F,
  DATA_BlActAnmFlip_WalkU8F,//DRWA_STA_WALK_8F
  DATA_BlActAnmFlip_WalkD8F,
  DATA_BlActAnmFlip_WalkL8F,
  DATA_BlActAnmFlip_WalkR8F,
  DATA_BlActAnmFlip_WalkU4F,//DRWA_STA_WALK_4F
  DATA_BlActAnmFlip_WalkD4F,
  DATA_BlActAnmFlip_WalkL4F,
  DATA_BlActAnmFlip_WalkR4F,
  DATA_BlActAnmFlip_WalkU2F,//DRWA_STA_WALK_2F
  DATA_BlActAnmFlip_WalkD2F,
  DATA_BlActAnmFlip_WalkL2F,
  DATA_BlActAnmFlip_WalkR2F,
  DATA_BlActAnmFlip_WalkU6F,//DRWA_STA_WALK_6F
  DATA_BlActAnmFlip_WalkD6F,
  DATA_BlActAnmFlip_WalkL6F,
  DATA_BlActAnmFlip_WalkR6F,
  DATA_BlActAnmFlip_WalkU3F,//DRWA_STA_WALK_3F
  DATA_BlActAnmFlip_WalkD3F,
  DATA_BlActAnmFlip_WalkL3F,
  DATA_BlActAnmFlip_WalkR3F,
  DATA_BlActAnmFlip_WalkU7F,//DRWA_STA_WALK_7F
  DATA_BlActAnmFlip_WalkD7F,
  DATA_BlActAnmFlip_WalkL7F,
  DATA_BlActAnmFlip_WalkR7F,
  DATA_BlActAnmFlip_WalkU12F,//DRWA_STA_WALK_12F
  DATA_BlActAnmFlip_WalkD12F,
  DATA_BlActAnmFlip_WalkL12F,
  DATA_BlActAnmFlip_WalkR12F,
  
  DATA_BlActAnmFlip_PCBow, //DRAW_STA_PC_BOW
};

//======================================================================
//  人物汎用 フリップ無し
//======================================================================
enum
{
  TEXIDX_NFLIP_U_STOP,
  TEXIDX_NFLIP_U_WALK0,
  TEXIDX_NFLIP_U_WALK1,
  TEXIDX_NFLIP_D_STOP,
  TEXIDX_NFLIP_D_WALK0,
  TEXIDX_NFLIP_D_WALK1,
  TEXIDX_NFLIP_L_STOP,
  TEXIDX_NFLIP_L_WALK0,
  TEXIDX_NFLIP_L_WALK1,
  TEXIDX_NFLIP_R_STOP,
  TEXIDX_NFLIP_R_WALK0,
  TEXIDX_NFLIP_R_WALK1,
  
  TEXIDX_NFLIP_MAX,
  TEXIDX_NFLIP_ACT0 = TEXIDX_NFLIP_MAX, //演技用
  TEXIDX_NFLIP_ACT1,
  TEXIDX_NFLIP_ACT2,
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_StopU[] =
{
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_StopD[] = {
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_StopL[] = {
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_StopR[] = {
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkU32F[] = {
  {TEXIDX_NFLIP_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkD32F[] = {
  {TEXIDX_NFLIP_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkL32F[] = {
  {TEXIDX_NFLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkR32F[] = {
  {TEXIDX_NFLIP_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkU16F[] = {
  {TEXIDX_NFLIP_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkD16F[] = {
  {TEXIDX_NFLIP_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkL16F[] = {
  {TEXIDX_NFLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkR16F[] = {
  {TEXIDX_NFLIP_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkU8F[] = {
  {TEXIDX_NFLIP_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkD8F[] = {
  {TEXIDX_NFLIP_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkL8F[] = {
  {TEXIDX_NFLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkR8F[] = {
  {TEXIDX_NFLIP_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkU4F[] = {
  {TEXIDX_NFLIP_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkD4F[] = {
  {TEXIDX_NFLIP_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkL4F[] = {
  {TEXIDX_NFLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkR4F[] = {
  {TEXIDX_NFLIP_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkU2F[] = {
  {TEXIDX_NFLIP_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkD2F[] = {
  {TEXIDX_NFLIP_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkL2F[] = {
  {TEXIDX_NFLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkR2F[] = {
  {TEXIDX_NFLIP_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkU6F[] = {
  {TEXIDX_NFLIP_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkD6F[] = {
  {TEXIDX_NFLIP_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkL6F[] = {
  {TEXIDX_NFLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkR6F[] = {
  {TEXIDX_NFLIP_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkU3F[] = {
  {TEXIDX_NFLIP_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkD3F[] = {
  {TEXIDX_NFLIP_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkL3F[] = {
  {TEXIDX_NFLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkR3F[] = {
  {TEXIDX_NFLIP_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_NFLIP_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkU7F[] = {
  {TEXIDX_NFLIP_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkD7F[] = {
  {TEXIDX_NFLIP_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkL7F[] = {
  {TEXIDX_NFLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkR7F[] = {
  {TEXIDX_NFLIP_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_NFLIP_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkU12F[] = {
  {TEXIDX_NFLIP_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkD12F[] = {
  {TEXIDX_NFLIP_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkL12F[] = {
  {TEXIDX_NFLIP_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_WalkR12F[] = {
  {TEXIDX_NFLIP_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_NFLIP_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM * const DATA_BlActAnmNonFlipTbl[DRAW_STA_DIR4_MAX] =
{
  DATA_BlActAnmNonFlip_StopU,//DRWA_STA_STOP
  DATA_BlActAnmNonFlip_StopD,
  DATA_BlActAnmNonFlip_StopL,
  DATA_BlActAnmNonFlip_StopR,
  DATA_BlActAnmNonFlip_WalkU32F,//DRWA_STA_WALK_32F
  DATA_BlActAnmNonFlip_WalkD32F,
  DATA_BlActAnmNonFlip_WalkL32F,
  DATA_BlActAnmNonFlip_WalkR32F,
  DATA_BlActAnmNonFlip_WalkU16F,//DRWA_STA_WALK_16F
  DATA_BlActAnmNonFlip_WalkD16F,
  DATA_BlActAnmNonFlip_WalkL16F,
  DATA_BlActAnmNonFlip_WalkR16F,
  DATA_BlActAnmNonFlip_WalkU8F,//DRWA_STA_WALK_8F
  DATA_BlActAnmNonFlip_WalkD8F,
  DATA_BlActAnmNonFlip_WalkL8F,
  DATA_BlActAnmNonFlip_WalkR8F,
  DATA_BlActAnmNonFlip_WalkU4F,//DRWA_STA_WALK_4F
  DATA_BlActAnmNonFlip_WalkD4F,
  DATA_BlActAnmNonFlip_WalkL4F,
  DATA_BlActAnmNonFlip_WalkR4F,
  DATA_BlActAnmNonFlip_WalkU2F,//DRWA_STA_WALK_2F
  DATA_BlActAnmNonFlip_WalkD2F,
  DATA_BlActAnmNonFlip_WalkL2F,
  DATA_BlActAnmNonFlip_WalkR2F,
  DATA_BlActAnmNonFlip_WalkU6F,//DRWA_STA_WALK_6F
  DATA_BlActAnmNonFlip_WalkD6F,
  DATA_BlActAnmNonFlip_WalkL6F,
  DATA_BlActAnmNonFlip_WalkR6F,
  DATA_BlActAnmNonFlip_WalkU3F,//DRWA_STA_WALK_3F
  DATA_BlActAnmNonFlip_WalkD3F,
  DATA_BlActAnmNonFlip_WalkL3F,
  DATA_BlActAnmNonFlip_WalkR3F,
  DATA_BlActAnmNonFlip_WalkU12F,//DRWA_STA_WALK_12F
  DATA_BlActAnmNonFlip_WalkD12F,
  DATA_BlActAnmNonFlip_WalkL12F,
  DATA_BlActAnmNonFlip_WalkR12F,
};

//--------------------------------------------------------------
/// MMDL_BLACT_ANMTBLNO_NFLIP_ACT0用　フリップなし+演技3パターン
//--------------------------------------------------------------
static const GFL_BBDACT_ANM DATA_BlActAnmNonFlip_Act0[] = {
  {TEXIDX_NFLIP_ACT0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_ACT1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_NFLIP_ACT2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM * const DATA_BlActAnmNonFlipAct0Tbl[DRAW_STA_ACT0_DIR4_MAX] =
{
  DATA_BlActAnmNonFlip_StopU,//DRWA_STA_STOP
  DATA_BlActAnmNonFlip_StopD,
  DATA_BlActAnmNonFlip_StopL,
  DATA_BlActAnmNonFlip_StopR,
  DATA_BlActAnmNonFlip_WalkU32F,//DRWA_STA_WALK_32F
  DATA_BlActAnmNonFlip_WalkD32F,
  DATA_BlActAnmNonFlip_WalkL32F,
  DATA_BlActAnmNonFlip_WalkR32F,
  DATA_BlActAnmNonFlip_WalkU16F,//DRWA_STA_WALK_16F
  DATA_BlActAnmNonFlip_WalkD16F,
  DATA_BlActAnmNonFlip_WalkL16F,
  DATA_BlActAnmNonFlip_WalkR16F,
  DATA_BlActAnmNonFlip_WalkU8F,//DRWA_STA_WALK_8F
  DATA_BlActAnmNonFlip_WalkD8F,
  DATA_BlActAnmNonFlip_WalkL8F,
  DATA_BlActAnmNonFlip_WalkR8F,
  DATA_BlActAnmNonFlip_WalkU4F,//DRWA_STA_WALK_4F
  DATA_BlActAnmNonFlip_WalkD4F,
  DATA_BlActAnmNonFlip_WalkL4F,
  DATA_BlActAnmNonFlip_WalkR4F,
  DATA_BlActAnmNonFlip_WalkU2F,//DRWA_STA_WALK_2F
  DATA_BlActAnmNonFlip_WalkD2F,
  DATA_BlActAnmNonFlip_WalkL2F,
  DATA_BlActAnmNonFlip_WalkR2F,
  DATA_BlActAnmNonFlip_WalkU6F,//DRWA_STA_WALK_6F
  DATA_BlActAnmNonFlip_WalkD6F,
  DATA_BlActAnmNonFlip_WalkL6F,
  DATA_BlActAnmNonFlip_WalkR6F,
  DATA_BlActAnmNonFlip_WalkU3F,//DRWA_STA_WALK_3F
  DATA_BlActAnmNonFlip_WalkD3F,
  DATA_BlActAnmNonFlip_WalkL3F,
  DATA_BlActAnmNonFlip_WalkR3F,
  DATA_BlActAnmNonFlip_WalkU12F,//DRWA_STA_WALK_12F
  DATA_BlActAnmNonFlip_WalkD12F,
  DATA_BlActAnmNonFlip_WalkL12F,
  DATA_BlActAnmNonFlip_WalkR12F,
  
  DATA_BlActAnmNonFlip_Act0, //DRAW_STA_ACT0
};

//======================================================================
//  自機自転車 フリップ無し＆特殊停止パターン
//======================================================================
enum
{
  TEXIDX_HCYCLE_U_STOP,
  TEXIDX_HCYCLE_U_WALK0,
  TEXIDX_HCYCLE_U_WALK1,
  TEXIDX_HCYCLE_D_STOP,
  TEXIDX_HCYCLE_D_WALK0,
  TEXIDX_HCYCLE_D_WALK1,
  TEXIDX_HCYCLE_L_STOP,
  TEXIDX_HCYCLE_L_WALK0,
  TEXIDX_HCYCLE_L_WALK1,
  TEXIDX_HCYCLE_R_STOP,
  TEXIDX_HCYCLE_R_WALK0,
  TEXIDX_HCYCLE_R_WALK1,
  TEXIDX_HCYCLE_U_STAND,
  TEXIDX_HCYCLE_D_STAND,
  TEXIDX_HCYCLE_L_STAND,
  TEXIDX_HCYCLE_R_STAND,
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_StopU[] =
{
  {TEXIDX_HCYCLE_U_STAND,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_StopD[] = {
  {TEXIDX_HCYCLE_D_STAND,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_StopL[] = {
  {TEXIDX_HCYCLE_L_STAND,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_StopR[] = {
  {TEXIDX_HCYCLE_R_STAND,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkU32F[] = {
  {TEXIDX_HCYCLE_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkD32F[] = {
  {TEXIDX_HCYCLE_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkL32F[] = {
  {TEXIDX_HCYCLE_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkR32F[] = {
  {TEXIDX_HCYCLE_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,16},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkU16F[] = {
  {TEXIDX_HCYCLE_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkD16F[] = {
  {TEXIDX_HCYCLE_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkL16F[] = {
  {TEXIDX_HCYCLE_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkR16F[] = {
  {TEXIDX_HCYCLE_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkU8F[] = {
  {TEXIDX_HCYCLE_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkD8F[] = {
  {TEXIDX_HCYCLE_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkL8F[] = {
  {TEXIDX_HCYCLE_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkR8F[] = {
  {TEXIDX_HCYCLE_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkU4F[] = {
  {TEXIDX_HCYCLE_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkD4F[] = {
  {TEXIDX_HCYCLE_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkL4F[] = {
  {TEXIDX_HCYCLE_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkR4F[] = {
  {TEXIDX_HCYCLE_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkU2F[] = {
  {TEXIDX_HCYCLE_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkD2F[] = {
  {TEXIDX_HCYCLE_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkL2F[] = {
  {TEXIDX_HCYCLE_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkR2F[] = {
  {TEXIDX_HCYCLE_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkU6F[] = {
  {TEXIDX_HCYCLE_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkD6F[] = {
  {TEXIDX_HCYCLE_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkL6F[] = {
  {TEXIDX_HCYCLE_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkR6F[] = {
  {TEXIDX_HCYCLE_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkU3F[] = {
  {TEXIDX_HCYCLE_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkD3F[] = {
  {TEXIDX_HCYCLE_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkL3F[] = {
  {TEXIDX_HCYCLE_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkR3F[] = {
  {TEXIDX_HCYCLE_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {TEXIDX_HCYCLE_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkU7F[] = {
  {TEXIDX_HCYCLE_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkD7F[] = {
  {TEXIDX_HCYCLE_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkL7F[] = {
  {TEXIDX_HCYCLE_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkR7F[] = {
  {TEXIDX_HCYCLE_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {TEXIDX_HCYCLE_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,3},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkU12F[] = {
  {TEXIDX_HCYCLE_U_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_U_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_U_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkD12F[] = {
  {TEXIDX_HCYCLE_D_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_D_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_D_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkL12F[] = {
  {TEXIDX_HCYCLE_L_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_L_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_L_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActAnmHeroCycle_WalkR12F[] = {
  {TEXIDX_HCYCLE_R_WALK0,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_R_WALK1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_HCYCLE_R_STOP,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM * const DATA_BlActAnmHeroCycleTbl[DRAW_STA_DIR4_MAX] =
{
  DATA_BlActAnmHeroCycle_StopU,//DRWA_STA_STOP
  DATA_BlActAnmHeroCycle_StopD,
  DATA_BlActAnmHeroCycle_StopL,
  DATA_BlActAnmHeroCycle_StopR,
  DATA_BlActAnmHeroCycle_WalkU32F,//DRWA_STA_WALK_32F
  DATA_BlActAnmHeroCycle_WalkD32F,
  DATA_BlActAnmHeroCycle_WalkL32F,
  DATA_BlActAnmHeroCycle_WalkR32F,
  DATA_BlActAnmHeroCycle_WalkU16F,//DRWA_STA_WALK_16F
  DATA_BlActAnmHeroCycle_WalkD16F,
  DATA_BlActAnmHeroCycle_WalkL16F,
  DATA_BlActAnmHeroCycle_WalkR16F,
  DATA_BlActAnmHeroCycle_WalkU8F,//DRWA_STA_WALK_8F
  DATA_BlActAnmHeroCycle_WalkD8F,
  DATA_BlActAnmHeroCycle_WalkL8F,
  DATA_BlActAnmHeroCycle_WalkR8F,
  DATA_BlActAnmHeroCycle_WalkU4F,//DRWA_STA_WALK_4F
  DATA_BlActAnmHeroCycle_WalkD4F,
  DATA_BlActAnmHeroCycle_WalkL4F,
  DATA_BlActAnmHeroCycle_WalkR4F,
#if 0
  DATA_BlActAnmHeroCycle_WalkU2F,//DRWA_STA_WALK_2F
  DATA_BlActAnmHeroCycle_WalkD2F,
  DATA_BlActAnmHeroCycle_WalkL2F,
  DATA_BlActAnmHeroCycle_WalkR2F,
#else //2Fアニメ早すぎとの事で、4Fを当てる
  DATA_BlActAnmHeroCycle_WalkU4F,//DRWA_STA_WALK_2F
  DATA_BlActAnmHeroCycle_WalkD4F,
  DATA_BlActAnmHeroCycle_WalkL4F,
  DATA_BlActAnmHeroCycle_WalkR4F,
#endif
  DATA_BlActAnmHeroCycle_WalkU6F,//DRWA_STA_WALK_6F
  DATA_BlActAnmHeroCycle_WalkD6F,
  DATA_BlActAnmHeroCycle_WalkL6F,
  DATA_BlActAnmHeroCycle_WalkR6F,
  DATA_BlActAnmHeroCycle_WalkU3F,//DRWA_STA_WALK_3F
  DATA_BlActAnmHeroCycle_WalkD3F,
  DATA_BlActAnmHeroCycle_WalkL3F,
  DATA_BlActAnmHeroCycle_WalkR3F,
  DATA_BlActAnmHeroCycle_WalkU7F,//DRWA_STA_WALK_7F
  DATA_BlActAnmHeroCycle_WalkD7F,
  DATA_BlActAnmHeroCycle_WalkL7F,
  DATA_BlActAnmHeroCycle_WalkR7F,
  DATA_BlActAnmHeroCycle_WalkU12F,//DRWA_STA_WALK_12F
  DATA_BlActAnmHeroCycle_WalkD12F,
  DATA_BlActAnmHeroCycle_WalkL12F,
  DATA_BlActAnmHeroCycle_WalkR12F,
};

//======================================================================
//  アニメーション1パターン
//======================================================================
static const GFL_BBDACT_ANM DATA_BlActOneCellAnm[] = {
  {0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM * const DATA_BlActOneCellAnmTbl[DRAW_STA_DIR4_MAX] =
{
  DATA_BlActOneCellAnm,//DRWA_STA_STOP
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,//DRWA_STA_WALK_32F
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,//DRWA_STA_WALK_16F
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,//DRWA_STA_WALK_8F
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,//DRWA_STA_WALK_4F
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,//DRWA_STA_WALK_2F
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,//DRWA_STA_WALK_6F
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,//DRWA_STA_WALK_3F
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,//DRWA_STA_WALK_7F
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,//DRWA_STA_WALK_12F
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
  DATA_BlActOneCellAnm,
};

//======================================================================
//  自機アイテムゲット
//======================================================================
enum
{
  TEXIDX_ITEMGET_0,
  TEXIDX_ITEMGET_1,
};

static const GFL_BBDACT_ANM DATA_BlActItemGet_Stop[] = {
  {TEXIDX_ITEMGET_0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActItemGet_Anm[] = {
  {TEXIDX_ITEMGET_0,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_ITEMGET_1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM * const DATA_BlActItemGet[DRAW_STA_ITEMGET_MAX] =
{
  DATA_BlActItemGet_Stop,
  DATA_BlActItemGet_Anm,
};

//======================================================================
//  自機ポケセン預け
//======================================================================
enum
{
  TEXIDX_PCAZUKE_0,
  TEXIDX_PCAZUKE_1,
  TEXIDX_PCAZUKE_2,
  TEXIDX_PCAZUKE_3,
  TEXIDX_PCAZUKE_4,
};

static const GFL_BBDACT_ANM DATA_BlActPCAzuke_Stop[] = {
  {TEXIDX_PCAZUKE_4,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActPCAzuke_Anm0[] = {
  {TEXIDX_PCAZUKE_0,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_1,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_0,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_1,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_2,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_PCAZUKE_3,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_4,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActPCAzuke_Anm1[] = {
  {TEXIDX_PCAZUKE_4,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_3,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_2,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_PCAZUKE_1,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_0,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_1,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_0,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_PCAZUKE_4,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM * const DATA_BlActPCAzuke[DRAW_STA_PCAZUKE_MAX] =
{
  DATA_BlActPCAzuke_Stop,
  DATA_BlActPCAzuke_Anm0,
  DATA_BlActPCAzuke_Anm1,
};

//======================================================================
//  自機レポート
//======================================================================
enum
{
  TEXIDX_SAVEHERO_0,
  TEXIDX_SAVEHERO_1,
};

static const GFL_BBDACT_ANM DATA_BlActSaveHero00[] = {
  {TEXIDX_SAVEHERO_0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_SAVEHERO_1,ANMFLIP_OFF,ANMFLIP_OFF,4},
//  {GFL_BBDACT_ANMCOM_JMP,0,0,0}, //091030ROM時点ではループ未対応
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM * const DATA_BlActSaveHero[DRAW_STA_SAVEHERO_MAX] =
{
  DATA_BlActSaveHero00,
};

//======================================================================
//  ビルボードアニメデータ　連れ歩きポケモン　反転使用
//======================================================================
enum
{
  TEXIDX_TPOKE_FLIP_U0,
  TEXIDX_TPOKE_FLIP_U1,
  TEXIDX_TPOKE_FLIP_D0,
  TEXIDX_TPOKE_FLIP_D1,
  TEXIDX_TPOKE_FLIP_L0,
  TEXIDX_TPOKE_FLIP_L1,
};

static const GFL_BBDACT_ANM DATA_BlActTPokeFlip_U[] = {
  {TEXIDX_TPOKE_FLIP_U0,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_TPOKE_FLIP_U1,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActTPokeFlip_D[] = {
  {TEXIDX_TPOKE_FLIP_D0,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_TPOKE_FLIP_D1,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_TPOKE_FLIP_D0,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActTPokeFlip_L[] = {
  {TEXIDX_TPOKE_FLIP_L0,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_TPOKE_FLIP_L1,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActTPokeFlip_R[] = {
  {TEXIDX_TPOKE_FLIP_L0,ANMFLIP_ON,ANMFLIP_OFF,10},
  {TEXIDX_TPOKE_FLIP_L1,ANMFLIP_ON,ANMFLIP_OFF,10},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM * DATA_BlActTPokeFlipTbl[4] = {
  DATA_BlActTPokeFlip_U,
  DATA_BlActTPokeFlip_D,
  DATA_BlActTPokeFlip_L,
  DATA_BlActTPokeFlip_R,
};

//======================================================================
//  ビルボードアニメデータ　連れ歩きポケモン　反転未使用
//======================================================================
enum
{
  TEXIDX_TPOKE_NFLIP_U0,
  TEXIDX_TPOKE_NFLIP_U1,
  TEXIDX_TPOKE_NFLIP_D0,
  TEXIDX_TPOKE_NFLIP_D1,
  TEXIDX_TPOKE_NFLIP_L0,
  TEXIDX_TPOKE_NFLIP_L1,
  TEXIDX_TPOKE_NFLIP_R0,
  TEXIDX_TPOKE_NFLIP_R1,
};

static const GFL_BBDACT_ANM DATA_BlActTPokeNonFlip_U[] = {
  {TEXIDX_TPOKE_NFLIP_U0,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_TPOKE_NFLIP_U1,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActTPokeNonFlip_D[] = {
  {TEXIDX_TPOKE_NFLIP_D0,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {TEXIDX_TPOKE_NFLIP_D1,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_TPOKE_NFLIP_D0,ANMFLIP_OFF,ANMFLIP_OFF,5},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActTPokeNonFlip_L[] = {
  {TEXIDX_TPOKE_NFLIP_L0,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_TPOKE_NFLIP_L1,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM DATA_BlActTPokeNonFlip_R[] = {
  {TEXIDX_TPOKE_NFLIP_R0,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_TPOKE_NFLIP_R1,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};
static const GFL_BBDACT_ANM * DATA_BlActTPokeNonFlipTbl[4] = {
  DATA_BlActTPokeNonFlip_U,  //DRAW_STA_STOP
  DATA_BlActTPokeNonFlip_D,
  DATA_BlActTPokeNonFlip_L,
  DATA_BlActTPokeNonFlip_R,
};

//======================================================================
//  ビルボードアニメデータ　釣り自機
//======================================================================
enum
{
  TEXIDX_FISHHERO_U0,
  TEXIDX_FISHHERO_U1,
  TEXIDX_FISHHERO_U2,
  TEXIDX_FISHHERO_U3,
  TEXIDX_FISHHERO_D0,
  TEXIDX_FISHHERO_D1,
  TEXIDX_FISHHERO_D2,
  TEXIDX_FISHHERO_D3,
  TEXIDX_FISHHERO_L0,
  TEXIDX_FISHHERO_L1,
  TEXIDX_FISHHERO_L2,
  TEXIDX_FISHHERO_L3,
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_StartU[] =
{
  {TEXIDX_FISHHERO_U0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_U1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_U3,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_StartD[] =
{
  {TEXIDX_FISHHERO_D0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_D1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_D3,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_StartL[] =
{
  {TEXIDX_FISHHERO_L0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L3,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_StartR[] =
{
  {TEXIDX_FISHHERO_L0,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L1,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L2,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L3,ANMFLIP_ON,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_EndU[] =
{
  {TEXIDX_FISHHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_U1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_U0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_EndD[] =
{
  {TEXIDX_FISHHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_D1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_D0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_EndL[] =
{
  {TEXIDX_FISHHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_EndR[] =
{
  {TEXIDX_FISHHERO_L2,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L1,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L0,ANMFLIP_ON,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_OnU[] =
{
  {TEXIDX_FISHHERO_U1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_OnD[] =
{
  {TEXIDX_FISHHERO_D1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_OnL[] =
{
  {TEXIDX_FISHHERO_L1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_OnR[] =
{
  {TEXIDX_FISHHERO_L1,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L2,ANMFLIP_ON,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_HitU[] =
{
  {TEXIDX_FISHHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_U1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_U0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_HitD[] =
{
  {TEXIDX_FISHHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_D1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_D0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_HitL[] =
{
  {TEXIDX_FISHHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActFishingHero_HitR[] =
{
  {TEXIDX_FISHHERO_L2,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L1,ANMFLIP_ON,ANMFLIP_OFF,4},
  {TEXIDX_FISHHERO_L0,ANMFLIP_ON,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM * DATA_BlActFishingHeroTbl[DRAW_STA_FISH_DIR4_MAX] =
{
  DATA_BlActFishingHero_StartU,
  DATA_BlActFishingHero_StartD,
  DATA_BlActFishingHero_StartL,
  DATA_BlActFishingHero_StartR,
  
  DATA_BlActFishingHero_EndU,
  DATA_BlActFishingHero_EndD,
  DATA_BlActFishingHero_EndL,
  DATA_BlActFishingHero_EndR,
  
  DATA_BlActFishingHero_OnU,
  DATA_BlActFishingHero_OnD,
  DATA_BlActFishingHero_OnL,
  DATA_BlActFishingHero_OnR,
  
  DATA_BlActFishingHero_HitU,
  DATA_BlActFishingHero_HitD,
  DATA_BlActFishingHero_HitL,
  DATA_BlActFishingHero_HitR,
};

//======================================================================
//  ビルボードアニメデータ　カットイン自機
//======================================================================
enum
{
  TEXIDX_CUTINHERO_0,
  TEXIDX_CUTINHERO_1,
  TEXIDX_CUTINHERO_2,
  TEXIDX_CUTINHERO_3,
};

static const GFL_BBDACT_ANM DATA_BlActCutInHero[] =
{
  {TEXIDX_CUTINHERO_0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_CUTINHERO_1,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_CUTINHERO_2,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_CUTINHERO_3,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM * DATA_BlActCutInHeroTbl[1] = {
  DATA_BlActCutInHero,
};

//======================================================================
//  ビルボードアニメデータ　ゆれ自機
//======================================================================
enum
{
  TEXIDX_YUREHERO_U0,
  TEXIDX_YUREHERO_U1,
  TEXIDX_YUREHERO_U2,
  TEXIDX_YUREHERO_U3,

  TEXIDX_YUREHERO_D0,
  TEXIDX_YUREHERO_D1,
  TEXIDX_YUREHERO_D2,
  TEXIDX_YUREHERO_D3,

  TEXIDX_YUREHERO_L0,
  TEXIDX_YUREHERO_L1,
  TEXIDX_YUREHERO_L2,
  TEXIDX_YUREHERO_L3,
  
  TEXIDX_YUREHERO_R0,
  TEXIDX_YUREHERO_R1,
  TEXIDX_YUREHERO_R2,
  TEXIDX_YUREHERO_R3,
};

#define YURE_FRAME_0 (4)
#define YURE_FRAME_1 (3)
#define YURE_FRAME_2 (2)

static const GFL_BBDACT_ANM DATA_BlActYureHeroU[] =
{
  {TEXIDX_YUREHERO_U0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_U1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_U0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_U3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0}, //18

  {TEXIDX_YUREHERO_U0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_U1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_U0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_U3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1}, //18+12

  {TEXIDX_YUREHERO_U0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_U1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_U0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_U3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_U2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2}, //30+6
  {GFL_BBDACT_ANMCOM_JMP,0,0,12},
};

static const GFL_BBDACT_ANM DATA_BlActYureHeroD[] =
{
  {TEXIDX_YUREHERO_D0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_D1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_D0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_D3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0}, //18

  {TEXIDX_YUREHERO_D0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_D1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_D0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_D3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1}, //18+12

  {TEXIDX_YUREHERO_D0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_D1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_D0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_D3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_D2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2}, //30+6
  {GFL_BBDACT_ANMCOM_JMP,0,0,12},
};

static const GFL_BBDACT_ANM DATA_BlActYureHeroL[] =
{
  {TEXIDX_YUREHERO_L0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_L1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_L0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_L3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0}, //18

  {TEXIDX_YUREHERO_L0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_L1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_L0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_L3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1}, //18+12

  {TEXIDX_YUREHERO_L0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_L1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_L0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_L3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_L2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2}, //30+6
  {GFL_BBDACT_ANMCOM_JMP,0,0,12},
};

static const GFL_BBDACT_ANM DATA_BlActYureHeroR[] =
{
  {TEXIDX_YUREHERO_R0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_R1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_R0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_R2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_R3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0},
  {TEXIDX_YUREHERO_R2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_0}, //18

  {TEXIDX_YUREHERO_R0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_R1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_R0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_R2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_R3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1},
  {TEXIDX_YUREHERO_R2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_1}, //18+12

  {TEXIDX_YUREHERO_R0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_R1,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_R0,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_R2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_R3,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2},
  {TEXIDX_YUREHERO_R2,ANMFLIP_OFF,ANMFLIP_OFF,YURE_FRAME_2}, //30+6
  {GFL_BBDACT_ANMCOM_JMP,0,0,12},
};

static const GFL_BBDACT_ANM * DATA_BlActYureHeroTbl[4] = {
  DATA_BlActYureHeroU,
  DATA_BlActYureHeroD,
  DATA_BlActYureHeroL,
  DATA_BlActYureHeroR,
};

//======================================================================
//  シン・ム
//======================================================================
enum
{
  TEXIDX_SHIN_MU_0,
  TEXIDX_SHIN_MU_1,
  TEXIDX_SHIN_MU_2,
  TEXIDX_SHIN_MU_3,
  TEXIDX_SHIN_MU_4,
  TEXIDX_SHIN_MU_5,
  TEXIDX_SHIN_MU_6,
  TEXIDX_SHIN_MU_7,
  TEXIDX_SHIN_MU_8,
  TEXIDX_SHIN_MU_9,
  TEXIDX_SHIN_MU_10,
  TEXIDX_SHIN_MU_11,
  TEXIDX_SHIN_MU_12,
  TEXIDX_SHIN_MU_13,
  TEXIDX_SHIN_MU_14,
  TEXIDX_SHIN_MU_15,
#if 0
  TEXIDX_SHIN_MU_16,
  TEXIDX_SHIN_MU_17,
  TEXIDX_SHIN_MU_18,
  TEXIDX_SHIN_MU_19,
  TEXIDX_SHIN_MU_20,
  TEXIDX_SHIN_MU_21,
  TEXIDX_SHIN_MU_22,
#endif
};

static const GFL_BBDACT_ANM DATA_BlActShinMu_StopU[] = {
  {TEXIDX_SHIN_MU_2,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_SHIN_MU_3,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActShinMu_StopD[] = {
  {TEXIDX_SHIN_MU_0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_SHIN_MU_1,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActShinMu_Hoeru[] = {
  {TEXIDX_SHIN_MU_4,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_SHIN_MU_5,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActShinMu_Fly[] = {
  {TEXIDX_SHIN_MU_10,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActShinMu_FlyUp[] = {
  {TEXIDX_SHIN_MU_6,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_SHIN_MU_7,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActShinMu_Gutari[] = {
  {TEXIDX_SHIN_MU_8,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_SHIN_MU_9,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {GFL_BBDACT_ANMCOM_JMP,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActShinMu_Turn[] = {
  {TEXIDX_SHIN_MU_11,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_SHIN_MU_12,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {TEXIDX_SHIN_MU_13,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM * DATA_BlActShinMuTbl[DRAW_STA_SHIN_MU_MAX] = {
  DATA_BlActShinMu_StopU, //u
  DATA_BlActShinMu_StopD, //d
  DATA_BlActShinMu_StopU, //l データあわせ
  DATA_BlActShinMu_StopD, //r データあわせ
  
  DATA_BlActShinMu_Hoeru,
  DATA_BlActShinMu_Fly,
  DATA_BlActShinMu_FlyUp,
  DATA_BlActShinMu_Gutari,
  DATA_BlActShinMu_Turn,
};

//======================================================================
//  くもの巣
//======================================================================
enum
{
  TEXIDX_SPIDER_0,
  TEXIDX_SPIDER_1,
  TEXIDX_SPIDER_2,
  TEXIDX_SPIDER_3,
};

static const GFL_BBDACT_ANM DATA_BlActSpider_Stop[] = {
  {TEXIDX_SPIDER_0,ANMFLIP_OFF,ANMFLIP_OFF,2},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActSpider_Remove[] = {
  {TEXIDX_SPIDER_0,ANMFLIP_OFF,ANMFLIP_OFF,4},
  {TEXIDX_SPIDER_1,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_SPIDER_2,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {TEXIDX_SPIDER_3,ANMFLIP_OFF,ANMFLIP_OFF,6},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM * DATA_BlActSpiderTbl[DRAW_STA_SPIDER_MAX] = {
  DATA_BlActSpider_Stop,
  DATA_BlActSpider_Remove,
};

//======================================================================
//  メロディア
//======================================================================
enum
{
  TEXIDX_MELODYER_0,
  TEXIDX_MELODYER_1,
  TEXIDX_MELODYER_2,
  TEXIDX_MELODYER_3,
  TEXIDX_MELODYER_4,
  TEXIDX_MELODYER_5,
  TEXIDX_MELODYER_6,
  TEXIDX_MELODYER_7,
  TEXIDX_MELODYER_8,
  TEXIDX_MELODYER_9,
  TEXIDX_MELODYER_10,
  TEXIDX_MELODYER_11,
  TEXIDX_MELODYER_12,
  TEXIDX_MELODYER_13,
  TEXIDX_MELODYER_14,
  TEXIDX_MELODYER_15,
  TEXIDX_MELODYER_16,
  TEXIDX_MELODYER_17,
  TEXIDX_MELODYER_18,
  TEXIDX_MELODYER_19,
};

static const GFL_BBDACT_ANM DATA_BlActMerodyer_Stop[] = {
  {TEXIDX_MELODYER_0,ANMFLIP_OFF,ANMFLIP_OFF,1},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActMerodyer_Spin[] = {
  {TEXIDX_MELODYER_0,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_1,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_2,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_3,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_4,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_5,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_6,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_7,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_8,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_9,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActMerodyer_SpinPose[] = {
  {TEXIDX_MELODYER_8,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_9,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_10,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_11,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_12,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_13,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_14,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {TEXIDX_MELODYER_15,ANMFLIP_OFF,ANMFLIP_OFF,10},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM DATA_BlActMerodyer_Shake[] = {
  {TEXIDX_MELODYER_16,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_MELODYER_17,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_MELODYER_18,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {TEXIDX_MELODYER_19,ANMFLIP_OFF,ANMFLIP_OFF,8},
  {GFL_BBDACT_ANMCOM_END,0,0,0},
};

static const GFL_BBDACT_ANM * DATA_BlActMerodyerTbl[DRAW_STA_MELODYER_ANMNO_MAX] = {
  DATA_BlActMerodyer_Stop,
  DATA_BlActMerodyer_Spin,
  DATA_BlActMerodyer_SpinPose,
  DATA_BlActMerodyer_Shake,
};

//======================================================================
//  ビルボードアクター　アニメーション　リストテーブル
//======================================================================
const MMDL_BBDACT_ANMTBL
  DATA_MMDL_BBDACT_ANM_ListTable[MMDL_BLACT_ANMTBLNO_MAX] =
{
  //MMDL_BLACT_ANMTBLNO_NON
  {NULL,0},
  //MMDL_BLACT_ANMTBLNO_HERO
  {DATA_BlActHeroTbl,DRAW_STA_HERO_DIR4_MAX},
  //MMDL_BLACT_ANMTBLNO_BLACT 廃止
  {NULL,0},
  //MMDL_BLACT_ANMTBLNO_CYCLEHERO_OLD 廃止
  {NULL,0},
  //MMDL_BLACT_ANMTBLNO_SWIMHERO
  {DATA_BlActSwimHeroTbl,DRAW_STA_SWIMHERO_MAX},
  //MMDL_BLACT_ANMTBLNO_FLIP
  {DATA_BlActAnmFlipTbl,DRAW_STA_DIR4_MAX},
  //MMDL_BLACT_ANMTBLNO_FLIP
  {DATA_BlActAnmNonFlipTbl,DRAW_STA_DIR4_MAX},
  //MMDL_BLACT_ANMTBLNO_CYCLEHERO
  {DATA_BlActAnmHeroCycleTbl,DRAW_STA_DIR4_MAX},
  //MMDL_BLACT_ANMTBLNO_ONECELL
  {DATA_BlActOneCellAnmTbl,DRAW_STA_DIR4_MAX},
  //MMDL_BLACT_ANMTBLNO_ITEMGET
  {DATA_BlActItemGet,DRAW_STA_ITEMGET_MAX},
  //MMDL_BLACT_ANMTBLNO_PCAZUKE
  {DATA_BlActPCAzuke,DRAW_STA_PCAZUKE_MAX},
  //MMDL_BLACT_ANMTBLNO_SAVE
  {DATA_BlActSaveHero,DRAW_STA_SAVEHERO_MAX},
  //MMDL_BLACT_ANMTBLNO_PCWOMAN
  {DATA_BlActAnmPcwomanTbl,DRAW_STA_PCWOMAN_DIR4_MAX},
  //MMDL_BLACT_ANMTBLNO_POKE_FLIP
  {DATA_BlActTPokeFlipTbl,4},
  //MMDL_BLACT_ANMTBLNO_POKE_NONFLIP
  {DATA_BlActTPokeNonFlipTbl,4},
  //MMDL_BLACT_ANMTBLNO_FISHINGHERO
  {DATA_BlActFishingHeroTbl,DRAW_STA_FISH_DIR4_MAX},
  //MMDL_BLACT_ANMTBLNO_CUTINHERO
  {DATA_BlActCutInHeroTbl,4},
  //MMDL_BLACT_ANMTBLNO_YUREHERO
  {DATA_BlActYureHeroTbl,4},
  //MMDL_BLACT_ANMTBLNO_SHIN_MU_A
  {DATA_BlActShinMuTbl,DRAW_STA_SHIN_MU_MAX},
  //MMDL_BLACT_ANMTBLNO_SPIDER
  {DATA_BlActSpiderTbl,DRAW_STA_SPIDER_MAX},
  //MMDL_BLACT_ANMTBLNO_NFLIP_ACT0
  {DATA_BlActAnmNonFlipAct0Tbl,DRAW_STA_ACT0_DIR4_MAX},
  //MMDL_BLACT_ANMTBLNO_MELODYER
  {DATA_BlActMerodyerTbl,DRAW_STA_MELODYER_ANMNO_MAX},
  //MMDL_BLACT_ANMTBLNO_SHIN_MU_B
  {DATA_BlActShinMuTbl,DRAW_STA_SHIN_MU_MAX},
};

//======================================================================
//  ビルボードアクター　モデルサイズ [size][x,y]
//======================================================================
const u16 DATA_MMDL_BLACT_MdlSize[MMDL_BLACT_MDLSIZE_MAX][2] =
{
  {32,32}, //MMDL_BLACT_MDLSIZE_32x32
  {16,16}, //MMDL_BLACT_MDLSIZE_16x16
  {64,64}, //MMDL_BLACT_MDLSIZE_64x64
};
