//bsubway_scr_def.h
//このファイルはコンバータによって作成されました

#ifndef _BSUBWAY_SCR_DEF_H_
#define _BSUBWAY_SCR_DEF_H_

//スクリプトデータID定義
#define SCRID_INIT_BSW_RECEIPT (10330)
#define SCRID_RECOVER_BSW_RECEIPT (10331)
#define SCRID_BSW_POSEV_RECEIPT_STOPPER (10332)
#define SCRID_BSW_RECEIPT_TALK (10333)
#define SCRID_BSW_GAME_CONTINUE (10334)
#define SCRID_BSW_REPORT_ERROR (10335)
#define SCRID_BSW_GAME_CANCEL (10336)
#define SCRID_BSW_GAME_AFTER (10337)
#define SCRID_BSW_RETMAP_RECEIPT (10338)
#define SCRID_INIT_BSW_TTOWN (10339)
#define SCRID_BSW_TTOWN_RECEIPT_TALK (10340)
#define SCRID_BSW_DEBUG_MAP_CHG_TRAIN (10341)

#endif //_BSUBWAY_SCR_DEF_H_