//bsubway_scr_def.h
//このファイルはコンバータによって作成されました

#ifndef _BSUBWAY_SCR_DEF_H_
#define _BSUBWAY_SCR_DEF_H_

//スクリプトデータID定義
#define SCRID_INIT_BSW_RECEIPT (10330)
#define SCRID_RECOVER_BSW_RECEIPT (10331)
#define SCRID_BSW_POSEV_RECEIPT_STOPPER (10332)
#define SCRID_BSW_RECEIPT_TALK (10333)
#define SCRID_BSW_GAME_CONTINUE (10334)
#define SCRID_BSW_REPORT_ERROR (10335)
#define SCRID_BSW_GAME_AFTER (10336)
#define SCRID_BSW_GAME_AFTER_LOSE (10337)
#define SCRID_BSW_RETMAP_RECEIPT (10338)
#define SCRID_INIT_BSW_TTOWN (10339)
#define SCRID_BSW_TTOWN_RECEIPT_TALK (10340)
#define SCRID_BSW_TTOWN_RECEIPT_STOPPER (10341)
#define SCRID_BSW_TTOWN_DEMO_TRAIN_ARRIVAL (10342)
#define SCRID_BSW_DEBUG_MAP_CHG_TRAIN (10343)
#define SCRID_BSW_UPLOAD_WIFI_SCORE (10344)
#define SCRID_BSW_SELECT_BTL_BOX (10345)
#define SCRID_BSW_SELECT_POKEMON (10346)
#define SCRID_BSW_SELECT_AI_MULTI_POKEMON (10347)
#define SCRID_BSW_COMM_MULTI_ERROR_MSG_SAMEPOKE (10348)

#endif //_BSUBWAY_SCR_DEF_H_