#ifndef _C02_DEF_H_
#define _C02_DEF_H_

//スクリプトデータID定義 
#define	SCRID_C02_TALKOBJ_WOMAN2		(1)
#define	SCRID_C02_TALKOBJ_MAN2		(2)
#define	SCRID_C02_TALKOBJ_MIDDLEWOMAN2		(3)
#define	SCRID_C02_TALKOBJ_BACKPACKER		(4)
#define	SCRID_C02_TALKOBJ_ACCORDION		(5)
#define	SCRID_C02_TALKOBJ_SIGN1		(6)
#define	SCRID_C02_DATA_MAX		(6)		//最大数

#endif //_C02_DEF_H_
