//c05_def.h
//このファイルはコンバータによって作成されました

#ifndef _C05_DEF_H_
#define _C05_DEF_H_

//スクリプトデータID定義
#define SCRID_C05_TALKOBJ_WOMAN2 (1)
#define SCRID_C05_TALKOBJ_BABYGIRL1 (2)
#define SCRID_C05_TALKOBJ_BACKPACKERW (3)
#define SCRID_C05_TALKOBJ_TRAINERM (4)
#define SCRID_C05_TALKOBJ_DRIVER (5)
#define SCRID_C05_TALKOBJ_BADMAN (6)
#define SCRID_C05_TALKOBJ_WORKMAN (7)
#define SCRID_POS_C05_GYMLEADER_01 (8)
#define SCRID_POS_C05_GYMLEADER_02 (9)
#define SCRID_C05_BUSINESSMAN_01 (10)
#define SCRID_BG_C05_BOARD_01 (11)
#define SCRID_BG_C05_BOARD_02 (12)

#endif //_C05_DEF_H_