//common_scr_def.h
//このファイルはコンバータによって作成されました

#ifndef _COMMON_SCR_DEF_H_
#define _COMMON_SCR_DEF_H_

//スクリプトデータID定義
#define SCRID_DUMMY (2000)
#define SCRID_HEAL_P01_DUMMY (2001)
#define SCRID_SHOP_START_TALK (2002)
#define SCRID_ITEM_EVENT_SUCCESS (2003)
#define SCRID_ITEM_EVENT_FAIL (2004)
#define SCRID_EASY_ITEM_EVENT (2005)
#define SCRID_ITEM_EVENT_KEYWAIT (2006)
#define SCRID_ITEM_EVENT_NOWAIT (2007)
#define SCRID_GAMEOVER_RECOVER_HOME (2008)
#define SCRID_GAMEOVER_RECOVER_POKECEN (2009)
#define SCRID_REPORT_EVENT_CALL (2010)
#define SCRID_POCKET_ME_SET (2011)
#define SCRID_FIELD_COMM_EXIT_EVENT_CALL (2012)

#endif //_COMMON_SCR_DEF_H_