//field_ev_scr_def.h
//このファイルはコンバータによって作成されました

#ifndef _FIELD_EV_SCR_DEF_H_
#define _FIELD_EV_SCR_DEF_H_

//スクリプトデータID定義
#define SCRID_FLD_EV_SPRAY_EFFECT_END (10130)
#define SCRID_FLD_EV_AMAIKAORI_ENC_FAILED (10131)
#define SCRID_FLD_EV_AMAIKAORI_WEATHER_ERROR (10132)
#define SCRID_FLD_EV_EFFECT_ENC_ITEM_GET (10133)
#define SCRID_FLD_EV_FISHING_SUCCESS (10134)
#define SCRID_FLD_EV_FISHING_FAILED_ENCOUNT (10135)
#define SCRID_FLD_EV_FISHING_FAILED_TOO_EARLY (10136)
#define SCRID_FLD_EV_FISHING_FAILED_TOO_SLOW (10137)
#define SCRID_FLD_EV_WARP_SUCCESS (10138)
#define SCRID_FLD_EV_WARP_SUCCESS_PARTNER (10139)
#define SCRID_FLD_EV_WARP_FAILED (10140)
#define SCRID_FLD_EV_WARP_FAILED_MISSION_TARGET (10141)
#define SCRID_FLD_EV_WARP_FAILED_CONNECTING (10142)
#define SCRID_FLD_EV_WARP_FAILED_SHUTDOWN (10143)

#endif //_FIELD_EV_SCR_DEF_H_