//item_get_scr_def.h
//このファイルはコンバータによって作成されました

#ifndef _ITEM_GET_SCR_DEF_H_
#define _ITEM_GET_SCR_DEF_H_

//スクリプトデータID定義
#define SCRID_EASY_ITEM_EVENT (2800)
#define SCRID_ITEM_EVENT_SUCCESS_KEYWAIT (2801)
#define SCRID_ITEM_EVENT_SUCCESS_NOWAIT (2802)
#define SCRID_ITEM_EVENT_FAIL_KEYWAIT (2803)
#define SCRID_ITEM_EVENT_FAIL_NOWAIT (2804)
#define SCRID_ITEM_EVENT_KEYWAIT (2805)
#define SCRID_ITEM_EVENT_NOWAIT (2806)
#define SCRID_ITEM_EVENT_FIELD (2807)
#define SCRID_POCKET_ME_SET (2808)
#define SCRID_ITEM_GET_PLAYER_FORM_SET (2809)
#define SCRID_ITEM_GET_PLAYER_FORM_RETURN (2810)
#define SCRID_ITEM_EVENT_HIDEITEM (2811)

#endif //_ITEM_GET_SCR_DEF_H_