#----------------------------------------------------------------------------
#
#		script コンバート
#
#----------------------------------------------------------------------------

.PHONY:	do-build	clean


do-build:
		make -f makefile_h do-build
		make -f makefile_ev do-build

clean:
		make -f makefile_h clean
		make -f makefile_ev clean

