//symbol_encount_scr_def.h
//このファイルはコンバータによって作成されました

#ifndef _SYMBOL_ENCOUNT_SCR_DEF_H_
#define _SYMBOL_ENCOUNT_SCR_DEF_H_

//スクリプトデータID定義
#define SCRID_SYMBOL_POKEMON (10480)
#define SCRID_ZONE_SYMBOL_ENCOUNT (10481)
#define SCRID_INIT_SYMBOL_ENCOUNT (10482)
#define SCRID_RECOVER_SYMBOL_ENCOUNT (10483)
#define SCRID_POS_SYMBOLMAP_ENTRANCE_UP (10484)
#define SCRID_POS_SYMBOLMAP_ENTRANCE_DOWN (10485)
#define SCRID_POS_SYMBOLMAP_ENTRANCE_LEFT (10486)
#define SCRID_POS_SYMBOLMAP_ENTRANCE_RIGHT (10487)

#endif //_SYMBOL_ENCOUNT_SCR_DEF_H_