#ifndef _TRAINER_DEF_H_
#define _TRAINER_DEF_H_

//スクリプトデータID定義 
#define	SCRID_TANPAN_01		(3000)
#define	SCRID_TANPAN_01_2	(5000)
#define	SCRID_TRAINER_TALK_BATTLE		(3001)
#define	SCRID_TRAINER_TALK_BATTLE_2	(5001)
#define	SCRID_TRAINER_MOVE_BATTLE		(3002)
#define	SCRID_TRAINER_MOVE_BATTLE_2	(5002)
#define	SCRID_TRAINER_DATA_MAX		(3)		//最大数

#endif //_TRAINER_DEF_H_
