//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 11/14/09.
//-----------------------------------------------------
#define    NANR_c_gear2_obj_CellAnime_ampm    0 // 
#define    NANR_c_gear2_obj_CellAnime_NO2    1 // ２
#define    NANR_c_gear2_obj_CellAnime_NO10a    2 // 10
#define    NANR_c_gear2_obj_CellAnime_colon    3 // 
#define    NANR_c_gear2_obj_CellAnime_NO6    4 // ６
#define    NANR_c_gear2_obj_CellAnime_NO10b    5 // 
#define    NANR_c_gear2_obj_CellAnime_batt1    6 // 
#define    NANR_c_gear2_obj_CellAnime_batt2    7 // 
#define    NANR_c_gear2_obj_CellAnime_IR    8 // 
#define    NANR_c_gear2_obj_CellAnime_WIRELESS    9 // 
#define    NANR_c_gear2_obj_CellAnime_WIFI    10 // 
#define    NANR_c_gear2_obj_CellAnime01    11 // ボタンむらさき
#define    NANR_c_gear2_obj_CellAnime02    12 // ボタン黄色
#define    NANR_c_gear2_obj_CellAnime03    13 // ボタンオレンジ
#define    NANR_c_gear2_obj_CellAnime0    14 // 
#define    NANR_c_gear2_obj_CellAnime1    15 // 
#define    NANR_c_gear2_obj_CellAnime_SURECHIGAI    16 // 
#define    NANR_c_gear2_obj_CellAnime_sure01    17 // 
#define    NANR_c_gear2_obj_CellAnime_sure02    18 // 
#define    NANR_c_gear2_obj_CellAnime_sure03    19 // 
#define    NANR_c_gear2_obj_CellAnime_sure04    20 // 
#define    NANR_c_gear2_obj_CellAnime_sure05    21 // 
#define    NANR_c_gear2_obj_CellAnime_sure06    22 // 
#define    NANR_c_gear2_obj_CellAnime_sure07    23 // 
#define    NANR_c_gear2_obj_CellAnime_sure08    24 // 
#define    NANR_c_gear2_obj_CellAnime_sure09    25 // 
#define    NANR_c_gear2_obj_CellAnime_sure10    26 // 
#define    NANR_c_gear2_obj_CellAnime_sure11    27 // 
#define    NANR_c_gear2_obj_CellAnime_sure12    28 // 
#define    NANR_c_gear2_obj_CellAnime_sure13    29 // 
#define    NANR_c_gear2_obj_CellAnime_sure14    30 // 
#define    NANR_c_gear2_obj_CellAnime_sure15    31 // 
#define    NANR_c_gear2_obj_CellAnime_sure16    32 // 
#define    NANR_c_gear2_obj_CellAnime011    33 // ボタンむらさき
#define    NANR_c_gear2_obj_CellAnime021    34 // ボタン黄色
#define    NANR_c_gear2_obj_CellAnime031    35 // ボタンオレンジ
