//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 04/07/10.
//-----------------------------------------------------
#define    NANR_c_gear_obj_CellAnime_ampm    0 // 
#define    NANR_c_gear_obj_CellAnime_NO2    1 // ２
#define    NANR_c_gear_obj_CellAnime_NO10a    2 // 10
#define    NANR_c_gear_obj_CellAnime_colon    3 // 
#define    NANR_c_gear_obj_CellAnime_NO6    4 // ６
#define    NANR_c_gear_obj_CellAnime_NO10b    5 // 
#define    NANR_c_gear_obj_CellAnime_batt1    6 // 
#define    NANR_c_gear_obj_CellAnime_batt2    7 // 
#define    NANR_c_gear_obj_CellAnime_IR    8 // 
#define    NANR_c_gear_obj_CellAnime_WIRELESS    9 // 
#define    NANR_c_gear_obj_CellAnime_WIFI    10 // 
#define    NANR_c_gear_obj_CellAnime01    11 // ボタンむらさき
#define    NANR_c_gear_obj_CellAnime02    12 // ボタン黄色
#define    NANR_c_gear_obj_CellAnime03    13 // ボタンオレンジ
#define    NANR_c_gear_obj_CellAnime_cus_on    14 // 
#define    NANR_c_gear_obj_CellAnime_SURECHIGAI    15 // 
#define    NANR_c_gear_obj_CellAnime_sure01    16 // 
#define    NANR_c_gear_obj_CellAnime_radar    17 // 
#define    NANR_c_gear_obj_CellAnime_loro_all    18 // 
#define    NANR_c_gear_obj_CellAnime_logo1    19 // 
#define    NANR_c_gear_obj_CellAnime_logo2    20 // 
#define    NANR_c_gear_obj_CellAnime_logo3    21 // 
#define    NANR_c_gear_obj_CellAnime_logo4    22 // 
#define    NANR_c_gear_obj_CellAnime_logo_g    23 // 
#define    NANR_c_gear_obj_CellAnime_logo_e    24 // 
#define    NANR_c_gear_obj_CellAnime_logo_a    25 // 
#define    NANR_c_gear_obj_CellAnime_logo_r    26 // 
#define    NANR_c_gear_obj_CellAnime_logo_g2    27 // 
#define    NANR_c_gear_obj_CellAnime_logo_e2    28 // 
#define    NANR_c_gear_obj_CellAnime_logo_a2    29 // 
#define    NANR_c_gear_obj_CellAnime_logo_r2    30 // 
#define    NANR_c_gear_obj_CellAnime_logo_mini1    31 // 
#define    NANR_c_gear_obj_CellAnime_logo_mini2    32 // 
#define    NANR_c_gear_obj_CellAnime_logo_mini3    33 // 
#define    NANR_c_gear_obj_CellAnime_logo_mini4    34 // 
#define    NANR_c_gear_obj_CellAnime_logo_mini5    35 // 
#define    NANR_c_gear_obj_CellAnime_logo_mini6    36 // 
#define    NANR_c_gear_obj_CellAnime_logo_mini7    37 // 
#define    NANR_c_gear_obj_CellAnime_help    38 // 
#define    NANR_c_gear_obj_CellAnime_surechigai    39 // 
#define    NANR_c_gear_obj_CellAnime_on_off    40 // 
#define    NANR_c_gear_obj_CellAnime_surechigai_waku    41 // 
