//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 02/06/10.
//-----------------------------------------------------
#define    NANR_c_gear_obj_CellAnime_ampm    0 // 
#define    NANR_c_gear_obj_CellAnime_NO2    1 // ２
#define    NANR_c_gear_obj_CellAnime_NO10a    2 // 10
#define    NANR_c_gear_obj_CellAnime_colon    3 // 
#define    NANR_c_gear_obj_CellAnime_NO6    4 // ６
#define    NANR_c_gear_obj_CellAnime_NO10b    5 // 
#define    NANR_c_gear_obj_CellAnime_batt1    6 // 
#define    NANR_c_gear_obj_CellAnime_batt2    7 // 
#define    NANR_c_gear_obj_CellAnime_IR    8 // 
#define    NANR_c_gear_obj_CellAnime_WIRELESS    9 // 
#define    NANR_c_gear_obj_CellAnime_WIFI    10 // 
#define    NANR_c_gear_obj_CellAnime01    11 // ボタンむらさき
#define    NANR_c_gear_obj_CellAnime02    12 // ボタン黄色
#define    NANR_c_gear_obj_CellAnime03    13 // ボタンオレンジ
#define    NANR_c_gear_obj_CellAnime0    14 // 
#define    NANR_c_gear_obj_CellAnime1    15 // 
#define    NANR_c_gear_obj_CellAnime_SURECHIGAI    16 // 
#define    NANR_c_gear_obj_CellAnime_sure01    17 // 
#define    NANR_c_gear_obj_CellAnime_radar    18 // 
