//============================================================================================
/**
 * @file	wazano_def.h
 * @bfief	技NoのDefine定義ファイル
 * @author	WazaTableConverter
 * 技テーブルコンバータから生成されました
*/
//============================================================================================

#pragma once

#define		WAZANO_NULL						( 0 )
#define		WAZANO_HATAKU					( 1 )		//はたく
#define		WAZANO_KARATETYOPPU		( 2 )		//からてチョップ
#define		WAZANO_OUHUKUBINTA		( 3 )		//おうふくビンタ
#define		WAZANO_RENZOKUPANTI		( 4 )		//れんぞくパンチ
#define		WAZANO_MEGATONPANTI		( 5 )		//メガトンパンチ
#define		WAZANO_NEKONIKOBAN		( 6 )		//ネコにこばん
#define		WAZANO_HONOONOPANTI		( 7 )		//ほのおのパンチ
#define		WAZANO_REITOUPANTI		( 8 )		//れいとうパンチ
#define		WAZANO_KAMINARIPANTI	( 9 )		//かみなりパンチ
#define		WAZANO_HIKKAKU				( 10 )		//ひっかく
#define		WAZANO_HASAMU					( 11 )		//はさむ
#define		WAZANO_HASAMIGIROTIN	( 12 )		//ハサミギロチン
#define		WAZANO_KAMAITATI			( 13 )		//かまいたち
#define		WAZANO_TURUGINOMAI		( 14 )		//つるぎのまい
#define		WAZANO_IAIGIRI				( 15 )		//いあいぎり
#define		WAZANO_KAZEOKOSI			( 16 )		//かぜおこし
#define		WAZANO_TUBASADEUTU		( 17 )		//つばさでうつ
#define		WAZANO_HUKITOBASI			( 18 )		//ふきとばし
#define		WAZANO_SORAWOTOBU			( 19 )		//そらをとぶ
#define		WAZANO_SIMETUKERU			( 20 )		//しめつける
#define		WAZANO_TATAKITUKERU		( 21 )		//たたきつける
#define		WAZANO_TURUNOMUTI			( 22 )		//つるのムチ
#define		WAZANO_HUMITUKE				( 23 )		//ふみつけ
#define		WAZANO_NIDOGERI				( 24 )		//にどげり
#define		WAZANO_MEGATONKIKKU		( 25 )		//メガトンキック
#define		WAZANO_TOBIGERI				( 26 )		//とびげり
#define		WAZANO_MAWASIGERI			( 27 )		//まわしげり
#define		WAZANO_SUNAKAKE				( 28 )		//すなかけ
#define		WAZANO_ZUTUKI					( 29 )		//ずつき
#define		WAZANO_TUNODETUKU			( 30 )		//つのでつく
#define		WAZANO_MIDAREDUKI			( 31 )		//みだれづき
#define		WAZANO_TUNODORIRU			( 32 )		//つのドリル
#define		WAZANO_TAIATARI				( 33 )		//たいあたり
#define		WAZANO_NOSIKAKARI			( 34 )		//のしかかり
#define		WAZANO_MAKITUKU				( 35 )		//まきつく
#define		WAZANO_TOSSIN					( 36 )		//とっしん
#define		WAZANO_ABARERU				( 37 )		//あばれる
#define		WAZANO_SUTEMITAKKURU	( 38 )		//すてみタックル
#define		WAZANO_SIPPOWOHURU		( 39 )		//しっぽをふる
#define		WAZANO_DOKUBARI				( 40 )		//どくばり
#define		WAZANO_DABURUNIIDORU	( 41 )		//ダブルニードル
#define		WAZANO_MISAIRUBARI		( 42 )		//ミサイルばり
#define		WAZANO_NIRAMITUKERU		( 43 )		//にらみつける
#define		WAZANO_KAMITUKU				( 44 )		//かみつく
#define		WAZANO_NAKIGOE				( 45 )		//なきごえ
#define		WAZANO_HOERU					( 46 )		//ほえる
#define		WAZANO_UTAU						( 47 )		//うたう
#define		WAZANO_TYOUONPA				( 48 )		//ちょうおんぱ
#define		WAZANO_SONIKKUBUUMU		( 49 )		//ソニックブーム
#define		WAZANO_KANASIBARI			( 50 )		//かなしばり
#define		WAZANO_YOUKAIEKI			( 51 )		//ようかいえき
#define		WAZANO_HINOKO					( 52 )		//ひのこ
#define		WAZANO_KAENHOUSYA			( 53 )		//かえんほうしゃ
#define		WAZANO_SIROIKIRI			( 54 )		//しろいきり
#define		WAZANO_MIZUDEPPOU			( 55 )		//みずでっぽう
#define		WAZANO_HAIDOROPONPU		( 56 )		//ハイドロポンプ
#define		WAZANO_NAMINORI				( 57 )		//なみのり
#define		WAZANO_REITOUBIIMU		( 58 )		//れいとうビーム
#define		WAZANO_HUBUKI					( 59 )		//ふぶき
#define		WAZANO_SAIKEKOUSEN		( 60 )		//サイケこうせん
#define		WAZANO_BABURUKOUSEN		( 61 )		//バブルこうせん
#define		WAZANO_OORORABIIMU		( 62 )		//オーロラビーム
#define		WAZANO_HAKAIKOUSEN		( 63 )		//はかいこうせん
#define		WAZANO_TUTUKU					( 64 )		//つつく
#define		WAZANO_DORIRUKUTIBASI	( 65 )		//ドリルくちばし
#define		WAZANO_ZIGOKUGURUMA		( 66 )		//じごくぐるま
#define		WAZANO_KETAGURI				( 67 )		//けたぐり
#define		WAZANO_KAUNTAA				( 68 )		//カウンター
#define		WAZANO_TIKYUUNAGE			( 69 )		//ちきゅうなげ
#define		WAZANO_KAIRIKI				( 70 )		//かいりき
#define		WAZANO_SUITORU				( 71 )		//すいとる
#define		WAZANO_MEGADOREIN			( 72 )		//メガドレイン
#define		WAZANO_YADORIGINOTANE	( 73 )		//やどりぎのタネ
#define		WAZANO_SEITYOU				( 74 )		//せいちょう
#define		WAZANO_HAPPAKATTAA		( 75 )		//はっぱカッター
#define		WAZANO_SOORAABIIMU		( 76 )		//ソーラービーム
#define		WAZANO_DOKUNOKONA			( 77 )		//どくのこな
#define		WAZANO_SIBIREGONA			( 78 )		//しびれごな
#define		WAZANO_NEMURIGONA			( 79 )		//ねむりごな
#define		WAZANO_HANABIRANOMAI	( 80 )		//はなびらのまい
#define		WAZANO_ITOWOHAKU			( 81 )		//いとをはく
#define		WAZANO_RYUUNOIKARI		( 82 )		//りゅうのいかり
#define		WAZANO_HONOONOUZU			( 83 )		//ほのおのうず
#define		WAZANO_DENKISYOKKU		( 84 )		//でんきショック
#define		WAZANO_10MANBORUTO		( 85 )		//１０まんボルト
#define		WAZANO_DENZIHA				( 86 )		//でんじは
#define		WAZANO_KAMINARI				( 87 )		//かみなり
#define		WAZANO_IWAOTOSI				( 88 )		//いわおとし
#define		WAZANO_ZISIN					( 89 )		//じしん
#define		WAZANO_ZIWARE					( 90 )		//じわれ
#define		WAZANO_ANAWOHORU			( 91 )		//あなをほる
#define		WAZANO_DOKUDOKU				( 92 )		//どくどく
#define		WAZANO_NENRIKI				( 93 )		//ねんりき
#define		WAZANO_SAIKOKINESISU	( 94 )		//サイコキネシス
#define		WAZANO_SAIMINZYUTU		( 95 )		//さいみんじゅつ
#define		WAZANO_YOGANOPOOZU		( 96 )		//ヨガのポーズ
#define		WAZANO_KOUSOKUIDOU		( 97 )		//こうそくいどう
#define		WAZANO_DENKOUSEKKA		( 98 )		//でんこうせっか
#define		WAZANO_IKARI					( 99 )		//いかり
#define		WAZANO_TEREPOOTO			( 100 )		//テレポート
#define		WAZANO_NAITOHEDDO			( 101 )		//ナイトヘッド
#define		WAZANO_MONOMANE				( 102 )		//ものまね
#define		WAZANO_IYANAOTO				( 103 )		//いやなおと
#define		WAZANO_KAGEBUNSIN			( 104 )		//かげぶんしん
#define		WAZANO_ZIKOSAISEI			( 105 )		//じこさいせい
#define		WAZANO_KATAKUNARU			( 106 )		//かたくなる
#define		WAZANO_TIISAKUNARU		( 107 )		//ちいさくなる
#define		WAZANO_ENMAKU					( 108 )		//えんまく
#define		WAZANO_AYASIIHIKARI		( 109 )		//あやしいひかり
#define		WAZANO_KARANIKOMORU		( 110 )		//からにこもる
#define		WAZANO_MARUKUNARU			( 111 )		//まるくなる
#define		WAZANO_BARIAA					( 112 )		//バリアー
#define		WAZANO_HIKARINOKABE		( 113 )		//ひかりのかべ
#define		WAZANO_KUROIKIRI			( 114 )		//くろいきり
#define		WAZANO_RIHUREKUTAA		( 115 )		//リフレクター
#define		WAZANO_KIAIDAME				( 116 )		//きあいだめ
#define		WAZANO_GAMAN					( 117 )		//がまん
#define		WAZANO_YUBIWOHURU			( 118 )		//ゆびをふる
#define		WAZANO_OUMUGAESI			( 119 )		//オウムがえし
#define		WAZANO_ZIBAKU					( 120 )		//じばく
#define		WAZANO_TAMAGOBAKUDAN	( 121 )		//タマゴばくだん
#define		WAZANO_SITADENAMERU		( 122 )		//したでなめる
#define		WAZANO_SUMOGGU				( 123 )		//スモッグ
#define		WAZANO_HEDOROKOUGEKI	( 124 )		//ヘドロこうげき
#define		WAZANO_HONEKONBOU			( 125 )		//ホネこんぼう
#define		WAZANO_DAIMONZI				( 126 )		//だいもんじ
#define		WAZANO_TAKINOBORI			( 127 )		//たきのぼり
#define		WAZANO_KARADEHASAMU		( 128 )		//からではさむ
#define		WAZANO_SUPIIDOSUTAA		( 129 )		//スピードスター
#define		WAZANO_ROKETTOZUTUKI	( 130 )		//ロケットずつき
#define		WAZANO_TOGEKYANON			( 131 )		//とげキャノン
#define		WAZANO_KARAMITUKU			( 132 )		//からみつく
#define		WAZANO_DOWASURE				( 133 )		//ドわすれ
#define		WAZANO_SUPUUNMAGE			( 134 )		//スプーンまげ
#define		WAZANO_TAMAGOUMI			( 135 )		//タマゴうみ
#define		WAZANO_TOBIHIZAGERI		( 136 )		//とびひざげり
#define		WAZANO_HEBINIRAMI			( 137 )		//へびにらみ
#define		WAZANO_YUMEKUI				( 138 )		//ゆめくい
#define		WAZANO_DOKUGASU				( 139 )		//どくガス
#define		WAZANO_TAMANAGE				( 140 )		//たまなげ
#define		WAZANO_KYUUKETU				( 141 )		//きゅうけつ
#define		WAZANO_AKUMANOKISSU		( 142 )		//あくまのキッス
#define		WAZANO_GODDOBAADO			( 143 )		//ゴッドバード
#define		WAZANO_HENSIN					( 144 )		//へんしん
#define		WAZANO_AWA						( 145 )		//あわ
#define		WAZANO_PIYOPIYOPANTI	( 146 )		//ピヨピヨパンチ
#define		WAZANO_KINOKONOHOUSI	( 147 )		//キノコのほうし
#define		WAZANO_HURASSYU				( 148 )		//フラッシュ
#define		WAZANO_SAIKOWHEEBU		( 149 )		//サイコウェーブ
#define		WAZANO_HANERU					( 150 )		//はねる
#define		WAZANO_TOKERU					( 151 )		//とける
#define		WAZANO_KURABUHANMAA		( 152 )		//クラブハンマー
#define		WAZANO_DAIBAKUHATU		( 153 )		//だいばくはつ
#define		WAZANO_MIDAREHIKKAKI	( 154 )		//みだれひっかき
#define		WAZANO_HONEBUUMERAN		( 155 )		//ホネブーメラン
#define		WAZANO_NEMURU					( 156 )		//ねむる
#define		WAZANO_IWANADARE			( 157 )		//いわなだれ
#define		WAZANO_HISSATUMAEBA		( 158 )		//ひっさつまえば
#define		WAZANO_KAKUBARU				( 159 )		//かくばる
#define		WAZANO_TEKUSUTYAA			( 160 )		//テクスチャー
#define		WAZANO_TORAIATAKKU		( 161 )		//トライアタック
#define		WAZANO_IKARINOMAEBA		( 162 )		//いかりのまえば
#define		WAZANO_KIRISAKU				( 163 )		//きりさく
#define		WAZANO_MIGAWARI				( 164 )		//みがわり
#define		WAZANO_WARUAGAKI			( 165 )		//わるあがき
#define		WAZANO_SUKETTI				( 166 )		//スケッチ
#define		WAZANO_TORIPURUKIKKU	( 167 )		//トリプルキック
#define		WAZANO_DOROBOU				( 168 )		//どろぼう
#define		WAZANO_KUMONOSU				( 169 )		//クモのす
#define		WAZANO_KOKORONOME			( 170 )		//こころのめ
#define		WAZANO_AKUMU					( 171 )		//あくむ
#define		WAZANO_KAENGURUMA			( 172 )		//かえんぐるま
#define		WAZANO_IBIKI					( 173 )		//いびき
#define		WAZANO_NOROI					( 174 )		//のろい
#define		WAZANO_ZITABATA				( 175 )		//じたばた
#define		WAZANO_TEKUSUTYAA2		( 176 )		//テクスチャー２
#define		WAZANO_EAROBURASUTO		( 177 )		//エアロブラスト
#define		WAZANO_WATAHOUSI			( 178 )		//わたほうし
#define		WAZANO_KISIKAISEI			( 179 )		//きしかいせい
#define		WAZANO_URAMI					( 180 )		//うらみ
#define		WAZANO_KONAYUKI				( 181 )		//こなゆき
#define		WAZANO_MAMORU					( 182 )		//まもる
#define		WAZANO_MAHHAPANTI			( 183 )		//マッハパンチ
#define		WAZANO_KOWAIKAO				( 184 )		//こわいかお
#define		WAZANO_DAMASIUTI			( 185 )		//だましうち
#define		WAZANO_TENSINOKISSU		( 186 )		//てんしのキッス
#define		WAZANO_HARADAIKO			( 187 )		//はらだいこ
#define		WAZANO_HEDOROBAKUDAN	( 188 )		//ヘドロばくだん
#define		WAZANO_DOROKAKE				( 189 )		//どろかけ
#define		WAZANO_OKUTANHOU			( 190 )		//オクタンほう
#define		WAZANO_MAKIBISI				( 191 )		//まきびし
#define		WAZANO_DENZIHOU				( 192 )		//でんじほう
#define		WAZANO_MIYABURU				( 193 )		//みやぶる
#define		WAZANO_MITIDURE				( 194 )		//みちづれ
#define		WAZANO_HOROBINOUTA		( 195 )		//ほろびのうた
#define		WAZANO_KOGOERUKAZE		( 196 )		//こごえるかぜ
#define		WAZANO_MIKIRI					( 197 )		//みきり
#define		WAZANO_BOONRASSYU			( 198 )		//ボーンラッシュ
#define		WAZANO_ROKKUON				( 199 )		//ロックオン
#define		WAZANO_GEKIRIN				( 200 )		//げきりん
#define		WAZANO_SUNAARASI			( 201 )		//すなあらし
#define		WAZANO_GIGADOREIN			( 202 )		//ギガドレイン
#define		WAZANO_KORAERU				( 203 )		//こらえる
#define		WAZANO_AMAERU					( 204 )		//あまえる
#define		WAZANO_KOROGARU				( 205 )		//ころがる
#define		WAZANO_MINEUTI				( 206 )		//みねうち
#define		WAZANO_IBARU					( 207 )		//いばる
#define		WAZANO_MIRUKUNOMI			( 208 )		//ミルクのみ
#define		WAZANO_SUPAAKU				( 209 )		//スパーク
#define		WAZANO_RENZOKUGIRI		( 210 )		//れんぞくぎり
#define		WAZANO_HAGANENOTUBASA	( 211 )		//はがねのつばさ
#define		WAZANO_KUROIMANAZASI	( 212 )		//くろいまなざし
#define		WAZANO_MEROMERO				( 213 )		//メロメロ
#define		WAZANO_NEGOTO					( 214 )		//ねごと
#define		WAZANO_IYASINOSUZU		( 215 )		//いやしのすず
#define		WAZANO_ONGAESI				( 216 )		//おんがえし
#define		WAZANO_PUREZENTO			( 217 )		//プレゼント
#define		WAZANO_YATUATARI			( 218 )		//やつあたり
#define		WAZANO_SINPINOMAMORI	( 219 )		//しんぴのまもり
#define		WAZANO_ITAMIWAKE			( 220 )		//いたみわけ
#define		WAZANO_SEINARUHONOO		( 221 )		//せいなるほのお
#define		WAZANO_MAGUNITYUUDO		( 222 )		//マグニチュード
#define		WAZANO_BAKURETUPANTI	( 223 )		//ばくれつパンチ
#define		WAZANO_MEGAHOON				( 224 )		//メガホーン
#define		WAZANO_RYUUNOIBUKI		( 225 )		//りゅうのいぶき
#define		WAZANO_BATONTATTI			( 226 )		//バトンタッチ
#define		WAZANO_ANKOORU				( 227 )		//アンコール
#define		WAZANO_OIUTI					( 228 )		//おいうち
#define		WAZANO_KOUSOKUSUPIN		( 229 )		//こうそくスピン
#define		WAZANO_AMAIKAORI			( 230 )		//あまいかおり
#define		WAZANO_AIANTEERU			( 231 )		//アイアンテール
#define		WAZANO_METARUKUROO		( 232 )		//メタルクロー
#define		WAZANO_ATEMINAGE			( 233 )		//あてみなげ
#define		WAZANO_ASANOHIZASI		( 234 )		//あさのひざし
#define		WAZANO_KOUGOUSEI			( 235 )		//こうごうせい
#define		WAZANO_TUKINOHIKARI		( 236 )		//つきのひかり
#define		WAZANO_MEZAMERUPAWAA	( 237 )		//めざめるパワー
#define		WAZANO_KUROSUTYOPPU		( 238 )		//クロスチョップ
#define		WAZANO_TATUMAKI				( 239 )		//たつまき
#define		WAZANO_AMAGOI					( 240 )		//あまごい
#define		WAZANO_NIHONBARE			( 241 )		//にほんばれ
#define		WAZANO_KAMIKUDAKU			( 242 )		//かみくだく
#define		WAZANO_MIRAAKOOTO			( 243 )		//ミラーコート
#define		WAZANO_ZIKOANZI				( 244 )		//じこあんじ
#define		WAZANO_SINSOKU				( 245 )		//しんそく
#define		WAZANO_GENSINOTIKARA	( 246 )		//げんしのちから
#define		WAZANO_SYADOOBOORU		( 247 )		//シャドーボール
#define		WAZANO_MIRAIYOTI			( 248 )		//みらいよち
#define		WAZANO_IWAKUDAKI			( 249 )		//いわくだき
#define		WAZANO_UZUSIO					( 250 )		//うずしお
#define		WAZANO_HUKURODATAKI		( 251 )		//ふくろだたき
#define		WAZANO_NEKODAMASI			( 252 )		//ねこだまし
#define		WAZANO_SAWAGU					( 253 )		//さわぐ
#define		WAZANO_TAKUWAERU			( 254 )		//たくわえる
#define		WAZANO_HAKIDASU				( 255 )		//はきだす
#define		WAZANO_NOMIKOMU				( 256 )		//のみこむ
#define		WAZANO_NEPPUU					( 257 )		//ねっぷう
#define		WAZANO_ARARE					( 258 )		//あられ
#define		WAZANO_ITYAMON				( 259 )		//いちゃもん
#define		WAZANO_ODATERU				( 260 )		//おだてる
#define		WAZANO_ONIBI					( 261 )		//おにび
#define		WAZANO_OKIMIYAGE			( 262 )		//おきみやげ
#define		WAZANO_KARAGENKI			( 263 )		//からげんき
#define		WAZANO_KIAIPANTI			( 264 )		//きあいパンチ
#define		WAZANO_KITUKE					( 265 )		//きつけ
#define		WAZANO_KONOYUBITOMARE	( 266 )		//このゆびとまれ
#define		WAZANO_SIZENNOTIKARA	( 267 )		//しぜんのちから
#define		WAZANO_ZYUUDEN				( 268 )		//じゅうでん
#define		WAZANO_TYOUHATU				( 269 )		//ちょうはつ
#define		WAZANO_TEDASUKE				( 270 )		//てだすけ
#define		WAZANO_TORIKKU				( 271 )		//トリック
#define		WAZANO_NARIKIRI				( 272 )		//なりきり
#define		WAZANO_NEGAIGOTO			( 273 )		//ねがいごと
#define		WAZANO_NEKONOTE				( 274 )		//ねこのて
#define		WAZANO_NEWOHARU				( 275 )		//ねをはる
#define		WAZANO_BAKADIKARA			( 276 )		//ばかぢから
#define		WAZANO_MAZIKKUKOOTO		( 277 )		//マジックコート
#define		WAZANO_RISAIKURU			( 278 )		//リサイクル
#define		WAZANO_RIBENZI				( 279 )		//リベンジ
#define		WAZANO_KAWARAWARI			( 280 )		//かわらわり
#define		WAZANO_AKUBI					( 281 )		//あくび
#define		WAZANO_HATAKIOTOSU		( 282 )		//はたきおとす
#define		WAZANO_GAMUSYARA			( 283 )		//がむしゃら
#define		WAZANO_HUNKA					( 284 )		//ふんか
#define		WAZANO_SUKIRUSUWAPPU	( 285 )		//スキルスワップ
#define		WAZANO_HUUIN					( 286 )		//ふういん
#define		WAZANO_RIHURESSYU			( 287 )		//リフレッシュ
#define		WAZANO_ONNEN					( 288 )		//おんねん
#define		WAZANO_YOKODORI				( 289 )		//よこどり
#define		WAZANO_HIMITUNOTIKARA	( 290 )		//ひみつのちから
#define		WAZANO_DAIBINGU				( 291 )		//ダイビング
#define		WAZANO_TUPPARI				( 292 )		//つっぱり
#define		WAZANO_HOGOSYOKU			( 293 )		//ほごしょく
#define		WAZANO_HOTARUBI				( 294 )		//ほたるび
#define		WAZANO_RASUTAAPAAZI		( 295 )		//ラスターパージ
#define		WAZANO_MISUTOBOORU		( 296 )		//ミストボール
#define		WAZANO_FEZAADANSU			( 297 )		//フェザーダンス
#define		WAZANO_HURAHURADANSU	( 298 )		//フラフラダンス
#define		WAZANO_BUREIZUKIKKU		( 299 )		//ブレイズキック
#define		WAZANO_DOROASOBI			( 300 )		//どろあそび
#define		WAZANO_AISUBOORU			( 301 )		//アイスボール
#define		WAZANO_NIIDORUAAMU		( 302 )		//ニードルアーム
#define		WAZANO_NAMAKERU				( 303 )		//なまける
#define		WAZANO_HAIPAABOISU		( 304 )		//ハイパーボイス
#define		WAZANO_DOKUDOKUNOKIBA	( 305 )		//どくどくのキバ
#define		WAZANO_BUREIKUKUROO		( 306 )		//ブレイククロー
#define		WAZANO_BURASUTOBAAN		( 307 )		//ブラストバーン
#define		WAZANO_HAIDOROKANON		( 308 )		//ハイドロカノン
#define		WAZANO_KOMETTOPANTI		( 309 )		//コメットパンチ
#define		WAZANO_ODOROKASU			( 310 )		//おどろかす
#define		WAZANO_WHEZAABOORU		( 311 )		//ウェザーボール
#define		WAZANO_AROMASERAPII		( 312 )		//アロマセラピー
#define		WAZANO_USONAKI				( 313 )		//うそなき
#define		WAZANO_EAKATTAA				( 314 )		//エアカッター
#define		WAZANO_OOBAAHIITO			( 315 )		//オーバーヒート
#define		WAZANO_KAGIWAKERU			( 316 )		//かぎわける
#define		WAZANO_GANSEKIHUUZI		( 317 )		//がんせきふうじ
#define		WAZANO_GINIRONOKAZE		( 318 )		//ぎんいろのかぜ
#define		WAZANO_KINZOKUON			( 319 )		//きんぞくおん
#define		WAZANO_KUSABUE				( 320 )		//くさぶえ
#define		WAZANO_KUSUGURU				( 321 )		//くすぐる
#define		WAZANO_KOSUMOPAWAA		( 322 )		//コスモパワー
#define		WAZANO_SIOHUKI				( 323 )		//しおふき
#define		WAZANO_SIGUNARUBIIMU	( 324 )		//シグナルビーム
#define		WAZANO_SYADOOPANTI		( 325 )		//シャドーパンチ
#define		WAZANO_ZINTUURIKI			( 326 )		//じんつうりき
#define		WAZANO_SUKAIAPPAA			( 327 )		//スカイアッパー
#define		WAZANO_SUNAZIGOKU			( 328 )		//すなじごく
#define		WAZANO_ZETTAIREIDO		( 329 )		//ぜったいれいど
#define		WAZANO_DAKURYUU				( 330 )		//だくりゅう
#define		WAZANO_TANEMASINGAN		( 331 )		//タネマシンガン
#define		WAZANO_TUBAMEGAESI		( 332 )		//つばめがえし
#define		WAZANO_TURARABARI			( 333 )		//つららばり
#define		WAZANO_TEPPEKI				( 334 )		//てっぺき
#define		WAZANO_TOOSENBOU			( 335 )		//とおせんぼう
#define		WAZANO_TOOBOE					( 336 )		//とおぼえ
#define		WAZANO_DORAGONKUROO		( 337 )		//ドラゴンクロー
#define		WAZANO_HAADOPURANTO		( 338 )		//ハードプラント
#define		WAZANO_BIRUDOAPPU			( 339 )		//ビルドアップ
#define		WAZANO_TOBIHANERU			( 340 )		//とびはねる
#define		WAZANO_MADDOSYOTTO		( 341 )		//マッドショット
#define		WAZANO_POIZUNTEERU		( 342 )		//ポイズンテール
#define		WAZANO_HOSIGARU				( 343 )		//ほしがる
#define		WAZANO_BORUTEKKAA			( 344 )		//ボルテッカー
#define		WAZANO_MAZIKARURIIHU	( 345 )		//マジカルリーフ
#define		WAZANO_MIZUASOBI			( 346 )		//みずあそび
#define		WAZANO_MEISOU					( 347 )		//めいそう
#define		WAZANO_RIIHUBUREEDO		( 348 )		//リーフブレード
#define		WAZANO_RYUUNOMAI			( 349 )		//りゅうのまい
#define		WAZANO_ROKKUBURASUTO	( 350 )		//ロックブラスト
#define		WAZANO_DENGEKIHA			( 351 )		//でんげきは
#define		WAZANO_MIZUNOHADOU		( 352 )		//みずのはどう
#define		WAZANO_HAMETUNONEGAI	( 353 )		//はめつのねがい
#define		WAZANO_SAIKOBUUSUTO		( 354 )		//サイコブースト
#define		WAZANO_HANEYASUME			( 355 )		//はねやすめ
#define		WAZANO_ZYUURYOKU			( 356 )		//じゅうりょく
#define		WAZANO_MIRAKURUAI			( 357 )		//ミラクルアイ
#define		WAZANO_MEZAMASIBINTA	( 358 )		//めざましビンタ
#define		WAZANO_AAMUHANMAA			( 359 )		//アームハンマー
#define		WAZANO_ZYAIROBOORU		( 360 )		//ジャイロボール
#define		WAZANO_IYASINONEGAI		( 361 )		//いやしのねがい
#define		WAZANO_SIOMIZU				( 362 )		//しおみず
#define		WAZANO_SIZENNOMEGUMI	( 363 )		//しぜんのめぐみ
#define		WAZANO_FEINTO					( 364 )		//フェイント
#define		WAZANO_TUIBAMU				( 365 )		//ついばむ
#define		WAZANO_OIKAZE					( 366 )		//おいかぜ
#define		WAZANO_TUBOWOTUKU			( 367 )		//つぼをつく
#define		WAZANO_METARUBAASUTO	( 368 )		//メタルバースト
#define		WAZANO_TONBOGAERI			( 369 )		//とんぼがえり
#define		WAZANO_INFAITO				( 370 )		//インファイト
#define		WAZANO_SIPPEGAESI			( 371 )		//しっぺがえし
#define		WAZANO_DAMEOSI				( 372 )		//ダメおし
#define		WAZANO_SASIOSAE				( 373 )		//さしおさえ
#define		WAZANO_NAGETUKERU			( 374 )		//なげつける
#define		WAZANO_SAIKOSIHUTO		( 375 )		//サイコシフト
#define		WAZANO_KIRIHUDA				( 376 )		//きりふだ
#define		WAZANO_KAIHUKUHUUZI		( 377 )		//かいふくふうじ
#define		WAZANO_SIBORITORU			( 378 )		//しぼりとる
#define		WAZANO_PAWAATORIKKU		( 379 )		//パワートリック
#define		WAZANO_IEKI						( 380 )		//いえき
#define		WAZANO_OMAZINAI				( 381 )		//おまじない
#define		WAZANO_SAKIDORI				( 382 )		//さきどり
#define		WAZANO_MANEKKO				( 383 )		//まねっこ
#define		WAZANO_PAWAASUWAPPU		( 384 )		//パワースワップ
#define		WAZANO_GAADOSUWAPPU		( 385 )		//ガードスワップ
#define		WAZANO_OSIOKI					( 386 )		//おしおき
#define		WAZANO_TOTTEOKI				( 387 )		//とっておき
#define		WAZANO_NAYAMINOTANE		( 388 )		//なやみのタネ
#define		WAZANO_HUIUTI					( 389 )		//ふいうち
#define		WAZANO_DOKUBISI				( 390 )		//どくびし
#define		WAZANO_HAATOSUWAPPU		( 391 )		//ハートスワップ
#define		WAZANO_AKUARINGU			( 392 )		//アクアリング
#define		WAZANO_DENZIHUYUU			( 393 )		//でんじふゆう
#define		WAZANO_HUREADORAIBU		( 394 )		//フレアドライブ
#define		WAZANO_HAKKEI					( 395 )		//はっけい
#define		WAZANO_HADOUDAN				( 396 )		//はどうだん
#define		WAZANO_ROKKUKATTO			( 397 )		//ロックカット
#define		WAZANO_DOKUDUKI				( 398 )		//どくづき
#define		WAZANO_AKUNOHADOU			( 399 )		//あくのはどう
#define		WAZANO_TUZIGIRI				( 400 )		//つじぎり
#define		WAZANO_AKUATEERU			( 401 )		//アクアテール
#define		WAZANO_TANEBAKUDAN		( 402 )		//タネばくだん
#define		WAZANO_EASURASSYU			( 403 )		//エアスラッシュ
#define		WAZANO_SIZAAKUROSU		( 404 )		//シザークロス
#define		WAZANO_MUSINOSAZAMEKI	( 405 )		//むしのさざめき
#define		WAZANO_RYUUNOHADOU		( 406 )		//りゅうのはどう
#define		WAZANO_DORAGONDAIBU		( 407 )		//ドラゴンダイブ
#define		WAZANO_PAWAAJEMU			( 408 )		//パワージェム
#define		WAZANO_DOREINPANTI		( 409 )		//ドレインパンチ
#define		WAZANO_SINKUUHA				( 410 )		//しんくうは
#define		WAZANO_KIAIDAMA				( 411 )		//きあいだま
#define		WAZANO_ENAZIIBOORU		( 412 )		//エナジーボール
#define		WAZANO_BUREIBUBAADO		( 413 )		//ブレイブバード
#define		WAZANO_DAITINOTIKARA	( 414 )		//だいちのちから
#define		WAZANO_SURIKAE				( 415 )		//すりかえ
#define		WAZANO_GIGAINPAKUTO		( 416 )		//ギガインパクト
#define		WAZANO_WARUDAKUMI			( 417 )		//わるだくみ
#define		WAZANO_BARETTOPANTI		( 418 )		//バレットパンチ
#define		WAZANO_YUKINADARE			( 419 )		//ゆきなだれ
#define		WAZANO_KOORINOTUBUTE	( 420 )		//こおりのつぶて
#define		WAZANO_SYADOOKUROO		( 421 )		//シャドークロー
#define		WAZANO_KAMINARINOKIBA	( 422 )		//かみなりのキバ
#define		WAZANO_KOORINOKIBA		( 423 )		//こおりのキバ
#define		WAZANO_HONOONOKIBA		( 424 )		//ほのおのキバ
#define		WAZANO_KAGEUTI				( 425 )		//かげうち
#define		WAZANO_DOROBAKUDAN		( 426 )		//どろばくだん
#define		WAZANO_SAIKOKATTAA		( 427 )		//サイコカッター
#define		WAZANO_SINENNOZUTUKI	( 428 )		//しねんのずつき
#define		WAZANO_MIRAASYOTTO		( 429 )		//ミラーショット
#define		WAZANO_RASUTAAKANON		( 430 )		//ラスターカノン
#define		WAZANO_ROKKUKURAIMU		( 431 )		//ロッククライム
#define		WAZANO_KIRIBARAI			( 432 )		//きりばらい
#define		WAZANO_TORIKKURUUMU		( 433 )		//トリックルーム
#define		WAZANO_RYUUSEIGUN			( 434 )		//りゅうせいぐん
#define		WAZANO_HOUDEN					( 435 )		//ほうでん
#define		WAZANO_HUNEN					( 436 )		//ふんえん
#define		WAZANO_RIIHUSUTOOMU		( 437 )		//リーフストーム
#define		WAZANO_PAWAAWHIPPU		( 438 )		//パワーウィップ
#define		WAZANO_GANSEKIHOU			( 439 )		//がんせきほう
#define		WAZANO_KUROSUPOIZUN		( 440 )		//クロスポイズン
#define		WAZANO_DASUTOSYUUTO		( 441 )		//ダストシュート
#define		WAZANO_AIANHEDDO			( 442 )		//アイアンヘッド
#define		WAZANO_MAGUNETTOBOMU	( 443 )		//マグネットボム
#define		WAZANO_SUTOONEZI			( 444 )		//ストーンエッジ
#define		WAZANO_YUUWAKU				( 445 )		//ゆうわく
#define		WAZANO_SUTERUSUROKKU	( 446 )		//ステルスロック
#define		WAZANO_KUSAMUSUBI			( 447 )		//くさむすび
#define		WAZANO_OSYABERI				( 448 )		//おしゃべり
#define		WAZANO_SABAKINOTUBUTE	( 449 )		//さばきのつぶて
#define		WAZANO_MUSIKUI				( 450 )		//むしくい
#define		WAZANO_TYAAZIBIIMU		( 451 )		//チャージビーム
#define		WAZANO_UDDOHANMAA			( 452 )		//ウッドハンマー
#define		WAZANO_AKUAJETTO			( 453 )		//アクアジェット
#define		WAZANO_KOUGEKISIREI		( 454 )		//こうげきしれい
#define		WAZANO_BOUGYOSIREI		( 455 )		//ぼうぎょしれい
#define		WAZANO_KAIHUKUSIREI		( 456 )		//かいふくしれい
#define		WAZANO_MOROHANOZUTUKI	( 457 )		//もろはのずつき
#define		WAZANO_DABURUATAKKU		( 458 )		//ダブルアタック
#define		WAZANO_TOKINOHOUKOU		( 459 )		//ときのほうこう
#define		WAZANO_AKUUSETUDAN		( 460 )		//あくうせつだん
#define		WAZANO_MIKADUKINOMAI	( 461 )		//みかづきのまい
#define		WAZANO_NIGIRITUBUSU		( 462 )		//にぎりつぶす
#define		WAZANO_MAGUMASUTOOMU	( 463 )		//マグマストーム
#define		WAZANO_DAAKUHOORU			( 464 )		//ダークホール
#define		WAZANO_SIIDOHUREA			( 465 )		//シードフレア
#define		WAZANO_AYASIIKAZE			( 466 )		//あやしいかぜ
#define		WAZANO_SYADOODAIBU		( 467 )		//シャドーダイブ
#define		WAZANO_TUMETOGI				( 468 )		//つめとぎ
#define		WAZANO_WAIDOGAADO			( 469 )		//ワイドガード
#define		WAZANO_GAADOSHEA			( 470 )		//ガードシェア
#define		WAZANO_PAWAASHEA			( 471 )		//パワーシェア
#define		WAZANO_WANDAARUUMU		( 472 )		//ワンダールーム
#define		WAZANO_SAIKOSYOKKU		( 473 )		//サイコショック
#define		WAZANO_BENOMUSYOKKU		( 474 )		//ベノムショック
#define		WAZANO_BODHIPAAZI			( 475 )		//ボディパージ
#define		WAZANO_IKARINOKONA		( 476 )		//いかりのこな
#define		WAZANO_TEREKINESISU		( 477 )		//テレキネシス
#define		WAZANO_MAZIKKURUUMU		( 478 )		//マジックルーム
#define		WAZANO_UTIOTOSU				( 479 )		//うちおとす
#define		WAZANO_YAMAARASI			( 480 )		//やまあらし
#define		WAZANO_HAZIKERUHONOO	( 481 )		//はじけるほのお
#define		WAZANO_HEDOROWHEEBU		( 482 )		//ヘドロウェーブ
#define		WAZANO_TYOUNOMAI			( 483 )		//ちょうのまい
#define		WAZANO_HEBIIBONBAA		( 484 )		//ヘビーボンバー
#define		WAZANO_SINKURONOIZU		( 485 )		//シンクロノイズ
#define		WAZANO_EREKUTOBOORU		( 486 )		//エレクトボール
#define		WAZANO_MIZUBITASI			( 487 )		//みずびたし
#define		WAZANO_NITOROTYAAZI		( 488 )		//ニトロチャージ
#define		WAZANO_TOGUROWOMAKU		( 489 )		//とぐろをまく
#define		WAZANO_ROOKIKKU				( 490 )		//ローキック
#define		WAZANO_ASSIDOBOMU			( 491 )		//アッシドボム
#define		WAZANO_IKASAMA				( 492 )		//イカサマ
#define		WAZANO_SINPURUBIIMU		( 493 )		//シンプルビーム
#define		WAZANO_NAKAMADUKURI		( 494 )		//なかまづくり
#define		WAZANO_OSAKINIDOUZO		( 495 )		//おさきにどうぞ
#define		WAZANO_RINSYOU				( 496 )		//りんしょう
#define		WAZANO_EKOOBOISU			( 497 )		//エコーボイス
#define		WAZANO_NASIKUZUSI			( 498 )		//なしくずし
#define		WAZANO_KURIASUMOGGU		( 499 )		//クリアスモッグ
#define		WAZANO_ASISUTOPAWAA		( 500 )		//アシストパワー
#define		WAZANO_FASUTOGAADO		( 501 )		//ファストガード
#define		WAZANO_SAIDOTHENZI		( 502 )		//サイドチェンジ
#define		WAZANO_NETTOU					( 503 )		//ねっとう
#define		WAZANO_KARAWOYABURU		( 504 )		//からをやぶる
#define		WAZANO_IYASINOHADOU		( 505 )		//いやしのはどう
#define		WAZANO_TATARIME				( 506 )		//たたりめ
#define		WAZANO_HURIIFOORU			( 507 )		//フリーフォール
#define		WAZANO_GIATHENZI			( 508 )		//ギアチェンジ
#define		WAZANO_TOMOENAGE			( 509 )		//ともえなげ
#define		WAZANO_YAKITUKUSU			( 510 )		//やきつくす
#define		WAZANO_SAKIOKURI			( 511 )		//さきおくり
#define		WAZANO_AKUROBATTO			( 512 )		//アクロバット
#define		WAZANO_MIRAATAIPU			( 513 )		//ミラータイプ
#define		WAZANO_KATAKIUTI			( 514 )		//かたきうち
#define		WAZANO_INOTIGAKE			( 515 )		//いのちがけ
#define		WAZANO_GIHUTOPASU			( 516 )		//ギフトパス
#define		WAZANO_RENGOKU				( 517 )		//れんごく
#define		WAZANO_MIZUNOTIKAI		( 518 )		//みずのちかい
#define		WAZANO_HONOONOTIKAI		( 519 )		//ほのおのちかい
#define		WAZANO_KUSANOTIKAI		( 520 )		//くさのちかい
#define		WAZANO_BORUTOTHENZI		( 521 )		//ボルトチェンジ
#define		WAZANO_MUSINOTEIKOU		( 522 )		//むしのていこう
#define		WAZANO_ZINARASI				( 523 )		//じならし
#define		WAZANO_KOORINOIBUKI		( 524 )		//こおりのいぶき
#define		WAZANO_DORAGONTEERU		( 525 )		//ドラゴンテール
#define		WAZANO_HURUITATERU		( 526 )		//ふるいたてる
#define		WAZANO_EREKINETTO			( 527 )		//エレキネット
#define		WAZANO_WAIRUDOBORUTO	( 528 )		//ワイルドボルト
#define		WAZANO_DORIRURAINAA		( 529 )		//ドリルライナー
#define		WAZANO_DABURUTYOPPU		( 530 )		//ダブルチョップ
#define		WAZANO_HAATOSUTANPU		( 531 )		//ハートスタンプ
#define		WAZANO_UDDOHOON				( 532 )		//ウッドホーン
#define		WAZANO_SEINARUTURUGI	( 533 )		//せいなるつるぎ
#define		WAZANO_SHERUBUREEDO		( 534 )		//シェルブレード
#define		WAZANO_HIITOSUTANPU		( 535 )		//ヒートスタンプ
#define		WAZANO_GURASUMIKISAA	( 536 )		//グラスミキサー
#define		WAZANO_HAADOROORAA		( 537 )		//ハードローラー
#define		WAZANO_KOTTONGAADO		( 538 )		//コットンガード
#define		WAZANO_NAITOBAASUTO		( 539 )		//ナイトバースト
#define		WAZANO_SAIKOBUREIKU		( 540 )		//サイコブレイク
#define		WAZANO_SUIIPUBINTA		( 541 )		//スイープビンタ
#define		WAZANO_BOUHUU					( 542 )		//ぼうふう
#define		WAZANO_AHUROBUREIKU		( 543 )		//アフロブレイク
#define		WAZANO_GIASOOSAA			( 544 )		//ギアソーサー
#define		WAZANO_MAX						( 544 )
