#! make -f
#----------------------------------------------------------------------------
# Project:  NITRO-System - build - demos - g3d - demolib
# File:     Makefile
#
# Copyright 2004 Nintendo.  All rights reserved.
#
# These coded instructions, statements, and computer programs contain
# proprietary information of Nintendo of America Inc. and/or Nintendo
# Company Ltd., and are protected by Federal copyright law.  They may
# not be disclosed to third parties or copied or duplicated in any form,
# in whole or in part, without the prior written consent of Nintendo.
#
# $Log: Makefile,v $
# Revision 1.2  2004/09/15 01:42:11  okane_shinji
# ÉÅÉCÉNÉtÉ@ÉCÉãèCê≥
#
# Revision 1.1  2004/09/15 01:29:53  okane_shinji
# èâä˙ìoò^
#
#
# $NoKeywords: $
#----------------------------------------------------------------------------


SUBDIRS     =


#----------------------------------------------------------------------------

SRCS        =   ptcl_demo_system.c \
                ptcl_demo_graphics.c \
                ptcl_demo_input.c \

TARGET_LIB  =   libptcl_demo.a

#SRCDIR     =   # using default
#LCFILE     =   # using default

include $(NITROSYSTEM_ROOT)/build/buildtools/commondefs


#----------------------------------------------------------------------------

do-build:       $(TARGETS)


include $(NITROSYSTEM_ROOT)/build/buildtools/modulerules


#===== End of Makefile =====
