//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 07/12/09.
//-----------------------------------------------------
#define    NANR_box_m_obj_CellAnime0    0 // 
#define    NANR_box_m_obj_CellAnime1    1 // 
#define    NANR_box_m_obj_CellAnime2    2 // 
#define    NANR_box_m_obj_CellAnime3    3 // 
#define    NANR_box_m_obj_CellAnime4    4 // 
#define    NANR_box_m_obj_CellAnime6    5 // 
#define    NANR_box_m_obj_CellAnime7    6 // 
#define    NANR_box_m_obj_CellAnime8    7 // 
#define    NANR_box_m_obj_CellAnime10    8 // 
#define    NANR_box_m_obj_CellAnime11    9 // 
#define    NANR_box_m_obj_CellAnime12    10 // 
#define    NANR_box_m_obj_CellAnime14    11 // 
#define    NANR_box_m_obj_CellAnime15    12 // 
#define    NANR_box_m_obj_CellAnime13    13 // 
#define    NANR_box_m_obj_CellAnime5    14 // ボックス用カーソル
#define    NANR_box_m_obj_CellAnime9    15 // ポケいどう用カーソル
#define    NANR_box_m_obj_CellAnime16    16 // こうかん
#define    NANR_box_m_obj_CellAnime17    17 // 
#define    NANR_box_m_obj_CellAnime18    18 // 
