//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 07/13/09.
//-----------------------------------------------------
#define    NANR_p_st_obj_d_return    0 // 戻る
#define    NANR_p_st_obj_d_close    1 // 閉じる
#define    NANR_p_st_obj_d_up    2 // 上へ
#define    NANR_p_st_obj_d_down    3 // 下へ
#define    NANR_p_st_obj_d_chekbox_off    4 // チェック＿ｵﾌ
#define    NANR_p_st_obj_d_chekbox_on    5 // チェック＿オン
#define    NANR_p_st_obj_d_jouhou    6 // じょうほう
#define    NANR_p_st_obj_d_nouryoku    7 // のうりょく
#define    NANR_p_st_obj_d_ribbon    8 // リボン
#define    NANR_p_st_obj_d_CellAnime0    9 // 
#define    NANR_p_st_obj_d_CellAnime1    10 // 
#define    NANR_p_st_obj_d_CellAnime2    11 // 
