#! ruby -Ks
# csvファイルで作成された技マシンリストをファイルメーカーでインポートできる形にコンバート
  require File.dirname(__FILE__) + '/../constant'


class PARA
  enum_const_set %w[
  ZENKOKU_NO
  FORM_NUM
  POKENAME
  FORM_NAME
	WAZAMACHINE1
	WAZAMACHINE2
	WAZAMACHINE3
	WAZAMACHINE4
	WAZAMACHINE5
	WAZAMACHINE6
	WAZAMACHINE7
	WAZAMACHINE8
	WAZAMACHINE9
	WAZAMACHINE10
	WAZAMACHINE11
	WAZAMACHINE12
	WAZAMACHINE13
	WAZAMACHINE14
	WAZAMACHINE15
	WAZAMACHINE16
	WAZAMACHINE17
	WAZAMACHINE18
	WAZAMACHINE19
	WAZAMACHINE20
	WAZAMACHINE21
	WAZAMACHINE22
	WAZAMACHINE23
	WAZAMACHINE24
	WAZAMACHINE25
	WAZAMACHINE26
	WAZAMACHINE27
	WAZAMACHINE28
	WAZAMACHINE29
	WAZAMACHINE30
	WAZAMACHINE31
	WAZAMACHINE32
	WAZAMACHINE33
	WAZAMACHINE34
	WAZAMACHINE35
	WAZAMACHINE36
	WAZAMACHINE37
	WAZAMACHINE38
	WAZAMACHINE39
	WAZAMACHINE40
	WAZAMACHINE41
	WAZAMACHINE42
	WAZAMACHINE43
	WAZAMACHINE44
	WAZAMACHINE45
	WAZAMACHINE46
	WAZAMACHINE47
	WAZAMACHINE48
	WAZAMACHINE49
	WAZAMACHINE50
	WAZAMACHINE51
	WAZAMACHINE52
	WAZAMACHINE53
	WAZAMACHINE54
	WAZAMACHINE55
	WAZAMACHINE56
	WAZAMACHINE57
	WAZAMACHINE58
	WAZAMACHINE59
	WAZAMACHINE60
	WAZAMACHINE61
	WAZAMACHINE62
	WAZAMACHINE63
	WAZAMACHINE64
	WAZAMACHINE65
	WAZAMACHINE66
	WAZAMACHINE67
	WAZAMACHINE68
	WAZAMACHINE69
	WAZAMACHINE70
	WAZAMACHINE71
	WAZAMACHINE72
	WAZAMACHINE73
	WAZAMACHINE74
	WAZAMACHINE75
	WAZAMACHINE76
	WAZAMACHINE77
	WAZAMACHINE78
	WAZAMACHINE79
	WAZAMACHINE80
	WAZAMACHINE81
	WAZAMACHINE82
	WAZAMACHINE83
	WAZAMACHINE84
	WAZAMACHINE85
	WAZAMACHINE86
	WAZAMACHINE87
	WAZAMACHINE88
	WAZAMACHINE89
	WAZAMACHINE90
	WAZAMACHINE91
	WAZAMACHINE92
	WAZAMACHINE93
	WAZAMACHINE94
	WAZAMACHINE95
	WAZAMACHINE96
	WAZAMACHINE97
	WAZAMACHINE98
	WAZAMACHINE99
	WAZAMACHINE100
	WAZAMACHINE101
  ]
end

  ARGV_READ_FILE = 0

  read_data = []
  cnt = 0
  open( ARGV[ ARGV_READ_FILE ] ) {|fp_r|
    while read_data[ cnt ] = fp_r.gets
      cnt += 1
    end
  }

  cnt = 0
  waza_machine = []
  read_data.size.times {|i|
    next if read_data[ i ] == nil
    split_data = read_data[ i ].split(/,/)
    waza_machine.clear
	  for i in PARA::WAZAMACHINE1..PARA::WAZAMACHINE101
      if split_data[ i ] == "●"
        waza_machine << "●"
      else
        waza_machine << ""
      end
    end
    printf( "\"%s\",\"%s\",\"%s\",\"%s\",\"%s\"\n", split_data[ PARA::ZENKOKU_NO ], split_data[ PARA::FORM_NUM ], split_data[ PARA::POKENAME ], split_data[ PARA::FORM_NAME ], waza_machine )
  }
