#! make -f
#----------------------------------------------------------------------------
# Project:  Particle Demo
# File:     Makefile
#
# $Log: Makefile,v $
# Revision 1.8  2004/12/28 02:29:48  okane_shinji
# (none)
#
# Revision 1.7  2004/12/02 08:00:11  okane_shinji
# (none)
#
# Revision 1.6  2004/09/15 01:29:53  okane_shinji
# èâä˙ìoò^
#
# $NoKeywords: $
#----------------------------------------------------------------------------

include	$(NITROSYSTEM_ROOT)/build/buildtools/commondefs


#----------------------------------------------------------------------------

SUBDIRS = \
        PtclLib \
        Simple \
        Callback \
        MultiEmit \
        FreeRes \
        OneTime \

#----------------------------------------------------------------------------

include	$(NITROSYSTEM_ROOT)/build/buildtools/modulerules


#===== End of Makefile =====
