//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 03/20/10.
//-----------------------------------------------------
#define    NANR_bag_parts_d_taisetsu    0 // （閉）たいせつなもの
#define    NANR_bag_parts_d_waza    1 // （閉）わざマシン
#define    NANR_bag_parts_d_kinomi    2 // （閉）きのみ
#define    NANR_bag_parts_d_kaifuku    3 // （閉）かいふく
#define    NANR_bag_parts_d_dougu    4 // （閉）どうぐ
#define    NANR_bag_parts_d_taisetsu1    5 // たいせつなもの
#define    NANR_bag_parts_d_waza1    6 // わざマシン
#define    NANR_bag_parts_d_kinomi1    7 // きのみ
#define    NANR_bag_parts_d_kaifuku1    8 // かいふく
#define    NANR_bag_parts_d_dougu1    9 // どうぐ
