//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 07/19/09.
//-----------------------------------------------------
#define    NANR_bag_win_d_itemwin01    0 // 
#define    NANR_bag_win_d_itemwin02    1 // 
#define    NANR_bag_win_d_scroll    2 // 
#define    NANR_bag_win_d_cursor1    3 // 
