//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 03/18/10.
//-----------------------------------------------------
#define    NANR_bag_parts_d_taisetsu    0 // （開）たいせつなもの
#define    NANR_bag_parts_d_waza    1 // （開）わざマシン
#define    NANR_bag_parts_d_kinomi    2 // （開）きのみ
#define    NANR_bag_parts_d_kaifuku    3 // （開）かいふく
#define    NANR_bag_parts_d_dougu    4 // （開）どうぐ
#define    NANR_bag_parts_d_taisetsu1    5 // たいせつなもの
#define    NANR_bag_parts_d_waza1    6 // わざマシン
#define    NANR_bag_parts_d_kinomi1    7 // きのみ
#define    NANR_bag_parts_d_kaifuku1    8 // かいふく
#define    NANR_bag_parts_d_dougu1    9 // どうぐ
