//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 09/14/09.
//-----------------------------------------------------
#define    NANR_bag_parts_d_taisetsu    0 // 
#define    NANR_bag_parts_d_waza    1 // 
#define    NANR_bag_parts_d_kinomi    2 // 
#define    NANR_bag_parts_d_kaifuku    3 // 
#define    NANR_bag_parts_d_dougu_f    4 // 
#define    NANR_bag_parts_d_dougu_m    5 // 
