#------------------------------------------------------------------------------
#
#
#
#------------------------------------------------------------------------------
RESOURCE_MACRO	= $(PROJECT_RSCDIR)\macro_define



SUBDIRS	=	wmi \
			personal\
			trdata \
			trmsg \
			sound \
			bag \
			test_layout \
			test_graphic\
			place_name \
			field_weather \
			field_weather_light \
			field_light \
			message\
			fldmmdl \
			encount \
			fldmapdata\
			pokegra\
			battle\
			waza_tbl\
			net_err\
			font\
			itemconv\
			itemicon\
			title\
			snd_strm\
			mystery\
			startmenu \
			palace \
			ircbattle \
			wificlub \
			wifi_union_obj \
			wifi_2dchar \
			trainer_case \
			yn_touch \
			mysign \
			pms \
			pms_gra \
			compatible \
			musical \
			infowin \
			c_gear \
			gsync \
			bmpoam \
			shop \
			code_input \
			wazatype_icon \
			wifi_note \
			record \
			selbox \
			particle/wazaeffect \
			others \
			wazaeffect \
			field_menu \
			pokelist \
			wifi_earth \
			p_status \
			app_menu_common \
			irc_ranking \
			iss \
			townmap \
			unionroom \
			winframe \
			trgra \
			irc_compatible \
			worldtrade \
			calender \
			pokefoot \
			debug \
			config \
			narc_cpy \
			pokeicon \
			zukan_data \
            b_bag \
            b_plist \
		  regulation \
			mictest \
			pokemon_center \
			fld3d_ci \
			namein \
            box \
			battle_championship \
			trade \
			waza_oshie \
			sodateya \
			shopdata \
			fld_shortcut_menu \
			wifi_match \
			trtype_bgm \
			local_tvt \
            op_demo \
			battle_recorder \
			multiboot

include $(RESOURCE_MACRO)

.PHONY:	do-build	clean
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
do-build:
	@$(MAKE_SUBDIR)
	@$(ECHO_CURDIR)


#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
clean:
	@$(MAKE_SUBDIR)
	@$(ECHO_CURDIR)


