
include $(PROJECT_RSCDIR)\macro_define

SUBDIRS	=	sample_map others fieldmap fielddata loopbridge fieldmap3dp mb_test fldmapdata wb_trainercard easy_pokelist

.PHONY:	do-build clean

do-build:
	@$(MAKE_SUBDIR)

clean:
	@$(MAKE_SUBDIR)
