
include $(PROJECT_RSCDIR)\macro_define

SUBDIRS	=	sample_map others fieldmap fielddata mb_test easy_pokelist rail_editor

.PHONY:	do-build clean

do-build:
	@$(MAKE_SUBDIR)

clean:
	@$(MAKE_SUBDIR)
