//=============================================================================================
/**
 * @file  poketype.h
 * @brief ポケモンWB  タイプ指定子等の定義
 * @author  taya
 *
 * @date  2008.10.14  作成
 */
//=============================================================================================
#ifndef __POKETYPE_H__
#define __POKETYPE_H__

#include "poketype_def.h"

enum {
  POKE_WAZA_MAX = 4,
};

//------------------------------------------------------------------------------
/**
 *  ポケモン・わざのタイプ
 */
//------------------------------------------------------------------------------
#if 0
typedef enum {

  POKETYPE_ORIGIN = 0,

  POKETYPE_NORMAL = POKETYPE_ORIGIN,
  POKETYPE_BATTLE,
  POKETYPE_HIKOU,
  POKETYPE_POISON,
  POKETYPE_JIMEN,
  POKETYPE_IWA,
  POKETYPE_MUSHI,
  POKETYPE_GHOST,
  POKETYPE_METAL,
  POKETYPE_FIRE,
  POKETYPE_WATER,
  POKETYPE_KUSA,
  POKETYPE_ELECTRIC,
  POKETYPE_SP,
  POKETYPE_KOORI,
  POKETYPE_DRAGON,
  POKETYPE_AKU,

  POKETYPE_MAX,
  POKETYPE_NUMS = POKETYPE_MAX,
  POKETYPE_NULL = POKETYPE_MAX,

  POKETYPE_KAKUTOU = POKETYPE_BATTLE,
  POKETYPE_DOKU = POKETYPE_POISON,
  POKETYPE_HAGANE = POKETYPE_METAL,
  POKETYPE_HONOO = POKETYPE_FIRE,
  POKETYPE_MIZU = POKETYPE_WATER,
  POKETYPE_DENKI = POKETYPE_ELECTRIC,
  POKETYPE_ESPER = POKETYPE_SP,

}PokeType;
#endif

typedef u8 PokeType;

//------------------------------------------------------------------------------
/**
 *  状態異常のタイプ
 *
 *  ※ここに列挙して良い異常の種類は以下の条件を満たすもののみ。
 *
 *  （１）フィールドでもバトルでもその状態に成りうる
 *  （２）相互の重複は起こらない
 */
//------------------------------------------------------------------------------
typedef enum {

  POKESICK_NULL = 0,
  POKESICK_ORIGIN = 1,

  POKESICK_MAHI = POKESICK_ORIGIN,  ///< まひ
  POKESICK_NEMURI,    ///< ねむり
  POKESICK_KOORI,     ///< こおり
  POKESICK_YAKEDO,    ///< やけど
  POKESICK_DOKU,      ///< どく

  POKESICK_MAX,

}PokeSick;



//------------------------------------------------------------------------------
/**
 *  とくせい
 */
//------------------------------------------------------------------------------
typedef enum {

  POKETOKUSEI_NULL = 0,
  POKETOKUSEI_AKUSYUU,
  POKETOKUSEI_AMEFURASI,
  POKETOKUSEI_KASOKU,
  POKETOKUSEI_KABUTOAAMAA,
  POKETOKUSEI_GANJOU,
  POKETOKUSEI_SIMERIKE,
  POKETOKUSEI_JUUNAN,
  POKETOKUSEI_SUNAGAKURE,
  POKETOKUSEI_SEIDENKI,
  POKETOKUSEI_TIKUDEN,
  POKETOKUSEI_TYOSUI,
  POKETOKUSEI_DONKAN,
  POKETOKUSEI_NOOTENKI,
  POKETOKUSEI_FUKUGAN,
  POKETOKUSEI_FUMIN,
  POKETOKUSEI_HENSYOKU,
  POKETOKUSEI_MENEKI,
  POKETOKUSEI_MORAIBI,
  POKETOKUSEI_RINPUN,
  POKETOKUSEI_MAIPEESU,
  POKETOKUSEI_KYUUBAN,
  POKETOKUSEI_IKAKU,
  POKETOKUSEI_KAGEFUMI,
  POKETOKUSEI_SAMEHADA,
  POKETOKUSEI_FUSIGINAMAMORI,
  POKETOKUSEI_FUYUU,
  POKETOKUSEI_HOUSI,
  POKETOKUSEI_SINKURO,
  POKETOKUSEI_KURIABODY,
  POKETOKUSEI_SIZENKAIFUKU,
  POKETOKUSEI_HIRAISIN,
  POKETOKUSEI_TENNOMEGUMI,
  POKETOKUSEI_SUISUI,
  POKETOKUSEI_YOURYOKUSO,
  POKETOKUSEI_HAKKOU,
  POKETOKUSEI_TOREESU,
  POKETOKUSEI_TIKARAMOTI,
  POKETOKUSEI_DOKUNOTOGE,
  POKETOKUSEI_SEISINRYOKU,
  POKETOKUSEI_MAGUMANOYOROI,
  POKETOKUSEI_MIZUNOBEERU,
  POKETOKUSEI_JIRYOKU,
  POKETOKUSEI_BOUON,
  POKETOKUSEI_AMEUKEZARA,
  POKETOKUSEI_SUNAOKOSI,
  POKETOKUSEI_PURESSYAA,
  POKETOKUSEI_ATUISIBOU,
  POKETOKUSEI_HAYAOKI,
  POKETOKUSEI_HONOONOKARADA,
  POKETOKUSEI_NIGEASI,
  POKETOKUSEI_SURUDOIME,
  POKETOKUSEI_KAIRIKIBASAMI,
  POKETOKUSEI_MONOHIROI,
  POKETOKUSEI_NAMAKE,
  POKETOKUSEI_HARIKIRI,
  POKETOKUSEI_MEROMEROBODY,
  POKETOKUSEI_PURASU,
  POKETOKUSEI_MAINASU,
  POKETOKUSEI_TENKIYA,
  POKETOKUSEI_NENCHAKU,
  POKETOKUSEI_DAPPI,
  POKETOKUSEI_KONJOU,
  POKETOKUSEI_FUSIGINAUROKO,
  POKETOKUSEI_HEDOROEKI,
  POKETOKUSEI_SINRYOKU,
  POKETOKUSEI_MOUKA,
  POKETOKUSEI_GEKIRYUU,
  POKETOKUSEI_MUSINOSIRASE,
  POKETOKUSEI_ISIATAMA,
  POKETOKUSEI_HIDERI,
  POKETOKUSEI_ARIJIGOKU,
  POKETOKUSEI_YARUKI,
  POKETOKUSEI_SIROIKEMURI,
  POKETOKUSEI_YOGAPAWAA,
  POKETOKUSEI_SHERUAAMAA,
  POKETOKUSEI_EAROKKU,
  POKETOKUSEI_TIDORIASI,
  POKETOKUSEI_DENKIENJIN,
  POKETOKUSEI_TOUSOUSIN,
  POKETOKUSEI_FUKUTUNOKOKORO,
  POKETOKUSEI_YUKIGAKURE,
  POKETOKUSEI_KUISINBOU,
  POKETOKUSEI_IKARINOTUBO,
  POKETOKUSEI_KARUWAZA,
  POKETOKUSEI_TAINETU,
  POKETOKUSEI_TANJUN,
  POKETOKUSEI_KANSOUHADA,
  POKETOKUSEI_DAUNROODO,
  POKETOKUSEI_TETUNOKOBUSI,
  POKETOKUSEI_POIZUNHIIRU,
  POKETOKUSEI_TEKIOURYOKU,
  POKETOKUSEI_SUKIRURINKU,
  POKETOKUSEI_URUOIBODY,
  POKETOKUSEI_SANPAWAA,
  POKETOKUSEI_HAYAASI,
  POKETOKUSEI_NOOMARUSUKIN,
  POKETOKUSEI_SUNAIPAA,
  POKETOKUSEI_MAJIKKUGAADO,
  POKETOKUSEI_NOOGAADO,
  POKETOKUSEI_ATODASI,
  POKETOKUSEI_TEKUNISYAN,
  POKETOKUSEI_RIIFUGAADO,
  POKETOKUSEI_BUKIYOU,
  POKETOKUSEI_KATAYABURI,
  POKETOKUSEI_KYOUUN,
  POKETOKUSEI_YUUBAKU,
  POKETOKUSEI_KIKENYOTI,
  POKETOKUSEI_YOTIMU,
  POKETOKUSEI_TENNEN,
  POKETOKUSEI_IROMEGANE,
  POKETOKUSEI_FIRUTAA,
  POKETOKUSEI_SUROOSUTAATO,
  POKETOKUSEI_KIMOTTAMA,
  POKETOKUSEI_YOBIMIZU,
  POKETOKUSEI_AISUBODY,
  POKETOKUSEI_HAADOROKKU,
  POKETOKUSEI_YUKIFURASI,
  POKETOKUSEI_MITUATUME,
  POKETOKUSEI_OMITOOSI,
  POKETOKUSEI_SUTEMI,
  POKETOKUSEI_MARUTITAIPU,
  POKETOKUSEI_FURAWAAGIFUTO,
  POKETOKUSEI_NAITOMEA,

  POKETOKUSEI_WARUITEGUSE,        // わるいてぐせ
  POKETOKUSEI_TIKARAZUKU,         // ちからづく
  POKETOKUSEI_AMANOJAKU,          // あまのじゃく
  POKETOKUSEI_KINCHOUKAN,         // きんちょうかん
  POKETOKUSEI_MAKENKI,            // まけんき
  POKETOKUSEI_YOWAKI,             // よわき
  POKETOKUSEI_NOROWAREBODY,       // のろわれボディ
  POKETOKUSEI_MORATERAPII,        // モラテラピー
  POKETOKUSEI_NAKAMAISIKI,        // なかまいしき
  POKETOKUSEI_KUDAKERUYOROI,      // くだけるよろい
  POKETOKUSEI_HEVIMETARU,         // ヘヴィメタル
  POKETOKUSEI_RAITOMETARU,        // ライトメタル
  POKETOKUSEI_MARUTISUKEIRU,      // マルチスケイル
  POKETOKUSEI_DOKUBOUSOU,         // どくぼうそう
  POKETOKUSEI_NETUBOUSOU,         // ねつぼうそう
  POKETOKUSEI_SYUUKAKU,           // しゅうかく
  POKETOKUSEI_AUNNOIKI,           // あうんのいき
  POKETOKUSEI_MURAKKE,            // ムラっけ
  POKETOKUSEI_BOUJIN,             // ぼうじん
  POKETOKUSEI_DOKUSYU,            // どくしゅ
  POKETOKUSEI_SAISEIRYOKU,        // さいせいりょく
  POKETOKUSEI_HATOMUNE,           // はとむね
  POKETOKUSEI_SUNAKAKI,           // すなかき
  POKETOKUSEI_MIRAKURUSUKIN,      // ミラクルスキン
  POKETOKUSEI_SINUTI,             // しんうち
  POKETOKUSEI_IRYUUJON,           // イリュージョン
  POKETOKUSEI_HENSIN,             // へんしん
  POKETOKUSEI_SURINUKE,           // すりぬけ
  POKETOKUSEI_MIIRA,              // ミイラ
  POKETOKUSEI_JISINKAJOU,         // じしんかじょう
  POKETOKUSEI_SEIGINOKOKORO,      // せいぎのこころ
  POKETOKUSEI_BIBIRI,             // びびり
  POKETOKUSEI_MAJIKKUMIRAA,       // マジックミラー
  POKETOKUSEI_SOUSYOKU,           // そうしょく
  POKETOKUSEI_ITAZURAGOKORO,      // いたずらごころ
  POKETOKUSEI_SUNANOTIKARA,       // すなのちから
  POKETOKUSEI_TETUNOTOGE,         // てつのとげ
  POKETOKUSEI_DARUMAMOODO,        // ダルマモード


  POKETOKUSEI_MAX,

}PokeTokusei;



#endif
