//レギュレーションのデータ引き出しラベルです
//reguration.rb reguration.xls からの自動生成です
#pragma once
REG_LV50_SINGLE = 0
REG_LV50_DOUBLE = 1
REG_LV50_TRIPLE = 2
REG_LV50_ROTATION = 3
REG_FREE_SINGLE = 4
REG_FREE_DOUBLE = 5
REG_FREE_TRIPLE = 6
REG_FREE_ROTATION = 7
REG_STANDARD_SINGLE = 8
REG_STANDARD_DOUBLE = 9
REG_STANDARD_TRIPLE = 10
REG_STANDARD_ROTATION = 11
REG_STANDARD_MALTI = 12
