//レギュレーションのデータ引き出しラベルです
//reguration.rb reguration.xls からの自動生成です
#pragma once
#define REG_LV50_SINGLE 0
#define REG_LV50_DOUBLE 1
#define REG_LV50_TRIPLE 2
#define REG_LV50_ROTATION 3
#define REG_FREE_SINGLE 4
#define REG_FREE_DOUBLE 5
#define REG_FREE_TRIPLE 6
#define REG_FREE_ROTATION 7
#define REG_STANDARD_SINGLE 8
#define REG_STANDARD_DOUBLE 9
#define REG_STANDARD_TRIPLE 10
#define REG_STANDARD_ROTATION 11
#define REG_STANDARD_MALTI 12
#define REG_DEBUG_BATTLE 13
#define REG_RND_SINGLE 14
#define REG_RND_DOUBLE 15
#define REG_RND_TRIPLE 16
#define REG_RND_ROTATION 17
#define REG_RND_TRIPLE_SHOOTER 18
#define REG_SUBWAY_SINGLE 19
#define REG_SUBWAY_DOUBLE 20
#define REG_SUBWAY_MALTI 21
