
include $(PROJECT_RSCDIR)\macro_define

SUBDIRS	=	item dressup pokegra_mus stage stage_audience musical_debug musical_shot program

.PHONY:	do-build clean

do-build:
	@$(MAKE_SUBDIR)

clean:
	@$(MAKE_SUBDIR)
