copy /b poke_icon.ncl /b icon_000.ncl
copy /b poke_icon.ncl /b icon_001.ncl
copy /b poke_icon.ncl /b icon_002.ncl
copy /b poke_icon.ncl /b icon_003.ncl
copy /b poke_icon.ncl /b icon_004.ncl
copy /b poke_icon.ncl /b icon_005.ncl
copy /b poke_icon.ncl /b icon_006.ncl
copy /b poke_icon.ncl /b icon_007.ncl
copy /b poke_icon.ncl /b icon_008.ncl
copy /b poke_icon.ncl /b icon_009.ncl
copy /b poke_icon.ncl /b icon_010.ncl
copy /b poke_icon.ncl /b icon_011.ncl
copy /b poke_icon.ncl /b icon_012.ncl
copy /b poke_icon.ncl /b icon_013.ncl
copy /b poke_icon.ncl /b icon_014.ncl
copy /b poke_icon.ncl /b icon_015.ncl
copy /b poke_icon.ncl /b icon_016.ncl
copy /b poke_icon.ncl /b icon_017.ncl
copy /b poke_icon.ncl /b icon_018.ncl
copy /b poke_icon.ncl /b icon_019.ncl
copy /b poke_icon.ncl /b icon_020.ncl
copy /b poke_icon.ncl /b icon_021.ncl
copy /b poke_icon.ncl /b icon_022.ncl
copy /b poke_icon.ncl /b icon_023.ncl
copy /b poke_icon.ncl /b icon_024.ncl
copy /b poke_icon.ncl /b icon_025.ncl
copy /b poke_icon.ncl /b icon_026.ncl
copy /b poke_icon.ncl /b icon_027.ncl
copy /b poke_icon.ncl /b icon_028.ncl
copy /b poke_icon.ncl /b icon_029.ncl
copy /b poke_icon.ncl /b icon_030.ncl
copy /b poke_icon.ncl /b icon_031.ncl
copy /b poke_icon.ncl /b icon_032.ncl
copy /b poke_icon.ncl /b icon_033.ncl
copy /b poke_icon.ncl /b icon_034.ncl
copy /b poke_icon.ncl /b icon_035.ncl
copy /b poke_icon.ncl /b icon_036.ncl
copy /b poke_icon.ncl /b icon_037.ncl
copy /b poke_icon.ncl /b icon_038.ncl
copy /b poke_icon.ncl /b icon_039.ncl
copy /b poke_icon.ncl /b icon_040.ncl
copy /b poke_icon.ncl /b icon_041.ncl
copy /b poke_icon.ncl /b icon_042.ncl
copy /b poke_icon.ncl /b icon_043.ncl
copy /b poke_icon.ncl /b icon_044.ncl
copy /b poke_icon.ncl /b icon_045.ncl
copy /b poke_icon.ncl /b icon_046.ncl
copy /b poke_icon.ncl /b icon_047.ncl
copy /b poke_icon.ncl /b icon_048.ncl
copy /b poke_icon.ncl /b icon_049.ncl
copy /b poke_icon.ncl /b icon_050.ncl
copy /b poke_icon.ncl /b icon_051.ncl
copy /b poke_icon.ncl /b icon_052.ncl
copy /b poke_icon.ncl /b icon_053.ncl
copy /b poke_icon.ncl /b icon_054.ncl
copy /b poke_icon.ncl /b icon_055.ncl
copy /b poke_icon.ncl /b icon_056.ncl
copy /b poke_icon.ncl /b icon_057.ncl
copy /b poke_icon.ncl /b icon_058.ncl
copy /b poke_icon.ncl /b icon_059.ncl
copy /b poke_icon.ncl /b icon_060.ncl
copy /b poke_icon.ncl /b icon_061.ncl
copy /b poke_icon.ncl /b icon_062.ncl
copy /b poke_icon.ncl /b icon_063.ncl
copy /b poke_icon.ncl /b icon_064.ncl
copy /b poke_icon.ncl /b icon_065.ncl
copy /b poke_icon.ncl /b icon_066.ncl
copy /b poke_icon.ncl /b icon_067.ncl
copy /b poke_icon.ncl /b icon_068.ncl
copy /b poke_icon.ncl /b icon_069.ncl
copy /b poke_icon.ncl /b icon_070.ncl
copy /b poke_icon.ncl /b icon_071.ncl
copy /b poke_icon.ncl /b icon_072.ncl
copy /b poke_icon.ncl /b icon_073.ncl
copy /b poke_icon.ncl /b icon_074.ncl
copy /b poke_icon.ncl /b icon_075.ncl
copy /b poke_icon.ncl /b icon_076.ncl
copy /b poke_icon.ncl /b icon_077.ncl
copy /b poke_icon.ncl /b icon_078.ncl
copy /b poke_icon.ncl /b icon_079.ncl
copy /b poke_icon.ncl /b icon_080.ncl
copy /b poke_icon.ncl /b icon_081.ncl
copy /b poke_icon.ncl /b icon_082.ncl
copy /b poke_icon.ncl /b icon_083.ncl
copy /b poke_icon.ncl /b icon_084.ncl
copy /b poke_icon.ncl /b icon_085.ncl
copy /b poke_icon.ncl /b icon_086.ncl
copy /b poke_icon.ncl /b icon_087.ncl
copy /b poke_icon.ncl /b icon_088.ncl
copy /b poke_icon.ncl /b icon_089.ncl
copy /b poke_icon.ncl /b icon_090.ncl
copy /b poke_icon.ncl /b icon_091.ncl
copy /b poke_icon.ncl /b icon_092.ncl
copy /b poke_icon.ncl /b icon_093.ncl
copy /b poke_icon.ncl /b icon_094.ncl
copy /b poke_icon.ncl /b icon_095.ncl
copy /b poke_icon.ncl /b icon_096.ncl
copy /b poke_icon.ncl /b icon_097.ncl
copy /b poke_icon.ncl /b icon_098.ncl
copy /b poke_icon.ncl /b icon_099.ncl
copy /b poke_icon.ncl /b icon_100.ncl
copy /b poke_icon.ncl /b icon_101.ncl
copy /b poke_icon.ncl /b icon_102.ncl
copy /b poke_icon.ncl /b icon_103.ncl
copy /b poke_icon.ncl /b icon_104.ncl
copy /b poke_icon.ncl /b icon_105.ncl
copy /b poke_icon.ncl /b icon_106.ncl
copy /b poke_icon.ncl /b icon_107.ncl
copy /b poke_icon.ncl /b icon_108.ncl
copy /b poke_icon.ncl /b icon_109.ncl
copy /b poke_icon.ncl /b icon_110.ncl
copy /b poke_icon.ncl /b icon_111.ncl
copy /b poke_icon.ncl /b icon_112.ncl
copy /b poke_icon.ncl /b icon_113.ncl
copy /b poke_icon.ncl /b icon_114.ncl
copy /b poke_icon.ncl /b icon_115.ncl
copy /b poke_icon.ncl /b icon_116.ncl
copy /b poke_icon.ncl /b icon_117.ncl
copy /b poke_icon.ncl /b icon_118.ncl
copy /b poke_icon.ncl /b icon_119.ncl
copy /b poke_icon.ncl /b icon_120.ncl
copy /b poke_icon.ncl /b icon_121.ncl
copy /b poke_icon.ncl /b icon_122.ncl
copy /b poke_icon.ncl /b icon_123.ncl
copy /b poke_icon.ncl /b icon_124.ncl
copy /b poke_icon.ncl /b icon_125.ncl
copy /b poke_icon.ncl /b icon_126.ncl
copy /b poke_icon.ncl /b icon_127.ncl
copy /b poke_icon.ncl /b icon_128.ncl
copy /b poke_icon.ncl /b icon_129.ncl
copy /b poke_icon.ncl /b icon_130.ncl
copy /b poke_icon.ncl /b icon_131.ncl
copy /b poke_icon.ncl /b icon_132.ncl
copy /b poke_icon.ncl /b icon_133.ncl
copy /b poke_icon.ncl /b icon_134.ncl
copy /b poke_icon.ncl /b icon_135.ncl
copy /b poke_icon.ncl /b icon_136.ncl
copy /b poke_icon.ncl /b icon_137.ncl
copy /b poke_icon.ncl /b icon_138.ncl
copy /b poke_icon.ncl /b icon_139.ncl
copy /b poke_icon.ncl /b icon_140.ncl
copy /b poke_icon.ncl /b icon_141.ncl
copy /b poke_icon.ncl /b icon_142.ncl
copy /b poke_icon.ncl /b icon_143.ncl
copy /b poke_icon.ncl /b icon_144.ncl
copy /b poke_icon.ncl /b icon_145.ncl
copy /b poke_icon.ncl /b icon_146.ncl
copy /b poke_icon.ncl /b icon_147.ncl
copy /b poke_icon.ncl /b icon_148.ncl
copy /b poke_icon.ncl /b icon_149.ncl
copy /b poke_icon.ncl /b icon_150.ncl
copy /b poke_icon.ncl /b icon_151.ncl
copy /b poke_icon.ncl /b icon_152.ncl
copy /b poke_icon.ncl /b icon_153.ncl
copy /b poke_icon.ncl /b icon_154.ncl
copy /b poke_icon.ncl /b icon_155.ncl
copy /b poke_icon.ncl /b icon_156.ncl
copy /b poke_icon.ncl /b icon_157.ncl
copy /b poke_icon.ncl /b icon_158.ncl
copy /b poke_icon.ncl /b icon_159.ncl
copy /b poke_icon.ncl /b icon_160.ncl
copy /b poke_icon.ncl /b icon_161.ncl
copy /b poke_icon.ncl /b icon_162.ncl
copy /b poke_icon.ncl /b icon_163.ncl
copy /b poke_icon.ncl /b icon_164.ncl
copy /b poke_icon.ncl /b icon_165.ncl
copy /b poke_icon.ncl /b icon_166.ncl
copy /b poke_icon.ncl /b icon_167.ncl
copy /b poke_icon.ncl /b icon_168.ncl
copy /b poke_icon.ncl /b icon_169.ncl
copy /b poke_icon.ncl /b icon_170.ncl
copy /b poke_icon.ncl /b icon_171.ncl
copy /b poke_icon.ncl /b icon_172.ncl
copy /b poke_icon.ncl /b icon_173.ncl
copy /b poke_icon.ncl /b icon_174.ncl
copy /b poke_icon.ncl /b icon_175.ncl
copy /b poke_icon.ncl /b icon_176.ncl
copy /b poke_icon.ncl /b icon_177.ncl
copy /b poke_icon.ncl /b icon_178.ncl
copy /b poke_icon.ncl /b icon_179.ncl
copy /b poke_icon.ncl /b icon_180.ncl
copy /b poke_icon.ncl /b icon_181.ncl
copy /b poke_icon.ncl /b icon_182.ncl
copy /b poke_icon.ncl /b icon_183.ncl
copy /b poke_icon.ncl /b icon_184.ncl
copy /b poke_icon.ncl /b icon_185.ncl
copy /b poke_icon.ncl /b icon_186.ncl
copy /b poke_icon.ncl /b icon_187.ncl
copy /b poke_icon.ncl /b icon_188.ncl
copy /b poke_icon.ncl /b icon_189.ncl
copy /b poke_icon.ncl /b icon_190.ncl
copy /b poke_icon.ncl /b icon_191.ncl
copy /b poke_icon.ncl /b icon_192.ncl
copy /b poke_icon.ncl /b icon_193.ncl
copy /b poke_icon.ncl /b icon_194.ncl
copy /b poke_icon.ncl /b icon_195.ncl
copy /b poke_icon.ncl /b icon_196.ncl
copy /b poke_icon.ncl /b icon_197.ncl
copy /b poke_icon.ncl /b icon_198.ncl
copy /b poke_icon.ncl /b icon_199.ncl
copy /b poke_icon.ncl /b icon_200.ncl
copy /b poke_icon.ncl /b icon_201.ncl
copy /b poke_icon.ncl /b icon_202.ncl
copy /b poke_icon.ncl /b icon_203.ncl
copy /b poke_icon.ncl /b icon_204.ncl
copy /b poke_icon.ncl /b icon_205.ncl
copy /b poke_icon.ncl /b icon_206.ncl
copy /b poke_icon.ncl /b icon_207.ncl
copy /b poke_icon.ncl /b icon_208.ncl
copy /b poke_icon.ncl /b icon_209.ncl
copy /b poke_icon.ncl /b icon_210.ncl
copy /b poke_icon.ncl /b icon_211.ncl
copy /b poke_icon.ncl /b icon_212.ncl
copy /b poke_icon.ncl /b icon_213.ncl
copy /b poke_icon.ncl /b icon_214.ncl
copy /b poke_icon.ncl /b icon_215.ncl
copy /b poke_icon.ncl /b icon_216.ncl
copy /b poke_icon.ncl /b icon_217.ncl
copy /b poke_icon.ncl /b icon_218.ncl
copy /b poke_icon.ncl /b icon_219.ncl
copy /b poke_icon.ncl /b icon_220.ncl
copy /b poke_icon.ncl /b icon_221.ncl
copy /b poke_icon.ncl /b icon_222.ncl
copy /b poke_icon.ncl /b icon_223.ncl
copy /b poke_icon.ncl /b icon_224.ncl
copy /b poke_icon.ncl /b icon_225.ncl
copy /b poke_icon.ncl /b icon_226.ncl
copy /b poke_icon.ncl /b icon_227.ncl
copy /b poke_icon.ncl /b icon_228.ncl
copy /b poke_icon.ncl /b icon_229.ncl
copy /b poke_icon.ncl /b icon_230.ncl
copy /b poke_icon.ncl /b icon_231.ncl
copy /b poke_icon.ncl /b icon_232.ncl
copy /b poke_icon.ncl /b icon_233.ncl
copy /b poke_icon.ncl /b icon_234.ncl
copy /b poke_icon.ncl /b icon_235.ncl
copy /b poke_icon.ncl /b icon_236.ncl
copy /b poke_icon.ncl /b icon_237.ncl
copy /b poke_icon.ncl /b icon_238.ncl
copy /b poke_icon.ncl /b icon_239.ncl
copy /b poke_icon.ncl /b icon_240.ncl
copy /b poke_icon.ncl /b icon_241.ncl
copy /b poke_icon.ncl /b icon_242.ncl
copy /b poke_icon.ncl /b icon_243.ncl
copy /b poke_icon.ncl /b icon_244.ncl
copy /b poke_icon.ncl /b icon_245.ncl
copy /b poke_icon.ncl /b icon_246.ncl
copy /b poke_icon.ncl /b icon_247.ncl
copy /b poke_icon.ncl /b icon_248.ncl
copy /b poke_icon.ncl /b icon_249.ncl
copy /b poke_icon.ncl /b icon_250.ncl
copy /b poke_icon.ncl /b icon_251.ncl
copy /b poke_icon.ncl /b icon_252.ncl
copy /b poke_icon.ncl /b icon_253.ncl
copy /b poke_icon.ncl /b icon_254.ncl
copy /b poke_icon.ncl /b icon_255.ncl
copy /b poke_icon.ncl /b icon_256.ncl
copy /b poke_icon.ncl /b icon_257.ncl
copy /b poke_icon.ncl /b icon_258.ncl
copy /b poke_icon.ncl /b icon_259.ncl
copy /b poke_icon.ncl /b icon_260.ncl
copy /b poke_icon.ncl /b icon_261.ncl
copy /b poke_icon.ncl /b icon_262.ncl
copy /b poke_icon.ncl /b icon_263.ncl
copy /b poke_icon.ncl /b icon_264.ncl
copy /b poke_icon.ncl /b icon_265.ncl
copy /b poke_icon.ncl /b icon_266.ncl
copy /b poke_icon.ncl /b icon_267.ncl
copy /b poke_icon.ncl /b icon_268.ncl
copy /b poke_icon.ncl /b icon_269.ncl
copy /b poke_icon.ncl /b icon_270.ncl
copy /b poke_icon.ncl /b icon_271.ncl
copy /b poke_icon.ncl /b icon_272.ncl
copy /b poke_icon.ncl /b icon_273.ncl
copy /b poke_icon.ncl /b icon_274.ncl
copy /b poke_icon.ncl /b icon_275.ncl
copy /b poke_icon.ncl /b icon_276.ncl
copy /b poke_icon.ncl /b icon_277.ncl
copy /b poke_icon.ncl /b icon_278.ncl
copy /b poke_icon.ncl /b icon_279.ncl
copy /b poke_icon.ncl /b icon_280.ncl
copy /b poke_icon.ncl /b icon_281.ncl
copy /b poke_icon.ncl /b icon_282.ncl
copy /b poke_icon.ncl /b icon_283.ncl
copy /b poke_icon.ncl /b icon_284.ncl
copy /b poke_icon.ncl /b icon_285.ncl
copy /b poke_icon.ncl /b icon_286.ncl
copy /b poke_icon.ncl /b icon_287.ncl
copy /b poke_icon.ncl /b icon_288.ncl
copy /b poke_icon.ncl /b icon_289.ncl
copy /b poke_icon.ncl /b icon_290.ncl
copy /b poke_icon.ncl /b icon_291.ncl
copy /b poke_icon.ncl /b icon_292.ncl
copy /b poke_icon.ncl /b icon_293.ncl
copy /b poke_icon.ncl /b icon_294.ncl
copy /b poke_icon.ncl /b icon_295.ncl
copy /b poke_icon.ncl /b icon_296.ncl
copy /b poke_icon.ncl /b icon_297.ncl
copy /b poke_icon.ncl /b icon_298.ncl
copy /b poke_icon.ncl /b icon_299.ncl
copy /b poke_icon.ncl /b icon_300.ncl
copy /b poke_icon.ncl /b icon_301.ncl
copy /b poke_icon.ncl /b icon_302.ncl
copy /b poke_icon.ncl /b icon_303.ncl
copy /b poke_icon.ncl /b icon_304.ncl
copy /b poke_icon.ncl /b icon_305.ncl
copy /b poke_icon.ncl /b icon_306.ncl
copy /b poke_icon.ncl /b icon_307.ncl
copy /b poke_icon.ncl /b icon_308.ncl
copy /b poke_icon.ncl /b icon_309.ncl
copy /b poke_icon.ncl /b icon_310.ncl
copy /b poke_icon.ncl /b icon_311.ncl
copy /b poke_icon.ncl /b icon_312.ncl
copy /b poke_icon.ncl /b icon_313.ncl
copy /b poke_icon.ncl /b icon_314.ncl
copy /b poke_icon.ncl /b icon_315.ncl
copy /b poke_icon.ncl /b icon_316.ncl
copy /b poke_icon.ncl /b icon_317.ncl
copy /b poke_icon.ncl /b icon_318.ncl
copy /b poke_icon.ncl /b icon_319.ncl
copy /b poke_icon.ncl /b icon_320.ncl
copy /b poke_icon.ncl /b icon_321.ncl
copy /b poke_icon.ncl /b icon_322.ncl
copy /b poke_icon.ncl /b icon_323.ncl
copy /b poke_icon.ncl /b icon_324.ncl
copy /b poke_icon.ncl /b icon_325.ncl
copy /b poke_icon.ncl /b icon_326.ncl
copy /b poke_icon.ncl /b icon_327.ncl
copy /b poke_icon.ncl /b icon_328.ncl
copy /b poke_icon.ncl /b icon_329.ncl
copy /b poke_icon.ncl /b icon_330.ncl
copy /b poke_icon.ncl /b icon_331.ncl
copy /b poke_icon.ncl /b icon_332.ncl
copy /b poke_icon.ncl /b icon_333.ncl
copy /b poke_icon.ncl /b icon_334.ncl
copy /b poke_icon.ncl /b icon_335.ncl
copy /b poke_icon.ncl /b icon_336.ncl
copy /b poke_icon.ncl /b icon_337.ncl
copy /b poke_icon.ncl /b icon_338.ncl
copy /b poke_icon.ncl /b icon_339.ncl
copy /b poke_icon.ncl /b icon_340.ncl
copy /b poke_icon.ncl /b icon_341.ncl
copy /b poke_icon.ncl /b icon_342.ncl
copy /b poke_icon.ncl /b icon_343.ncl
copy /b poke_icon.ncl /b icon_344.ncl
copy /b poke_icon.ncl /b icon_345.ncl
copy /b poke_icon.ncl /b icon_346.ncl
copy /b poke_icon.ncl /b icon_347.ncl
copy /b poke_icon.ncl /b icon_348.ncl
copy /b poke_icon.ncl /b icon_349.ncl
copy /b poke_icon.ncl /b icon_350.ncl
copy /b poke_icon.ncl /b icon_351.ncl
copy /b poke_icon.ncl /b icon_352.ncl
copy /b poke_icon.ncl /b icon_353.ncl
copy /b poke_icon.ncl /b icon_354.ncl
copy /b poke_icon.ncl /b icon_355.ncl
copy /b poke_icon.ncl /b icon_356.ncl
copy /b poke_icon.ncl /b icon_357.ncl
copy /b poke_icon.ncl /b icon_358.ncl
copy /b poke_icon.ncl /b icon_359.ncl
copy /b poke_icon.ncl /b icon_360.ncl
copy /b poke_icon.ncl /b icon_361.ncl
copy /b poke_icon.ncl /b icon_362.ncl
copy /b poke_icon.ncl /b icon_363.ncl
copy /b poke_icon.ncl /b icon_364.ncl
copy /b poke_icon.ncl /b icon_365.ncl
copy /b poke_icon.ncl /b icon_366.ncl
copy /b poke_icon.ncl /b icon_367.ncl
copy /b poke_icon.ncl /b icon_368.ncl
copy /b poke_icon.ncl /b icon_369.ncl
copy /b poke_icon.ncl /b icon_370.ncl
copy /b poke_icon.ncl /b icon_371.ncl
copy /b poke_icon.ncl /b icon_372.ncl
copy /b poke_icon.ncl /b icon_373.ncl
copy /b poke_icon.ncl /b icon_374.ncl
copy /b poke_icon.ncl /b icon_375.ncl
copy /b poke_icon.ncl /b icon_376.ncl
copy /b poke_icon.ncl /b icon_377.ncl
copy /b poke_icon.ncl /b icon_378.ncl
copy /b poke_icon.ncl /b icon_379.ncl
copy /b poke_icon.ncl /b icon_380.ncl
copy /b poke_icon.ncl /b icon_381.ncl
copy /b poke_icon.ncl /b icon_382.ncl
copy /b poke_icon.ncl /b icon_383.ncl
copy /b poke_icon.ncl /b icon_384.ncl
copy /b poke_icon.ncl /b icon_385.ncl
copy /b poke_icon.ncl /b icon_386.ncl
copy /b poke_icon.ncl /b icon_412.ncl
copy /b poke_icon.ncl /b icon_413.ncl
copy /b poke_icon.ncl /b icon_414.ncl
copy /b poke_icon.ncl /b icon_415.ncl
copy /b poke_icon.ncl /b icon_416.ncl
copy /b poke_icon.ncl /b icon_417.ncl
copy /b poke_icon.ncl /b icon_418.ncl
copy /b poke_icon.ncl /b icon_419.ncl
copy /b poke_icon.ncl /b icon_420.ncl
copy /b poke_icon.ncl /b icon_421.ncl
copy /b poke_icon.ncl /b icon_422.ncl
copy /b poke_icon.ncl /b icon_423.ncl
copy /b poke_icon.ncl /b icon_424.ncl
copy /b poke_icon.ncl /b icon_425.ncl
copy /b poke_icon.ncl /b icon_426.ncl
copy /b poke_icon.ncl /b icon_427.ncl
copy /b poke_icon.ncl /b icon_428.ncl
copy /b poke_icon.ncl /b icon_429.ncl
copy /b poke_icon.ncl /b icon_430.ncl
copy /b poke_icon.ncl /b icon_431.ncl
copy /b poke_icon.ncl /b icon_432.ncl
copy /b poke_icon.ncl /b icon_433.ncl
copy /b poke_icon.ncl /b icon_434.ncl
copy /b poke_icon.ncl /b icon_435.ncl
copy /b poke_icon.ncl /b icon_436.ncl
copy /b poke_icon.ncl /b icon_437.ncl
copy /b poke_icon.ncl /b icon_438.ncl
copy /b poke_icon.ncl /b icon_439.ncl
copy /b poke_icon.ncl /b icon_440.ncl
copy /b poke_icon.ncl /b icon_441.ncl
copy /b poke_icon.ncl /b icon_442.ncl
copy /b poke_icon.ncl /b icon_443.ncl
copy /b poke_icon.ncl /b icon_444.ncl
copy /b poke_icon.ncl /b icon_445.ncl
copy /b poke_icon.ncl /b icon_446.ncl
copy /b poke_icon.ncl /b icon_447.ncl
copy /b poke_icon.ncl /b icon_448.ncl
copy /b poke_icon.ncl /b icon_449.ncl
copy /b poke_icon.ncl /b icon_450.ncl
copy /b poke_icon.ncl /b icon_451.ncl
copy /b poke_icon.ncl /b icon_452.ncl
copy /b poke_icon.ncl /b icon_453.ncl
copy /b poke_icon.ncl /b icon_454.ncl
copy /b poke_icon.ncl /b icon_455.ncl
copy /b poke_icon.ncl /b icon_456.ncl
copy /b poke_icon.ncl /b icon_457.ncl
copy /b poke_icon.ncl /b icon_458.ncl
copy /b poke_icon.ncl /b icon_459.ncl
copy /b poke_icon.ncl /b icon_460.ncl
copy /b poke_icon.ncl /b icon_461.ncl
copy /b poke_icon.ncl /b icon_462.ncl
copy /b poke_icon.ncl /b icon_463.ncl
copy /b poke_icon.ncl /b icon_464.ncl
copy /b poke_icon.ncl /b icon_465.ncl
copy /b poke_icon.ncl /b icon_466.ncl
copy /b poke_icon.ncl /b icon_467.ncl
copy /b poke_icon.ncl /b icon_468.ncl
copy /b poke_icon.ncl /b icon_469.ncl
copy /b poke_icon.ncl /b icon_470.ncl
copy /b poke_icon.ncl /b icon_471.ncl
copy /b poke_icon.ncl /b icon_472.ncl
copy /b poke_icon.ncl /b icon_473.ncl
copy /b poke_icon.ncl /b icon_474.ncl
copy /b poke_icon.ncl /b icon_475.ncl
copy /b poke_icon.ncl /b icon_476.ncl
copy /b poke_icon.ncl /b icon_477.ncl
copy /b poke_icon.ncl /b icon_478.ncl
copy /b poke_icon.ncl /b icon_479.ncl
copy /b poke_icon.ncl /b icon_480.ncl
copy /b poke_icon.ncl /b icon_481.ncl
copy /b poke_icon.ncl /b icon_482.ncl
copy /b poke_icon.ncl /b icon_483.ncl
copy /b poke_icon.ncl /b icon_484.ncl
copy /b poke_icon.ncl /b icon_485.ncl
copy /b poke_icon.ncl /b icon_486.ncl
copy /b poke_icon.ncl /b icon_487.ncl
copy /b poke_icon.ncl /b icon_488.ncl
copy /b poke_icon.ncl /b icon_489.ncl
copy /b poke_icon.ncl /b icon_490.ncl
copy /b poke_icon.ncl /b icon_491.ncl
copy /b poke_icon.ncl /b icon_492.ncl
copy /b poke_icon.ncl /b icon_493.ncl
copy /b poke_icon.ncl /b icon_494.ncl
copy /b poke_icon.ncl /b icon_495.ncl
copy /b poke_icon.ncl /b icon_496.ncl
copy /b poke_icon.ncl /b icon_497.ncl
copy /b poke_icon.ncl /b icon_498.ncl
copy /b poke_icon.ncl /b icon_499.ncl
copy /b poke_icon.ncl /b icon_500.ncl
copy /b poke_icon.ncl /b icon_501.ncl
copy /b poke_icon.ncl /b icon_502.ncl
copy /b poke_icon.ncl /b icon_503.ncl
copy /b poke_icon.ncl /b icon_504.ncl
copy /b poke_icon.ncl /b icon_505.ncl
copy /b poke_icon.ncl /b icon_506.ncl
copy /b poke_icon.ncl /b icon_507.ncl
copy /b poke_icon.ncl /b icon_508.ncl
copy /b poke_icon.ncl /b icon_509.ncl
copy /b poke_icon.ncl /b icon_510.ncl
copy /b poke_icon.ncl /b icon_511.ncl
copy /b poke_icon.ncl /b icon_512.ncl
copy /b poke_icon.ncl /b icon_513.ncl
copy /b poke_icon.ncl /b icon_514.ncl
copy /b poke_icon.ncl /b icon_515.ncl
copy /b poke_icon.ncl /b icon_516.ncl
copy /b poke_icon.ncl /b icon_517.ncl
copy /b poke_icon.ncl /b icon_518.ncl
copy /b poke_icon.ncl /b icon_519.ncl
copy /b poke_icon.ncl /b icon_c01.ncl
copy /b poke_icon.ncl /b icon_d01.ncl
copy /b poke_icon.ncl /b icon_d02.ncl
copy /b poke_icon.ncl /b icon_d03.ncl
copy /b poke_icon.ncl /b icon_mnf.ncl
copy /b poke_icon.ncl /b icon_tam.ncl
copy /b poke_icon.ncl /b icon_u01.ncl
copy /b poke_icon.ncl /b icon_u02.ncl
copy /b poke_icon.ncl /b icon_u03.ncl
copy /b poke_icon.ncl /b icon_u04.ncl
copy /b poke_icon.ncl /b icon_u05.ncl
copy /b poke_icon.ncl /b icon_u06.ncl
copy /b poke_icon.ncl /b icon_u07.ncl
copy /b poke_icon.ncl /b icon_u08.ncl
copy /b poke_icon.ncl /b icon_u09.ncl
copy /b poke_icon.ncl /b icon_u10.ncl
copy /b poke_icon.ncl /b icon_u11.ncl
copy /b poke_icon.ncl /b icon_u12.ncl
copy /b poke_icon.ncl /b icon_u13.ncl
copy /b poke_icon.ncl /b icon_u14.ncl
copy /b poke_icon.ncl /b icon_u15.ncl
copy /b poke_icon.ncl /b icon_u16.ncl
copy /b poke_icon.ncl /b icon_u17.ncl
copy /b poke_icon.ncl /b icon_u18.ncl
copy /b poke_icon.ncl /b icon_u19.ncl
copy /b poke_icon.ncl /b icon_u20.ncl
copy /b poke_icon.ncl /b icon_u21.ncl
copy /b poke_icon.ncl /b icon_u22.ncl
copy /b poke_icon.ncl /b icon_u23.ncl
copy /b poke_icon.ncl /b icon_u24.ncl
copy /b poke_icon.ncl /b icon_u25.ncl
copy /b poke_icon.ncl /b icon_u26.ncl
copy /b poke_icon.ncl /b icon_u27.ncl
copy /b poke_icon.ncl /b icon_u28.ncl
copy /b poke_icon.ncl /b icon_455_01.ncl
copy /b poke_icon.ncl /b icon_455_02.ncl
copy /b poke_icon.ncl /b icon_457_01.ncl
copy /b poke_icon.ncl /b icon_457_02.ncl
copy /b poke_icon.ncl /b icon_458_01.ncl
copy /b poke_icon.ncl /b icon_459_01.ncl
copy /b poke_icon.ncl /b icon_509_01.ncl
copy /b poke_icon.ncl /b icon_516_01.ncl
copy /b poke_icon.ncl /b icon_519_01.ncl
copy /b poke_icon.ncl /b icon_519_02.ncl
copy /b poke_icon.ncl /b icon_519_03.ncl
copy /b poke_icon.ncl /b icon_519_04.ncl
copy /b poke_icon.ncl /b icon_519_05.ncl

copy /b poke_icon.ncl /b icon_391.ncl
copy /b poke_icon.ncl /b icon_395.ncl
copy /b poke_icon.ncl /b icon_404.ncl
copy /b poke_icon.ncl /b icon_405.ncl
copy /b poke_icon.ncl /b icon_387.ncl
copy /b poke_icon.ncl /b icon_401.ncl
copy /b poke_icon.ncl /b icon_392.ncl
copy /b poke_icon.ncl /b icon_393.ncl
copy /b poke_icon.ncl /b icon_una.ncl
copy /b poke_icon.ncl /b icon_unb.ncl
copy /b poke_icon.ncl /b icon_unc.ncl
copy /b poke_icon.ncl /b icon_und.ncl
copy /b poke_icon.ncl /b icon_une.ncl
copy /b poke_icon.ncl /b icon_unf.ncl
copy /b poke_icon.ncl /b icon_ung.ncl
copy /b poke_icon.ncl /b icon_unh.ncl
copy /b poke_icon.ncl /b icon_uni.ncl
copy /b poke_icon.ncl /b icon_unj.ncl
copy /b poke_icon.ncl /b icon_unk.ncl
copy /b poke_icon.ncl /b icon_unl.ncl
copy /b poke_icon.ncl /b icon_unm.ncl
copy /b poke_icon.ncl /b icon_unn.ncl
copy /b poke_icon.ncl /b icon_uno.ncl
copy /b poke_icon.ncl /b icon_unp.ncl
copy /b poke_icon.ncl /b icon_unq.ncl
copy /b poke_icon.ncl /b icon_unr.ncl
copy /b poke_icon.ncl /b icon_uns.ncl
copy /b poke_icon.ncl /b icon_unt.ncl
copy /b poke_icon.ncl /b icon_unu.ncl
copy /b poke_icon.ncl /b icon_unv.ncl
copy /b poke_icon.ncl /b icon_unw.ncl
copy /b poke_icon.ncl /b icon_unx.ncl
copy /b poke_icon.ncl /b icon_uny.ncl
copy /b poke_icon.ncl /b icon_unz.ncl
copy /b poke_icon.ncl /b icon_exc.ncl
copy /b poke_icon.ncl /b icon_que.ncl

copy /b poke_icon.ncl /b icon_351_rain.ncl
copy /b poke_icon.ncl /b icon_351_snow.ncl
copy /b poke_icon.ncl /b icon_351_sun.ncl
copy /b poke_icon.ncl /b icon_483_sun.ncl
