//このファイルはコンバータにより生成されます
enum {
	AREA_ID_FIELD            =   0,
	AREA_ID_ROOM             =   1,
	AREA_ID_OUT01            =   2,
	AREA_ID_OUT01_SPRING     =   2,
	AREA_ID_OUT01_SUMMER     =   3,
	AREA_ID_OUT01_AUTUMN     =   4,
	AREA_ID_OUT01_WINTER     =   5,
	AREA_ID_OUT04            =   6,
	AREA_ID_OUT05            =   7,
	AREA_ID_IN01             =   8,
	AREA_ID_IN02             =   9,
	AREA_ID_IN_PC            =  10,
	AREA_ID_IN04             =  11,
	AREA_ID_IN05             =  12,
	AREA_ID_DUNGEON01        =  13,
	AREA_ID_DUNGEON02        =  14,
	AREA_ID_DUNGEON03        =  15,
	AREA_ID_DUNGEON04        =  16,
	AREA_ID_TESTBRIDGE01     =  17,
	AREA_ID_TESTBRIDGE02     =  18,
	AREA_ID_LOOPBRIDGE       =  19,
	AREA_ID_MAX
};