//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 02/07/07.
//-----------------------------------------------------
#define    NANR_fall_obj_KURIBO_STOP_U    0 // 
#define    NANR_fall_obj_KURIBO_STOP_D    1 // 
#define    NANR_fall_obj_KURIBO_TUBURE_U    2 // 
#define    NANR_fall_obj_KURIBO_TUBURE_D    3 // 
#define    NANR_fall_obj_KURIBO_FALL    4 // 
#define    NANR_fall_obj_KURIBO_ROTATE_UD    5 // 
#define    NANR_fall_obj_KURIBO_ROTATE_DU    6 // 
#define    NANR_fall_obj_PAKKUN_STOP_U    7 // 
#define    NANR_fall_obj_PAKKUN_STOP_D    8 // 
#define    NANR_fall_obj_PAKKUN_TUBURE_U    9 // 
#define    NANR_fall_obj_PAKKUN_TUBURE_D    10 // 
#define    NANR_fall_obj_PAKKUN_FALL    11 // 
#define    NANR_fall_obj_PAKKUN_ROTATE_UD    12 // 
#define    NANR_fall_obj_PAKKUN_ROTATE_DU    13 // 
#define    NANR_fall_obj_GESSO_STOP_U    14 // 
#define    NANR_fall_obj_GESSO_STOP_D    15 // 
#define    NANR_fall_obj_GESSO_TUBURE_U    16 // 
#define    NANR_fall_obj_GESSO_TUBURE_D    17 // 
#define    NANR_fall_obj_GESSO_FALL    18 // 
#define    NANR_fall_obj_GESSO_ROTATE_UD    19 // 
#define    NANR_fall_obj_GESSO_ROTATE_DU    20 // 
#define    NANR_fall_obj_TERESA_STOP_U    21 // 
#define    NANR_fall_obj_TERESA_STOP_D    22 // 
#define    NANR_fall_obj_TERESA_TUBURE_U    23 // 
#define    NANR_fall_obj_TERESA_TUBURE_D    24 // 
#define    NANR_fall_obj_TERESA_FALL    25 // 
#define    NANR_fall_obj_TERESA_ROTATE_UD    26 // 
#define    NANR_fall_obj_TERESA_ROTATE_DU    27 // 
#define    NANR_fall_obj_DEKATERESA_STOP_U    28 // 
#define    NANR_fall_obj_DEKATERESA_STOP_D    29 // 
#define    NANR_fall_obj_DEKATERESA_TUBURE_U    30 // 
#define    NANR_fall_obj_DEKATERESA_TUBURE_D    31 // 
#define    NANR_fall_obj_DEKATERESA_FALL    32 // 
#define    NANR_fall_obj_DEKATERESA_ROTATE_UD    33 // 
#define    NANR_fall_obj_DEKATERESA_ROTATE_DU    34 // 
#define    NANR_fall_obj_GREEN_EGG_U    35 // 
#define    NANR_fall_obj_GREEN_EGG_D    36 // 
#define    NANR_fall_obj_GREEN_EGG_ROTATE_UD    37 // 
#define    NANR_fall_obj_GREEN_EGG_ROTATE_DU    38 // 
#define    NANR_fall_obj_RED_EGG_U    39 // 
#define    NANR_fall_obj_RED_EGG_D    40 // 
#define    NANR_fall_obj_RED_EGG_ROTATE_UD    41 // 
#define    NANR_fall_obj_RED_EGG_ROTATE_DU    42 // 
#define    NANR_fall_obj_GREEN_EGG    43 // 
#define    NANR_fall_obj_GREEN_EGG_ROTATE    44 // 
#define    NANR_fall_obj_RED_EGG    45 // 
#define    NANR_fall_obj_RED_EGG_ROTATE    46 // 
#define    NANR_fall_obj_GREEN_EGG_KAKERA    47 // 
#define    NANR_fall_obj_RED_EGG_KAKERA    48 // 
#define    NANR_fall_obj_CHR_KIE    49 // 
#define    NANR_fall_obj_JUGEM_MOVE    50 // 
