//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 02/15/10.
//-----------------------------------------------------
#define    NANR_wb_trade_obj01_CellAnime0    0 // 
#define    NANR_wb_trade_obj01_x    1 // 
#define    NANR_wb_trade_obj01_CellAnime2    2 // 
#define    NANR_wb_trade_obj01_x2    3 // 
#define    NANR_wb_trade_obj01_CellAnime4    4 // 
#define    NANR_wb_trade_obj01_CellAnime5    5 // 
#define    NANR_wb_trade_obj01_CellAnime6    6 // 
#define    NANR_wb_trade_obj01_CellAnime7    7 // 
#define    NANR_wb_trade_obj01_CellAnime8    8 // 
#define    NANR_wb_trade_obj01_CellAnime9    9 // 
#define    NANR_wb_trade_obj01_CellAnime10    10 // 
#define    NANR_wb_trade_obj01_icon1    11 // 
#define    NANR_wb_trade_obj01_icon2    12 // 
#define    NANR_wb_trade_obj01_icon3    13 // 
#define    NANR_wb_trade_obj01_icon4    14 // 
#define    NANR_wb_trade_obj01_icon11    15 // 
#define    NANR_wb_trade_obj01_icon21    16 // 
#define    NANR_wb_trade_obj01_icon31    17 // 
#define    NANR_wb_trade_obj01_icon41    18 // 
#define    NANR_wb_trade_obj01_icon12    19 // 
#define    NANR_wb_trade_obj01_icon22    20 // 
#define    NANR_wb_trade_obj01_icon32    21 // 
#define    NANR_wb_trade_obj01_icon42    22 // 
#define    NANR_wb_trade_obj01_fukidashi    23 // 
