//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 02/21/10.
//-----------------------------------------------------
#define    NANR_wb_trade_obj01_icon12    0 // 
#define    NANR_wb_trade_obj01_icon22    1 // 
#define    NANR_wb_trade_obj01_icon32    2 // 
#define    NANR_wb_trade_obj01_icon42    3 // 
#define    NANR_wb_trade_obj01_fukidashi    4 // 
