//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 10/29/09.
//-----------------------------------------------------
#define    NANR_wb_trade_obj01_CellAnime0    0 // 
#define    NANR_wb_trade_obj01_CellAnime1    1 // 
#define    NANR_wb_trade_obj01_CellAnime2    2 // 
#define    NANR_wb_trade_obj01_CellAnime3    3 // 
#define    NANR_wb_trade_obj01_CellAnime4    4 // 
#define    NANR_wb_trade_obj01_CellAnime5    5 // 
#define    NANR_wb_trade_obj01_CellAnime6    6 // 
#define    NANR_wb_trade_obj01_CellAnime7    7 // 
#define    NANR_wb_trade_obj01_CellAnime8    8 // 
#define    NANR_wb_trade_obj01_CellAnime9    9 // 
