///////////////////////////////////////////////////////////////////////////////
// GameSpy ATLAS Competition System Source File
//
// NOTE: This is an auto-generated file, do not edit this file directly.
///////////////////////////////////////////////////////////////////////////////

#include <string.h>
#include "atlas_syachi2ds_v1.h"

int atlas_rule_set_version = 1;

int ATLAS_GET_KEY(char* keyName)
{
   if(!keyName)
      return 0;
   
   if(!strcmp("KEY_ARENA_GAMETYPE_1V1", keyName))
      return KEY_ARENA_GAMETYPE_1V1;   
   if(!strcmp("KEY_NUM_SINGLE_MATCH_COUNTER", keyName))
      return KEY_NUM_SINGLE_MATCH_COUNTER;   
   if(!strcmp("KEY_ARENA_GAMETYPE_1V1_DOUBLE", keyName))
      return KEY_ARENA_GAMETYPE_1V1_DOUBLE;   
   if(!strcmp("ARENA_FFA_PLACE", keyName))
      return ARENA_FFA_PLACE;   
   
   return 0;
}

char* ATLAS_GET_KEY_NAME(int keyId)
{
   if(keyId <= 0)
      return "";
   
   if(keyId == KEY_ARENA_GAMETYPE_1V1)
      return "KEY_ARENA_GAMETYPE_1V1";   
   if(keyId == KEY_NUM_SINGLE_MATCH_COUNTER)
      return "KEY_NUM_SINGLE_MATCH_COUNTER";   
   if(keyId == KEY_ARENA_GAMETYPE_1V1_DOUBLE)
      return "KEY_ARENA_GAMETYPE_1V1_DOUBLE";   
   if(keyId == ARENA_FFA_PLACE)
      return "ARENA_FFA_PLACE";   
   
   return "";
}

int ATLAS_GET_STAT(char* statName)
{
   if(!statName)
      return 0;
   
   if(!strcmp("ARENA_ELO_RATING_1V1", statName))
      return ARENA_ELO_RATING_1V1;   
   if(!strcmp("ARENA_ELO_RATING_1V1_DOUBLE", statName))
      return ARENA_ELO_RATING_1V1_DOUBLE;   
   if(!strcmp("ARENA_INITIAL_RATING", statName))
      return ARENA_INITIAL_RATING;   
   if(!strcmp("COMPLETE_MATCHES_COUNTER", statName))
      return COMPLETE_MATCHES_COUNTER;   
   if(!strcmp("DISCONNECT_RATE", statName))
      return DISCONNECT_RATE;   
   if(!strcmp("DISCONNECTS_COUNTER", statName))
      return DISCONNECTS_COUNTER;   
   if(!strcmp("NUM_SINGLE_MATCH_COUNTER", statName))
      return NUM_SINGLE_MATCH_COUNTER;   
   if(!strcmp("TOTAL_MATCHES_COUNTER", statName))
      return TOTAL_MATCHES_COUNTER;   
   
   return 0;
}
char* ATLAS_GET_STAT_NAME(int statId)
{
   if(statId <= 0)
      return "";
   
   if(statId == ARENA_ELO_RATING_1V1)
      return "ARENA_ELO_RATING_1V1";   
   if(statId == ARENA_ELO_RATING_1V1_DOUBLE)
      return "ARENA_ELO_RATING_1V1_DOUBLE";   
   if(statId == ARENA_INITIAL_RATING)
      return "ARENA_INITIAL_RATING";   
   if(statId == COMPLETE_MATCHES_COUNTER)
      return "COMPLETE_MATCHES_COUNTER";   
   if(statId == DISCONNECT_RATE)
      return "DISCONNECT_RATE";   
   if(statId == DISCONNECTS_COUNTER)
      return "DISCONNECTS_COUNTER";   
   if(statId == NUM_SINGLE_MATCH_COUNTER)
      return "NUM_SINGLE_MATCH_COUNTER";   
   if(statId == TOTAL_MATCHES_COUNTER)
      return "TOTAL_MATCHES_COUNTER";   
   
   return "";
}

int ATLAS_GET_STAT_PAGE_BY_ID(int statId)
{
   if(statId <= 0)
      return 0;
   

   //PlayerStats
   if(statId == 1 || statId == 2 || statId == 3 || statId == 4 || statId == 5 || statId == 6 || statId == 7)
      return 1;   

   
   //StaticStats
   if(statId == 8)
      return 1;   
      
   
   return 0;
}

int ATLAS_GET_STAT_PAGE_BY_NAME(char* statName)
{
   if(!statName)
      return 0;
   

   //PlayerStats
   if(!strcmp("ARENA_ELO_RATING_1V1", statName) || !strcmp("TOTAL_MATCHES_COUNTER", statName) ||
      !strcmp("DISCONNECTS_COUNTER", statName) || !strcmp("COMPLETE_MATCHES_COUNTER", statName) ||
      !strcmp("DISCONNECT_RATE", statName) || !strcmp("NUM_SINGLE_MATCH_COUNTER", statName) ||
      !strcmp("ARENA_ELO_RATING_1V1_DOUBLE", statName))
      return 1;   

   
   //StaticStats
   if(!strcmp("ARENA_INITIAL_RATING", statName))
      return 1;   
      
   
   return 0;
}

