///////////////////////////////////////////////////////////////////////////////
// GameSpy ATLAS Competition System Header File
//
// NOTE: This is an auto-generated file, do not edit this file directly.
//  
// Atlasサーバから吐き出されるhとcです。
// 変更項目は以下
// ・DWC_GdbGetMyRecordsAsyncで使うため、使用キー文字列をテーブル化
// ・strcmpを使用していたのをGFL_STD_StrCmpへ変更
//
///////////////////////////////////////////////////////////////////////////////

#ifndef _ATLAS_SYACHI2DS_V1_H_
#define _ATLAS_SYACHI2DS_V1_H_

#ifdef __cplusplus
extern "C" {
#endif

extern const char** ATLAS_GetFieldName( void );
extern u32 ATLAS_GetFieldNameNum( void );

extern int ATLAS_GET_KEY(char* keyName);
extern char* ATLAS_GET_KEY_NAME(int keyId);
extern int ATLAS_GET_STAT(char* statName);
extern char* ATLAS_GET_STAT_NAME(int statId);
extern int ATLAS_GET_STAT_PAGE_BY_ID(int statId);
extern int ATLAS_GET_STAT_PAGE_BY_NAME(char* statName);

#define ATLAS_RULE_SET_VERSION 1

// KEYS
// Use these key ID's to report match data for your game.

#define KEY_NUM_SINGLE_WIN_COUNTER 5  // [TYPE: short]
#define KEY_NUM_SINGLE_LOSE_COUNTER 6  // [TYPE: short]
#define KEY_NUM_DOUBLE_LOSE_COUNTER 7  // [TYPE: short]
#define KEY_NUM_DOUBLE_WIN_COUNTER 8  // [TYPE: short]
#define KEY_NUM_ROTATE_WIN_COUNTER 9  // [TYPE: short]
#define KEY_NUM_ROTATE_LOSE_COUNTER 10  // [TYPE: short]
#define KEY_NUM_TRIPLE_WIN_COUNTER 11  // [TYPE: short]
#define KEY_NUM_TRIPLE_LOSE_COUNTER 12  // [TYPE: short]
#define KEY_NUM_SHOOTER_WIN_COUNTER 13  // [TYPE: short]
#define KEY_NUM_SHOOTER_LOSE_COUNTER 14  // [TYPE: short]
#define KEY_ARENA_GAMETYPE_1V1_SINGLE 15  // [TYPE: byte]
#define KEY_ARENA_GAMETYPE_1V1_DOUBLE 16  // [TYPE: byte]
#define KEY_ARENA_GAMETYPE_1V1_ROTATE 17  // [TYPE: byte]
#define KEY_ARENA_GAMETYPE_1V1_TRIPLE 18  // [TYPE: byte]
#define KEY_ARENA_GAMETYPE_1V1_SHOOTER 19  // [TYPE: byte]
#define KEY_CHEATS_COUNTER 20  // [TYPE: int]

///////////////////////////////////////////////////////////////////////////////

// STATS
// Use these stat ID's to query aggregate statistics for your game.

#define DISCONNECTS_COUNTER 3  // [TYPE: int]
#define COMPLETE_MATCHES_COUNTER 4  // [TYPE: int]
#define NUM_SINGLE_WIN_COUNTER 9  // [TYPE: short]
#define NUM_SINGLE_LOSE_COUNTER 10  // [TYPE: short]
#define NUM_DOUBLE_LOSE_COUNTER 11  // [TYPE: short]
#define NUM_DOUBLE_WIN_COUNTER 12  // [TYPE: short]
#define NUM_ROTATE_WIN_COUNTER 13  // [TYPE: short]
#define NUM_ROTATE_LOSE_COUNTER 14  // [TYPE: short]
#define NUM_TRIPLE_WIN_COUNTER 15  // [TYPE: short]
#define NUM_TRIPLE_LOSE_COUNTER 16  // [TYPE: short]
#define NUM_SHOOTER_WIN_COUNTER 17  // [TYPE: short]
#define NUM_SHOOTER_LOSE_COUNTER 18  // [TYPE: short]
#define ARENA_ELO_RATING_1V1_SINGLE 19  // [TYPE: int]
#define ARENA_ELO_RATING_1V1_DOUBLE 20  // [TYPE: int]
#define ARENA_ELO_RATING_1V1_ROTATE 21  // [TYPE: int]
#define ARENA_ELO_RATING_1V1_TRIPLE 22  // [TYPE: int]
#define ARENA_ELO_RATING_1V1_SHOOTER 23  // [TYPE: int]
#define CHEATS_COUNTER 24  // [TYPE: int]


#ifdef __cplusplus
}
#endif

#endif // _ATLAS_SYACHI2DS_V1_H_
