///////////////////////////////////////////////////////////////////////////////
// GameSpy ATLAS Competition System Source File
//
// NOTE: This is an auto-generated file, do not edit this file directly.
///////////////////////////////////////////////////////////////////////////////
#include <gflib.h>
#include "atlas_syachi2ds_v1.h"

int atlas_rule_set_version = 1;

static const char* ATLAS_Field_Name[] = 
{
  "ARENA_ELO_RATING_1V1_DOUBLE",
  "ARENA_ELO_RATING_1V1_ROTATE",
  "ARENA_ELO_RATING_1V1_SHOOTER",
  "ARENA_ELO_RATING_1V1_SINGLE",
  "ARENA_ELO_RATING_1V1_TRIPLE",
  "CHEATS_COUNTER",
  "COMPLETE_MATCHES_COUNTER",
  "DISCONNECTS_COUNTER",
  "NUM_DOUBLE_LOSE_COUNTER",
  "NUM_DOUBLE_WIN_COUNTER",
  "NUM_ROTATE_LOSE_COUNTER",
  "NUM_ROTATE_WIN_COUNTER",
  "NUM_SHOOTER_LOSE_COUNTER",
  "NUM_SHOOTER_WIN_COUNTER",
  "NUM_SINGLE_LOSE_COUNTER",
  "NUM_SINGLE_WIN_COUNTER"  ,
  "NUM_TRIPLE_LOSE_COUNTER",
  "NUM_TRIPLE_WIN_COUNTER",
  "INITIAL_PROFILE_ID",
  "NOW_PROFILE_ID",
};

const char** ATLAS_GetFieldName( void )
{ 
  return ATLAS_Field_Name;
}

u32 ATLAS_GetFieldNameNum( void )
{ 
  return NELEMS( ATLAS_Field_Name );
}

int ATLAS_GET_KEY(char* keyName)
{
   if(!keyName)
      return 0;
   
   if(!GFL_STD_StrCmp("KEY_NUM_SINGLE_WIN_COUNTER", keyName))
      return KEY_NUM_SINGLE_WIN_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_NUM_SINGLE_LOSE_COUNTER", keyName))
      return KEY_NUM_SINGLE_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_NUM_DOUBLE_LOSE_COUNTER", keyName))
      return KEY_NUM_DOUBLE_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_NUM_DOUBLE_WIN_COUNTER", keyName))
      return KEY_NUM_DOUBLE_WIN_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_NUM_ROTATE_WIN_COUNTER", keyName))
      return KEY_NUM_ROTATE_WIN_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_NUM_ROTATE_LOSE_COUNTER", keyName))
      return KEY_NUM_ROTATE_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_NUM_TRIPLE_WIN_COUNTER", keyName))
      return KEY_NUM_TRIPLE_WIN_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_NUM_TRIPLE_LOSE_COUNTER", keyName))
      return KEY_NUM_TRIPLE_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_NUM_SHOOTER_WIN_COUNTER", keyName))
      return KEY_NUM_SHOOTER_WIN_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_NUM_SHOOTER_LOSE_COUNTER", keyName))
      return KEY_NUM_SHOOTER_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("KEY_ARENA_GAMETYPE_1V1_SINGLE", keyName))
      return KEY_ARENA_GAMETYPE_1V1_SINGLE;   
   if(!GFL_STD_StrCmp("KEY_ARENA_GAMETYPE_1V1_DOUBLE", keyName))
      return KEY_ARENA_GAMETYPE_1V1_DOUBLE;   
   if(!GFL_STD_StrCmp("KEY_ARENA_GAMETYPE_1V1_ROTATE", keyName))
      return KEY_ARENA_GAMETYPE_1V1_ROTATE;   
   if(!GFL_STD_StrCmp("KEY_ARENA_GAMETYPE_1V1_TRIPLE", keyName))
      return KEY_ARENA_GAMETYPE_1V1_TRIPLE;   
   if(!GFL_STD_StrCmp("KEY_ARENA_GAMETYPE_1V1_SHOOTER", keyName))
      return KEY_ARENA_GAMETYPE_1V1_SHOOTER;   
   if(!GFL_STD_StrCmp("KEY_CHEATS_COUNTER", keyName))
      return KEY_CHEATS_COUNTER;   
   
   return 0;
}

char* ATLAS_GET_KEY_NAME(int keyId)
{
   if(keyId <= 0)
      return "";
   
   if(keyId == KEY_NUM_SINGLE_WIN_COUNTER)
      return "KEY_NUM_SINGLE_WIN_COUNTER";   
   if(keyId == KEY_NUM_SINGLE_LOSE_COUNTER)
      return "KEY_NUM_SINGLE_LOSE_COUNTER";   
   if(keyId == KEY_NUM_DOUBLE_LOSE_COUNTER)
      return "KEY_NUM_DOUBLE_LOSE_COUNTER";   
   if(keyId == KEY_NUM_DOUBLE_WIN_COUNTER)
      return "KEY_NUM_DOUBLE_WIN_COUNTER";   
   if(keyId == KEY_NUM_ROTATE_WIN_COUNTER)
      return "KEY_NUM_ROTATE_WIN_COUNTER";   
   if(keyId == KEY_NUM_ROTATE_LOSE_COUNTER)
      return "KEY_NUM_ROTATE_LOSE_COUNTER";   
   if(keyId == KEY_NUM_TRIPLE_WIN_COUNTER)
      return "KEY_NUM_TRIPLE_WIN_COUNTER";   
   if(keyId == KEY_NUM_TRIPLE_LOSE_COUNTER)
      return "KEY_NUM_TRIPLE_LOSE_COUNTER";   
   if(keyId == KEY_NUM_SHOOTER_WIN_COUNTER)
      return "KEY_NUM_SHOOTER_WIN_COUNTER";   
   if(keyId == KEY_NUM_SHOOTER_LOSE_COUNTER)
      return "KEY_NUM_SHOOTER_LOSE_COUNTER";   
   if(keyId == KEY_ARENA_GAMETYPE_1V1_SINGLE)
      return "KEY_ARENA_GAMETYPE_1V1_SINGLE";   
   if(keyId == KEY_ARENA_GAMETYPE_1V1_DOUBLE)
      return "KEY_ARENA_GAMETYPE_1V1_DOUBLE";   
   if(keyId == KEY_ARENA_GAMETYPE_1V1_ROTATE)
      return "KEY_ARENA_GAMETYPE_1V1_ROTATE";   
   if(keyId == KEY_ARENA_GAMETYPE_1V1_TRIPLE)
      return "KEY_ARENA_GAMETYPE_1V1_TRIPLE";   
   if(keyId == KEY_ARENA_GAMETYPE_1V1_SHOOTER)
      return "KEY_ARENA_GAMETYPE_1V1_SHOOTER";   
   if(keyId == KEY_CHEATS_COUNTER)
      return "KEY_CHEATS_COUNTER";   
   
   return "";
}

int ATLAS_GET_STAT(char* statName)
{
   if(!statName)
      return 0;
   
   if(!GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_DOUBLE", statName))
      return ARENA_ELO_RATING_1V1_DOUBLE;   
   if(!GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_ROTATE", statName))
      return ARENA_ELO_RATING_1V1_ROTATE;   
   if(!GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_SHOOTER", statName))
      return ARENA_ELO_RATING_1V1_SHOOTER;   
   if(!GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_SINGLE", statName))
      return ARENA_ELO_RATING_1V1_SINGLE;   
   if(!GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_TRIPLE", statName))
      return ARENA_ELO_RATING_1V1_TRIPLE;   
   if(!GFL_STD_StrCmp("CHEATS_COUNTER", statName))
      return CHEATS_COUNTER;   
   if(!GFL_STD_StrCmp("COMPLETE_MATCHES_COUNTER", statName))
      return COMPLETE_MATCHES_COUNTER;   
   if(!GFL_STD_StrCmp("DISCONNECTS_COUNTER", statName))
      return DISCONNECTS_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_DOUBLE_LOSE_COUNTER", statName))
      return NUM_DOUBLE_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_DOUBLE_WIN_COUNTER", statName))
      return NUM_DOUBLE_WIN_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_ROTATE_LOSE_COUNTER", statName))
      return NUM_ROTATE_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_ROTATE_WIN_COUNTER", statName))
      return NUM_ROTATE_WIN_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_SHOOTER_LOSE_COUNTER", statName))
      return NUM_SHOOTER_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_SHOOTER_WIN_COUNTER", statName))
      return NUM_SHOOTER_WIN_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_SINGLE_LOSE_COUNTER", statName))
      return NUM_SINGLE_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_SINGLE_WIN_COUNTER", statName))
      return NUM_SINGLE_WIN_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_TRIPLE_LOSE_COUNTER", statName))
      return NUM_TRIPLE_LOSE_COUNTER;   
   if(!GFL_STD_StrCmp("NUM_TRIPLE_WIN_COUNTER", statName))
      return NUM_TRIPLE_WIN_COUNTER;   
   
   return 0;
}
char* ATLAS_GET_STAT_NAME(int statId)
{
   if(statId <= 0)
      return "";
   
   if(statId == ARENA_ELO_RATING_1V1_DOUBLE)
      return "ARENA_ELO_RATING_1V1_DOUBLE";   
   if(statId == ARENA_ELO_RATING_1V1_ROTATE)
      return "ARENA_ELO_RATING_1V1_ROTATE";   
   if(statId == ARENA_ELO_RATING_1V1_SHOOTER)
      return "ARENA_ELO_RATING_1V1_SHOOTER";   
   if(statId == ARENA_ELO_RATING_1V1_SINGLE)
      return "ARENA_ELO_RATING_1V1_SINGLE";   
   if(statId == ARENA_ELO_RATING_1V1_TRIPLE)
      return "ARENA_ELO_RATING_1V1_TRIPLE";   
   if(statId == CHEATS_COUNTER)
      return "CHEATS_COUNTER";   
   if(statId == COMPLETE_MATCHES_COUNTER)
      return "COMPLETE_MATCHES_COUNTER";   
   if(statId == DISCONNECTS_COUNTER)
      return "DISCONNECTS_COUNTER";   
   if(statId == NUM_DOUBLE_LOSE_COUNTER)
      return "NUM_DOUBLE_LOSE_COUNTER";   
   if(statId == NUM_DOUBLE_WIN_COUNTER)
      return "NUM_DOUBLE_WIN_COUNTER";   
   if(statId == NUM_ROTATE_LOSE_COUNTER)
      return "NUM_ROTATE_LOSE_COUNTER";   
   if(statId == NUM_ROTATE_WIN_COUNTER)
      return "NUM_ROTATE_WIN_COUNTER";   
   if(statId == NUM_SHOOTER_LOSE_COUNTER)
      return "NUM_SHOOTER_LOSE_COUNTER";   
   if(statId == NUM_SHOOTER_WIN_COUNTER)
      return "NUM_SHOOTER_WIN_COUNTER";   
   if(statId == NUM_SINGLE_LOSE_COUNTER)
      return "NUM_SINGLE_LOSE_COUNTER";   
   if(statId == NUM_SINGLE_WIN_COUNTER)
      return "NUM_SINGLE_WIN_COUNTER";   
   if(statId == NUM_TRIPLE_LOSE_COUNTER)
      return "NUM_TRIPLE_LOSE_COUNTER";   
   if(statId == NUM_TRIPLE_WIN_COUNTER)
      return "NUM_TRIPLE_WIN_COUNTER";   
   
   return "";
}

int ATLAS_GET_STAT_PAGE_BY_ID(int statId)
{
   if(statId <= 0)
      return 0;
   

   //PlayerStats
   if(statId == 3 || statId == 4 || statId == 18 || statId == 17 || statId == 16 || statId == 15 || statId == 14 ||
      statId == 13 || statId == 12 || statId == 11 || statId == 10 || statId == 9 || statId == 19 || statId == 20 ||
      statId == 21 || statId == 22 || statId == 23 || statId == 24)
      return 1;   
      
   
   return 0;
}

int ATLAS_GET_STAT_PAGE_BY_NAME(char* statName)
{
   if(!statName)
      return 0;
   

   //PlayerStats
   if(!GFL_STD_StrCmp("DISCONNECTS_COUNTER", statName) || !GFL_STD_StrCmp("COMPLETE_MATCHES_COUNTER", statName) ||
      !GFL_STD_StrCmp("NUM_SHOOTER_LOSE_COUNTER", statName) || !GFL_STD_StrCmp("NUM_SHOOTER_WIN_COUNTER", statName) ||
      !GFL_STD_StrCmp("NUM_TRIPLE_LOSE_COUNTER", statName) || !GFL_STD_StrCmp("NUM_TRIPLE_WIN_COUNTER", statName) ||
      !GFL_STD_StrCmp("NUM_ROTATE_LOSE_COUNTER", statName) || !GFL_STD_StrCmp("NUM_ROTATE_WIN_COUNTER", statName) ||
      !GFL_STD_StrCmp("NUM_DOUBLE_WIN_COUNTER", statName) || !GFL_STD_StrCmp("NUM_DOUBLE_LOSE_COUNTER", statName) ||
      !GFL_STD_StrCmp("NUM_SINGLE_LOSE_COUNTER", statName) || !GFL_STD_StrCmp("NUM_SINGLE_WIN_COUNTER", statName) ||
      !GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_SINGLE", statName) || !GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_DOUBLE", statName) ||
      !GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_ROTATE", statName) || !GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_TRIPLE", statName) ||
      !GFL_STD_StrCmp("ARENA_ELO_RATING_1V1_SHOOTER", statName) || !GFL_STD_StrCmp("CHEATS_COUNTER", statName))
      return 1;   
      
   
   return 0;
}

