///////////////////////////////////////////////////////////////////////////////
// GameSpy ATLAS Competition System Header File
//
// NOTE: This is an auto-generated file, do not edit this file directly.
///////////////////////////////////////////////////////////////////////////////

#ifndef _ATLAS_SYACHI2DS_V1_H_
#define _ATLAS_SYACHI2DS_V1_H_

#ifdef __cplusplus
extern "C" {
#endif

extern int ATLAS_GET_KEY(char* keyName);
extern char* ATLAS_GET_KEY_NAME(int keyId);
extern int ATLAS_GET_STAT(char* statName);
extern char* ATLAS_GET_STAT_NAME(int statId);
extern int ATLAS_GET_STAT_PAGE_BY_ID(int statId);
extern int ATLAS_GET_STAT_PAGE_BY_NAME(char* statName);

#define ATLAS_RULE_SET_VERSION 1

// KEYS
// Use these key ID's to report match data for your game.

#define KEY_ARENA_GAMETYPE_1V1 1  // [TYPE: byte]
#define KEY_NUM_SINGLE_MATCH_COUNTER 2  // [TYPE: int]
#define KEY_ARENA_GAMETYPE_1V1_DOUBLE 3  // [TYPE: byte]
#define ARENA_FFA_PLACE 4  // [TYPE: string]

///////////////////////////////////////////////////////////////////////////////

// STATS
// Use these stat ID's to query aggregate statistics for your game.

#define ARENA_ELO_RATING_1V1 1  // [TYPE: int]
#define ARENA_ELO_RATING_1V1_DOUBLE 7  // [TYPE: int]
#define ARENA_INITIAL_RATING 8  // [TYPE: int]
#define COMPLETE_MATCHES_COUNTER 4  // [TYPE: int]
#define DISCONNECT_RATE 5  // [TYPE: float]
#define DISCONNECTS_COUNTER 3  // [TYPE: int]
#define NUM_SINGLE_MATCH_COUNTER 6  // [TYPE: int]
#define TOTAL_MATCHES_COUNTER 2  // [TYPE: int]


#ifdef __cplusplus
}
#endif

#endif // _ATLAS_SYACHI2DS_V1_H_
