//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 06/12/10.
//-----------------------------------------------------
#define    NANR_gsync_obj_bed    0 // 
#define    NANR_gsync_obj_bed_ani    1 // 
#define    NANR_gsync_obj_kemuri_r    2 // 
#define    NANR_gsync_obj_kemuri_l    3 // 
#define    NANR_gsync_obj_rug_ani1    4 // 
#define    NANR_gsync_obj_rug_ani2    5 // 
#define    NANR_gsync_obj_rug_ani3    6 // é~ÇﬂÇÈà◊ÇÃÉAÉjÉÅ
#define    NANR_gsync_obj_rug_ani4    7 // Ç”Ç∆ÇÒÇ∆Ç—
#define    NANR_gsync_obj_zzz_ani    8 // 
#define    NANR_gsync_obj_yume_1    9 // 
#define    NANR_gsync_obj_musha    10 // 
#define    NANR_gsync_obj_musha_shadow    11 // 
#define    NANR_gsync_obj_bed_shadow    12 // 
