//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 12/06/09.
//-----------------------------------------------------
#define    NANR_gsync_obj_bed    0 // 
#define    NANR_gsync_obj_bed_ani    1 // 
#define    NANR_gsync_obj_kemuri_r    2 // 
#define    NANR_gsync_obj_kemuri_l    3 // 
#define    NANR_gsync_obj_rug_ani1    4 // 
#define    NANR_gsync_obj_rug_ani2    5 // 
#define    NANR_gsync_obj_rug_ani3    6 // 止める為のアニメ
#define    NANR_gsync_obj_rug_ani4    7 // 布団が吹っ飛んだアニメ
#define    NANR_gsync_obj_zzz_ani    8 // 
#define    NANR_gsync_obj_yume_1    9 // 
