//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 03/18/10.
//-----------------------------------------------------
#define    NANR_ir_ani_CellAnime0    0 // 横＿電波相手
#define    NANR_ir_ani_CellAnime1    1 // 横＿電波自分
#define    NANR_ir_ani_CellAnime6    2 // 縦＿電波自分
#define    NANR_ir_ani_CellAnime7    3 // 縦＿電波相手
#define    NANR_ir_ani_CellAnime2    4 // DS1P＿4人通信開始
#define    NANR_ir_ani_CellAnime3    5 // DS2P＿4人通信開始
#define    NANR_ir_ani_CellAnime4    6 // DS3P＿4人通信開始
#define    NANR_ir_ani_CellAnime5    7 // DS4P＿4人通信開始
#define    NANR_ir_ani_CellAnime8    8 // DS1P＿4人通信終了
#define    NANR_ir_ani_CellAnime9    9 // DS3P＿4人通信終了
#define    NANR_ir_ani_CellAnime10    10 // DS1P＿2人通信開始
#define    NANR_ir_ani_CellAnime11    11 // DS3P＿2人通信開始
#define    NANR_ir_ani_CellAnime12    12 // DS1P＿2人通信終了
#define    NANR_ir_ani_CellAnime13    13 // DS3P＿2人通信終了
