//-----------------------------------------------------
// This file was generated by g2dcvtr.exe converter.
// Avoid editting this file.
// creation date ==> 12/09/09.
//-----------------------------------------------------
#define    NANR_ir_ani_CellAnime0    0 // “d”g‘ŠŽè
#define    NANR_ir_ani_CellAnime1    1 // “d”gŽ©•ª
#define    NANR_ir_ani_CellAnime2    2 // DSŽ©•ª
#define    NANR_ir_ani_CellAnime3    3 // DS‘ŠŽè
