copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch.ncg				world_watch.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch.ncl				world_watch.ncl
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch1.nsc              world_watch1.nsc
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch2.nsc              world_watch2.nsc
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch3.nsc              world_watch3.nsc
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch4.nsc              world_watch4.nsc
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch5.nsc              world_watch5.nsc
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch_frame.ncg         world_watch_frame.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch_frame.nsc         world_watch_frame.nsc
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w0anim.ncl				world_w0anim.ncl
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w2anim.ncl				world_w2anim.ncl
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w3anim.ncl				world_w3anim.ncl
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch2a.nsc            world_watch2a.nsc
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch2b.nsc            world_watch2b.nsc
copy ..\\..\\staff\\fujiwara\\world_watch\\world_watch_wall.nsc         world_watch_wall.nsc

copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon.ncl			world_w_balloon.ncl
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon00.ncg		world_w_balloon00.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon00.nce		world_w_balloon00.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon01.ncg		world_w_balloon01.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon01.nce		world_w_balloon01.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon02.ncg		world_w_balloon02.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon02.nce		world_w_balloon02.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon03.ncg		world_w_balloon03.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon03.nce		world_w_balloon03.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon04.ncg		world_w_balloon04.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon04.nce		world_w_balloon04.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon05.ncg		world_w_balloon05.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon05.nce		world_w_balloon05.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon06.ncg		world_w_balloon06.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon06.nce		world_w_balloon06.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon07.ncg		world_w_balloon07.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon07.nce		world_w_balloon07.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon08.ncg		world_w_balloon08.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon08.nce		world_w_balloon08.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon09.ncg		world_w_balloon09.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon09.nce		world_w_balloon09.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon10.ncg		world_w_balloon10.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon10.nce		world_w_balloon10.nce
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon11.ncg		world_w_balloon11.ncg
copy ..\\..\\staff\\fujiwara\\world_watch\\world_w_balloon11.nce		world_w_balloon11.nce

copy ..\\..\\staff\\fujiwara\\wifi_earth\\earth_sphere.imd		wifi_earth.imd
copy ..\\..\\staff\\fujiwara\\wifi_earth\\earth_mark_g.imd		earth_mark_1.imd
copy ..\\..\\staff\\fujiwara\\wifi_earth\\earth_mark_b.imd		earth_mark_2.imd
copy ..\\..\\staff\\fujiwara\\wifi_earth\\earth_mark_r.imd		earth_mark_3.imd
