//============================================================================================
/**
 * @file	tokusyu_def.h
 * @bfief	特性NoのDefine定義ファイル
 * @author	TokuseiConverter
 * 特性コンバータから生成されました
*/
//============================================================================================

#pragma once

#define		TOKUSYU_NULL						( 0 )
#define		TOKUSYU_AKUSYUU							( 1 )		//あくしゅう
#define		TOKUSYU_AMEHURASI						( 2 )		//あめふらし
#define		TOKUSYU_KASOKU							( 3 )		//かそく
#define		TOKUSYU_KABUTOAAMAA					( 4 )		//カブトアーマー
#define		TOKUSYU_GANZYOU							( 5 )		//がんじょう
#define		TOKUSYU_SIMERIKE						( 6 )		//しめりけ
#define		TOKUSYU_ZYUUNAN							( 7 )		//じゅうなん
#define		TOKUSYU_SUNAGAKURE					( 8 )		//すながくれ
#define		TOKUSYU_SEIDENKI						( 9 )		//せいでんき
#define		TOKUSYU_TIKUDEN							( 10 )		//ちくでん
#define		TOKUSYU_TYOSUI							( 11 )		//ちょすい
#define		TOKUSYU_DONKAN							( 12 )		//どんかん
#define		TOKUSYU_NOOTENKI						( 13 )		//ノーてんき
#define		TOKUSYU_HUKUGAN							( 14 )		//ふくがん
#define		TOKUSYU_HUMIN								( 15 )		//ふみん
#define		TOKUSYU_HENSYOKU						( 16 )		//へんしょく
#define		TOKUSYU_MENEKI							( 17 )		//めんえき
#define		TOKUSYU_MORAIBI							( 18 )		//もらいび
#define		TOKUSYU_RINPUN							( 19 )		//りんぷん
#define		TOKUSYU_MAIPEESU						( 20 )		//マイペース
#define		TOKUSYU_KYUUBAN							( 21 )		//きゅうばん
#define		TOKUSYU_IKAKU								( 22 )		//いかく
#define		TOKUSYU_KAGEHUMI						( 23 )		//かげふみ
#define		TOKUSYU_SAMEHADA						( 24 )		//さめはだ
#define		TOKUSYU_HUSIGINAMAMORI			( 25 )		//ふしぎなまもり
#define		TOKUSYU_HUYUU								( 26 )		//ふゆう
#define		TOKUSYU_HOUSI								( 27 )		//ほうし
#define		TOKUSYU_SINKURO							( 28 )		//シンクロ
#define		TOKUSYU_KURIABODHI					( 29 )		//クリアボディ
#define		TOKUSYU_SIZENKAIHUKU				( 30 )		//しぜんかいふく
#define		TOKUSYU_HIRAISIN						( 31 )		//ひらいしん
#define		TOKUSYU_TENNOMEGUMI					( 32 )		//てんのめぐみ
#define		TOKUSYU_SUISUI							( 33 )		//すいすい
#define		TOKUSYU_YOURYOKUSO					( 34 )		//ようりょくそ
#define		TOKUSYU_HAKKOU							( 35 )		//はっこう
#define		TOKUSYU_TOREESU							( 36 )		//トレース
#define		TOKUSYU_TIKARAMOTI					( 37 )		//ちからもち
#define		TOKUSYU_DOKUNOTOGE					( 38 )		//どくのトゲ
#define		TOKUSYU_SEISINRYOKU					( 39 )		//せいしんりょく
#define		TOKUSYU_MAGUMANOYOROI				( 40 )		//マグマのよろい
#define		TOKUSYU_MIZUNOBEERU					( 41 )		//みずのベール
#define		TOKUSYU_ZIRYOKU							( 42 )		//じりょく
#define		TOKUSYU_BOUON								( 43 )		//ぼうおん
#define		TOKUSYU_AMEUKEZARA					( 44 )		//あめうけざら
#define		TOKUSYU_SUNAOKOSI						( 45 )		//すなおこし
#define		TOKUSYU_PURESSYAA						( 46 )		//プレッシャー
#define		TOKUSYU_ATUISIBOU						( 47 )		//あついしぼう
#define		TOKUSYU_HAYAOKI							( 48 )		//はやおき
#define		TOKUSYU_HONOONOKARADA				( 49 )		//ほのおのからだ
#define		TOKUSYU_NIGEASI							( 50 )		//にげあし
#define		TOKUSYU_SURUDOIME						( 51 )		//するどいめ
#define		TOKUSYU_KAIRIKIBASAMI				( 52 )		//かいりきバサミ
#define		TOKUSYU_MONOHIROI						( 53 )		//ものひろい
#define		TOKUSYU_NAMAKE							( 54 )		//なまけ
#define		TOKUSYU_HARIKIRI						( 55 )		//はりきり
#define		TOKUSYU_MEROMEROBODHI				( 56 )		//メロメロボディ
#define		TOKUSYU_PURASU							( 57 )		//プラス
#define		TOKUSYU_MAINASU							( 58 )		//マイナス
#define		TOKUSYU_TENKIYA							( 59 )		//てんきや
#define		TOKUSYU_NENTYAKU						( 60 )		//ねんちゃく
#define		TOKUSYU_DAPPI								( 61 )		//だっぴ
#define		TOKUSYU_KONZYOU							( 62 )		//こんじょう
#define		TOKUSYU_HUSIGINAUROKO				( 63 )		//ふしぎなうろこ
#define		TOKUSYU_HEDOROEKI						( 64 )		//ヘドロえき
#define		TOKUSYU_SINRYOKU						( 65 )		//しんりょく
#define		TOKUSYU_MOUKA								( 66 )		//もうか
#define		TOKUSYU_GEKIRYUU						( 67 )		//げきりゅう
#define		TOKUSYU_MUSINOSIRASE				( 68 )		//むしのしらせ
#define		TOKUSYU_ISIATAMA						( 69 )		//いしあたま
#define		TOKUSYU_HIDERI							( 70 )		//ひでり
#define		TOKUSYU_ARIZIGOKU						( 71 )		//ありじごく
#define		TOKUSYU_YARUKI							( 72 )		//やるき
#define		TOKUSYU_SIROIKEMURI					( 73 )		//しろいけむり
#define		TOKUSYU_YOGAPAWAA						( 74 )		//ヨガパワー
#define		TOKUSYU_SHERUAAMAA					( 75 )		//シェルアーマー
#define		TOKUSYU_EAROKKU							( 76 )		//エアロック
#define		TOKUSYU_TIDORIASI						( 77 )		//ちどりあし
#define		TOKUSYU_DENKIENZIN					( 78 )		//でんきエンジン
#define		TOKUSYU_TOUSOUSIN						( 79 )		//とうそうしん
#define		TOKUSYU_HUKUTUNOKOKORO			( 80 )		//ふくつのこころ
#define		TOKUSYU_YUKIGAKURE					( 81 )		//ゆきがくれ
#define		TOKUSYU_KUISINBOU						( 82 )		//くいしんぼう
#define		TOKUSYU_IKARINOTUBO					( 83 )		//いかりのつぼ
#define		TOKUSYU_KARUWAZA						( 84 )		//かるわざ
#define		TOKUSYU_TAINETU							( 85 )		//たいねつ
#define		TOKUSYU_TANZYUN							( 86 )		//たんじゅん
#define		TOKUSYU_KANSOUHADA					( 87 )		//かんそうはだ
#define		TOKUSYU_DAUNROODO						( 88 )		//ダウンロード
#define		TOKUSYU_TETUNOKOBUSI				( 89 )		//てつのこぶし
#define		TOKUSYU_POIZUNHIIRU					( 90 )		//ポイズンヒール
#define		TOKUSYU_TEKIOURYOKU					( 91 )		//てきおうりょく
#define		TOKUSYU_SUKIRURINKU					( 92 )		//スキルリンク
#define		TOKUSYU_URUOIBODHI					( 93 )		//うるおいボディ
#define		TOKUSYU_SANPAWAA						( 94 )		//サンパワー
#define		TOKUSYU_HAYAASI							( 95 )		//はやあし
#define		TOKUSYU_NOOMARUSUKIN				( 96 )		//ノーマルスキン
#define		TOKUSYU_SUNAIPAA						( 97 )		//スナイパー
#define		TOKUSYU_MAZIKKUGAADO				( 98 )		//マジックガード
#define		TOKUSYU_NOOGAADO						( 99 )		//ノーガード
#define		TOKUSYU_ATODASI							( 100 )		//あとだし
#define		TOKUSYU_TEKUNISYAN					( 101 )		//テクニシャン
#define		TOKUSYU_RIIHUGAADO					( 102 )		//リーフガード
#define		TOKUSYU_BUKIYOU							( 103 )		//ぶきよう
#define		TOKUSYU_KATAYABURI					( 104 )		//かたやぶり
#define		TOKUSYU_KYOUUN							( 105 )		//きょううん
#define		TOKUSYU_YUUBAKU							( 106 )		//ゆうばく
#define		TOKUSYU_KIKENYOTI						( 107 )		//きけんよち
#define		TOKUSYU_YOTIMU							( 108 )		//よちむ
#define		TOKUSYU_TENNEN							( 109 )		//てんねん
#define		TOKUSYU_IROMEGANE						( 110 )		//いろめがね
#define		TOKUSYU_FIRUTAA							( 111 )		//フィルター
#define		TOKUSYU_SUROOSUTAATO				( 112 )		//スロースタート
#define		TOKUSYU_KIMOTTAMA						( 113 )		//きもったま
#define		TOKUSYU_YOBIMIZU						( 114 )		//よびみず
#define		TOKUSYU_AISUBODHI						( 115 )		//アイスボディ
#define		TOKUSYU_HAADOROKKU					( 116 )		//ハードロック
#define		TOKUSYU_YUKIHURASI					( 117 )		//ゆきふらし
#define		TOKUSYU_MITUATUME						( 118 )		//みつあつめ
#define		TOKUSYU_OMITOOSI						( 119 )		//おみとおし
#define		TOKUSYU_SUTEMI							( 120 )		//すてみ
#define		TOKUSYU_MARUTITAIPU					( 121 )		//マルチタイプ
#define		TOKUSYU_HURAWAAGIHUTO				( 122 )		//フラワーギフト
#define		TOKUSYU_NAITOMEA						( 123 )		//ナイトメア
#define		TOKUSYU_WARUITEGUSE					( 124 )		//わるいてぐせ
#define		TOKUSYU_TIKARADUKU					( 125 )		//ちからづく
#define		TOKUSYU_AMANOZYAKU					( 126 )		//あまのじゃく
#define		TOKUSYU_KINTYOUKAN					( 127 )		//きんちょうかん
#define		TOKUSYU_MAKENKI							( 128 )		//まけんき
#define		TOKUSYU_YOWAKI							( 129 )		//よわき
#define		TOKUSYU_NOROWAREBODHI				( 130 )		//のろわれボディ
#define		TOKUSYU_MORATERAPII					( 131 )		//モラテラピー
#define		TOKUSYU_HURENDOGAADO				( 132 )		//フレンドガード
#define		TOKUSYU_KUDAKERUYOROI				( 133 )		//くだけるよろい
#define		TOKUSYU_HHIMETARU						( 134 )		//ヘヴィメタル
#define		TOKUSYU_RAITOMETARU					( 135 )		//ライトメタル
#define		TOKUSYU_MARUTISUKEIRU				( 136 )		//マルチスケイル
#define		TOKUSYU_DOKUBOUSOU					( 137 )		//どくぼうそう
#define		TOKUSYU_NETUBOUSOU					( 138 )		//ねつぼうそう
#define		TOKUSYU_SYUUKAKU						( 139 )		//しゅうかく
#define		TOKUSYU_AUNNOIKI						( 140 )		//あうんのいき
#define		TOKUSYU_MURAKKE							( 141 )		//ムラっけ
#define		TOKUSYU_BOUZIN							( 142 )		//ぼうじん
#define		TOKUSYU_DOKUSYU							( 143 )		//どくしゅ
#define		TOKUSYU_SAISEIRYOKU					( 144 )		//さいせいりょく
#define		TOKUSYU_HATOMUNE						( 145 )		//はとむね
#define		TOKUSYU_SUNAKAKI						( 146 )		//すなかき
#define		TOKUSYU_MIRAKURUSUKIN				( 147 )		//ミラクルスキン
#define		TOKUSYU_SINUTI							( 148 )		//しんうち
#define		TOKUSYU_IRYUUZYON						( 149 )		//イリュージョン
#define		TOKUSYU_HENSIN							( 150 )		//へんしん
#define		TOKUSYU_SURINUKE						( 151 )		//すりぬけ
#define		TOKUSYU_MIIRA								( 152 )		//ミイラ
#define		TOKUSYU_ZISINKAZYOU					( 153 )		//じしんかじょう
#define		TOKUSYU_SEIGINOKOKORO				( 154 )		//せいぎのこころ
#define		TOKUSYU_BIBIRI							( 155 )		//びびり
#define		TOKUSYU_MAZIKKUMIRAA				( 156 )		//マジックミラー
#define		TOKUSYU_SOUSYOKU						( 157 )		//そうしょく
#define		TOKUSYU_ITAZURAGOKORO				( 158 )		//いたずらごころ
#define		TOKUSYU_SUNANOTIKARA				( 159 )		//すなのちから
#define		TOKUSYU_MAX						( 159 )
