#! make -f
#----------------------------------------------------------------------------
SUBDIRS		=	

#----------------------------------------------------------------------------

SRCS		=	main.c data.c draw.c\
				irc.c

TARGET_BIN	=	main.srl

#SRCDIR		=	# using default
#LCFILE		=	# using default

include	$(NITROSDK_ROOT)/build/buildtools/commondefs

#----------------------------------------------------------------------------

do-build:		$(TARGETS)

include	$(NITROSDK_ROOT)/build/buildtools/modulerules


#===== End of Makefile =====
