#pragma once
// out put rail_conv.pl
// rail line name
#define LINE_GROUND2 (0)
#define LINE_SLOPE1 (1)
#define LINE_GROUND1 (2)
#define div_3_RE_LINE_0 (3)
#define LINE_SLOPE2 (4)
#define div_5_RE_LINE_0 (5)
#define LINE_SLOPE3 (6)
#define LINE_C2 (7)
#define LINE_CMREND (8)
#define LINE_SLOPE4 (9)
#define div_10_RE_LINE_0 (10)
#define LINE_SLOPE5 (11)
#define div_12_RE_LINE_0 (12)
#define LINE_SLOPE6 (13)
#define div_14_div_7_RE_LINE_0 (14)
#define LINE_CENTER (15)
#define LINE_CMRST (16)
