#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "sp4.y".
#

require 'racc/parser'


#
#	ポケモン用スクリプトコンパイラ
#


module PmScript

  class Parser < Racc::Parser

module_eval <<'..end sp4.y modeval..id1ce3cc8ac7', 'sp4.y', 533

def initialize
end

#予約語定義
RESERVED = {
	'IF'	=> :IF,
	'THEN'	=> :THEN,
	'ELSE'	=> :ELSE,
	'ELSIF'	=> :ELSIF,
	'ENDIF'	=> :ENDIF,
	'DEFVAR'	=> :DEFVAR,
	'DEFFUNC'	=> :DEFFUNC,
	'FLAG_ON'	=> :FLAG_ON,
	'FLAG_OFF'	=> :FLAG_OFF,
  'EVENT_START' => :EVENT_START,
  'EVENT_END' => :EVENT_END,
  'SWITCH' => :SWITCH,
  'CASE' => :CASE,
  'ENDSWITCH' => :ENDSWITCH,
  'WHILE' => :WHILE,
  'ENDWHILE' => :ENDWHILE
};

#予約型定義
RESERVED_TYPE = {
	'LWORK'	=> :LWORK,
	'LABEL' => :LABEL_TYPE,
};

def parse( f )
	@q = []
	@nowlineno = 1
	@incomment = false
	f.each do |line_org|
		line = line_org.strip
		until line.empty? do
			if @incomment == true then
				if line =~ /.*\*\// then
					@incomment = false
					pushq [ :COMMENT, $&]
					line = $'
				else
					pushq [ :COMMENT, line]
					line = ""
				end
			else
				case line
				when /\A\s+/
					;
				when /\A\/\/.*$/
          #Ｃ＋＋形式コメント定義
					pushq [ :COMMENT, $& ]

				when /^\s*$/, /\A\#.*/
          #アセンブラコメント定義
					pushq [ :COMMENT, $&]

				when /\A\/\*.*\*\//
          #Ｃ形式コメント定義
					pushq [ :COMMENT, $&]

				when /\A\.[a-zA-Z_]+.*$/
          #アセンブラマクロ定義
					pushq [ :MACRO, $& ]

				when /\A[a-zA-Z_][a-zA-Z0-9_]*:/
          #アセンブララベル定義
					pushq [ :LABEL, $& ]

				when /\A_[A-Z0-9][a-zA-Z0-9_]*/
          #スクリプトコマンド定義（＿で開始する）
					pushq [ :COMMAND, $& ]

				when /\A0x[0-9a-fA-F]+/, /\A\d+/
          #数値定義（0xで始まる１６進数、あるいは１０進数）
					pushq [ :NUMBER, $& ]

				when /\A\$[a-zA-Z][a-zA-Z0-9_]*/
          #変数定義（＄で始まる）
					pushq [ :VARREF, $& ]

				when /\A[a-zA-Z_][a-zA-Z0-9_]*/
          #識別子定義あるいは型定義
					if RESERVED.has_key? $& then
						pushq [ RESERVED[$&], $&.intern ]
					elsif RESERVED_TYPE.has_key? $& then
						pushq [ :TYPE, $&.intern ]
					else
						pushq [ :IDENT, $& ]
					end

				when /\A\\[a-zA-Z_][a-zA-Z0-9_]*/
          # \から始まる識別子はアセンブラマクロパラメータ
					pushq [ :MACPARAM, $& ]

				when /\A==/,/\A!=/,/\A\<=/,/\A\>=/,/\A>/,/\A</,/\A\&\&/,/\A\|\|/
          # 比較演算子
					pushq [ $&, $& ]

				when /\A\/\*.*/
          #C形式コメント開始
					pushq [ :COMMENT, $& ]
					@incomment = true

				when /\A[\+\-\*\/=(){},]/
          #演算子、カッコなどの記号
					pushq [ $&, $& ]
				else
					raise RuntimeError, "#{@fname}:#{@nowlineno}: fatal error! \{#{line_org}\}"
				end
				line = $'
				printf( "\#NOW LINE(%4d) #{line}\n", @nowlineno)
			end
		end
		pushq [ :EOL, nil ]
		@nowlineno += 1
	end
	pushq [ false, nil ]
	
	@yydebug = true
	do_parse
end

def next_token
	value = @q.shift
	@lineno = value.last
	value.delete_at(2)
	value
end

def pushq value
	value << @nowlineno
	@q.push value
end


def on_error( t, v, values )
    if v then
      line = v[0]
      v = v[1]
    else
      line = 'last'
    end
    raise Racc::ParseError, "#{@fname}:#{@lineno}: syntax error on #{v.inspect}"
  end


..end sp4.y modeval..id1ce3cc8ac7

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 48, :_reduce_1,
 0, 49, :_reduce_2,
 3, 49, :_reduce_3,
 2, 49, :_reduce_4,
 2, 49, :_reduce_none,
 4, 49, :_reduce_6,
 3, 49, :_reduce_7,
 4, 49, :_reduce_8,
 0, 53, :_reduce_9,
 2, 53, :_reduce_none,
 3, 53, :_reduce_11,
 3, 54, :_reduce_12,
 8, 55, :_reduce_13,
 7, 55, :_reduce_14,
 1, 56, :_reduce_15,
 3, 56, :_reduce_16,
 4, 51, :_reduce_17,
 1, 51, :_reduce_none,
 2, 57, :_reduce_none,
 3, 57, :_reduce_none,
 2, 58, :_reduce_none,
 3, 58, :_reduce_none,
 1, 50, :_reduce_23,
 1, 50, :_reduce_24,
 1, 50, :_reduce_25,
 1, 50, :_reduce_26,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 3, 62, :_reduce_32,
 4, 62, :_reduce_33,
 6, 62, :_reduce_34,
 5, 62, :_reduce_35,
 1, 52, :_reduce_36,
 2, 52, :_reduce_37,
 6, 60, :_reduce_38,
 0, 67, :_reduce_39,
 2, 67, :_reduce_40,
 5, 67, :_reduce_41,
 3, 66, :_reduce_42,
 3, 66, :_reduce_43,
 4, 66, :_reduce_44,
 4, 66, :_reduce_45,
 4, 66, :_reduce_46,
 4, 66, :_reduce_47,
 3, 66, :_reduce_48,
 3, 66, :_reduce_49,
 1, 68, :_reduce_50,
 1, 68, :_reduce_51,
 1, 68, :_reduce_52,
 1, 68, :_reduce_53,
 1, 68, :_reduce_54,
 1, 68, :_reduce_55,
 1, 68, :_reduce_56,
 1, 68, :_reduce_57,
 5, 64, :_reduce_58,
 5, 63, :_reduce_59,
 0, 70, :_reduce_60,
 1, 70, :_reduce_61,
 2, 70, :_reduce_62,
 4, 71, :_reduce_63,
 3, 61, :_reduce_64,
 3, 61, :_reduce_65,
 3, 61, :_reduce_66,
 2, 59, :_reduce_67,
 4, 59, :_reduce_68,
 3, 59, :_reduce_69,
 2, 59, :_reduce_70,
 1, 59, :_reduce_71,
 1, 69, :_reduce_none,
 3, 69, :_reduce_73,
 3, 69, :_reduce_74,
 3, 69, :_reduce_75,
 3, 69, :_reduce_76,
 3, 69, :_reduce_77,
 1, 72, :_reduce_none,
 1, 72, :_reduce_none,
 1, 72, :_reduce_none,
 1, 73, :_reduce_none,
 1, 73, :_reduce_none,
 1, 65, :_reduce_83,
 3, 65, :_reduce_84 ]

racc_reduce_n = 85

racc_shift_n = 161

racc_action_table = [
     9,    86,    58,    16,    21,    49,    90,    28,   131,     6,
   145,     8,    12,    14,   103,    19,    23,    55,   104,   139,
   140,    55,   105,    10,     9,    15,   106,    16,    21,    27,
     4,    28,   116,     6,    86,     8,    12,    14,   132,    19,
    23,    42,   147,    83,   146,    46,   129,    10,     9,    15,
   126,    16,    21,    27,     4,    28,   152,     6,    86,     8,
    12,    14,    21,    19,    23,    19,   121,     6,    86,    39,
    40,    10,     9,    15,    52,    16,    21,    27,     4,    28,
    57,     6,    98,     8,    12,    14,   125,    19,    23,    42,
   124,    83,   130,    46,   122,    10,     9,    15,    63,    16,
    21,    27,     4,    28,    48,     6,   100,     8,    12,    14,
    74,    19,    23,    55,    97,   144,    56,    39,    40,    10,
     9,    15,   148,    16,    21,    27,     4,    28,    75,     6,
    55,     8,    12,    14,   151,    19,    23,    42,    30,    83,
    84,    46,   120,    10,   128,    15,   154,    50,     9,    27,
     4,    16,    21,    19,    42,    28,    45,     6,    46,     8,
    12,    14,    19,    19,    23,    39,    40,   139,   140,   155,
    54,    10,    42,    15,    83,   142,    46,    27,     4,    42,
    91,    83,    39,    40,    42,    55,    83,    88,    46,    42,
    21,    83,   134,   120,    94,     6,    19,    42,    96,    83,
    39,    40,    42,    87,    83,   137,   138,    39,    40,    42,
    29,    83,    39,    40,    59,    60,    86,    39,    40,    95,
    78,    79,    39,    40,     3,    39,    40,    78,    79,   nil,
    39,    40,    42,   nil,    83,   nil,   109,    39,    40,    69,
    70,    71,    72,    73,    64,    65,    66,    69,    70,    71,
    72,    73,    64,    65,    66,    78,    79,    80,    81,   nil,
    39,    40,   nil,   nil,   157,    78,    79,    80,    81,    37,
   nil,    38,    92,   114,    37,   nil,    38,    37,   nil,    38,
    37,   nil,    38,   114,   nil,    35,    36,    37,   nil,    38,
    35,    36,   nil,    35,    36,   nil,    35,    36,    78,    79,
    80,    81,   nil,    35,    36,    69,    70,    71,    72,    73,
    64,    65,    66,    78,    79,    80,    81,   nil,   nil,   107,
    69,    70,    71,    72,    73,    64,    65,    66,    68,    69,
    70,    71,    72,    73,    64,    65,    66,    69,    70,    71,
    72,    73,    64,    65,    66 ]

racc_action_check = [
   159,   135,    31,   159,   159,    16,    51,   159,   105,   159,
   135,   159,   159,   159,    74,   159,   159,    31,    74,   159,
   159,    51,    75,   159,     2,   159,    75,     2,     2,   159,
   159,     2,    85,     2,    85,     2,     2,     2,   106,     2,
     2,    86,   136,    86,   136,    86,   103,     2,   153,     2,
    98,   153,   153,     2,     2,   153,   143,   153,   143,   153,
   153,   153,   148,   153,   153,    98,    89,   148,    89,    86,
    86,   153,    61,   153,    21,    61,    61,   153,   153,    61,
    28,    61,    61,    61,    61,    61,    97,    61,    61,   120,
    94,   120,   104,   120,    91,    61,   149,    61,    33,   149,
   149,    61,    61,   149,    15,   149,    62,   149,   149,   149,
    35,   149,   149,    33,    60,   127,    27,   120,   120,   149,
   102,   149,   137,   102,   102,   149,   149,   102,    36,   102,
   127,   102,   102,   102,   141,   102,   102,    45,     6,    45,
    45,    45,    87,   102,   102,   102,   146,    18,   123,   102,
   102,   123,   123,     6,    12,   123,    12,   123,    12,   123,
   123,   123,    18,   123,   123,    45,    45,   123,   123,   147,
    25,   123,   124,   123,   124,   124,   124,   123,   123,    83,
    52,    83,    12,    12,    49,    25,    49,    49,    49,    81,
   155,    81,   118,   118,    57,   155,     9,    79,    57,    79,
   124,   124,    78,    48,    78,   122,   122,    83,    83,    80,
     3,    80,    49,    49,    32,    32,    47,    81,    81,    57,
   112,   112,    57,    57,     1,    79,    79,   113,   113,   nil,
    78,    78,    77,   nil,    77,   nil,    77,    80,    80,   150,
   150,   150,   150,   150,   150,   150,   150,    53,    53,    53,
    53,    53,    53,    53,    53,    82,    82,    82,    82,   nil,
    77,    77,   nil,   nil,   150,   115,   115,   115,   115,    67,
   nil,    67,    53,    82,    23,   nil,    23,    10,   nil,    10,
   140,   nil,   140,   115,   nil,    67,    67,    37,   nil,    37,
    23,    23,   nil,    10,    10,   nil,   140,   140,    41,    41,
    41,    41,   nil,    37,    37,    76,    76,    76,    76,    76,
    76,    76,    76,   108,   108,   108,   108,   nil,   nil,    76,
    34,    34,    34,    34,    34,    34,    34,    34,    34,    38,
    38,    38,    38,    38,    38,    38,    38,   101,   101,   101,
   101,   101,   101,   101,   101 ]

racc_action_pointer = [
   nil,   224,    10,   210,   nil,   nil,   124,   nil,   nil,   167,
   258,   nil,   137,   nil,   nil,    83,   -14,   nil,   133,   nil,
   nil,    58,   nil,   255,   nil,   156,   nil,    99,    52,   nil,
   nil,   -12,   200,    84,   314,    91,   109,   268,   323,   nil,
   nil,   296,   nil,   nil,   nil,   120,   nil,   194,   189,   167,
   nil,    -8,   163,   241,   nil,   nil,   nil,   177,   nil,   nil,
    98,    58,    92,   nil,   nil,   nil,   nil,   250,   nil,   nil,
   nil,   nil,   nil,   nil,    -3,     5,   299,   215,   185,   180,
   192,   172,   253,   162,   nil,    12,    24,   101,   nil,    46,
   nil,    75,   nil,   nil,    71,   nil,   nil,    69,    36,   nil,
   nil,   331,   106,    26,    72,   -12,    18,   nil,   311,   nil,
   nil,   nil,   218,   225,   nil,   263,   nil,   nil,   152,   nil,
    72,   nil,   185,   134,   155,   nil,   nil,   101,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   -21,    22,   108,   nil,   nil,
   261,   102,   nil,    36,   nil,   nil,   125,   155,    44,    82,
   233,   nil,   nil,    34,   nil,   172,   nil,   nil,   nil,   -14,
   nil ]

racc_action_default = [
    -2,   -85,    -1,   -85,   -71,   -18,   -85,    -9,   -23,    -5,
   -85,   -25,   -24,   -27,   -26,   -85,   -85,   -28,   -85,   -36,
   -29,   -85,    -4,   -85,   -30,   -85,   -31,   -85,   -85,   161,
   -19,   -85,    -2,   -85,   -85,   -85,   -85,   -85,   -85,   -78,
   -80,   -81,   -79,   -72,   -83,   -85,   -82,   -67,   -85,   -85,
    -3,   -85,   -85,   -85,    -7,   -37,   -70,   -85,   -20,   -10,
   -85,   -85,   -85,    -8,   -54,   -56,   -57,   -85,    -2,   -50,
   -51,   -53,   -52,   -55,   -85,   -85,   -85,   -85,   -85,   -85,
   -85,   -85,   -81,   -85,   -69,   -85,   -85,   -60,   -32,   -85,
    -6,   -85,    -2,   -65,   -79,   -66,   -64,   -85,   -85,   -17,
   -11,   -49,   -85,   -85,   -85,   -85,   -85,   -48,   -42,   -43,
   -75,   -76,   -74,   -73,   -77,   -85,   -68,   -84,   -85,   -61,
   -85,   -33,   -85,   -39,   -85,   -12,   -21,   -85,   -58,   -44,
   -45,   -46,   -47,   -62,   -59,   -85,   -85,   -85,   -15,    -2,
   -85,   -85,   -35,   -85,   -22,    -2,   -85,   -85,   -85,   -40,
   -85,   -38,   -34,   -63,   -16,   -85,   -14,    -2,   -13,   -39,
   -41 ]

racc_goto_table = [
     2,    34,    47,    31,   156,   119,    33,     1,    82,   141,
    99,   158,   136,    77,    53,    51,    62,   118,    32,    93,
   117,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    76,   nil,
   nil,   nil,    61,   nil,   nil,    85,   133,   nil,   nil,    89,
   108,   110,   111,   112,   113,   160,   115,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   101,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   102,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   123,   nil,   nil,   127,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   135,   nil,   nil,   nil,   143,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   150,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   149,
   nil,   nil,   nil,   nil,   nil,   153,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   159 ]

racc_goto_check = [
     2,    19,    18,     5,     4,    24,     5,     1,    22,    20,
    11,     4,     9,    21,    19,     5,     7,    23,     6,    25,
    26,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    19,   nil,
   nil,   nil,     2,   nil,   nil,    18,    24,   nil,   nil,    18,
    22,    22,    22,    22,    22,    20,    22,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    19,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     2,   nil,   nil,     5,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    18,   nil,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    19,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,
   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     7,     0,   nil,  -144,    -3,    11,   -16,   nil,  -110,
   nil,   -51,   nil,   nil,   nil,   nil,   nil,   nil,   -10,    -9,
  -114,   -25,   -37,   -70,   -82,   -38,   -66 ]

racc_goto_default = [
   nil,   nil,   nil,    18,    22,    25,   nil,   nil,     5,   nil,
     7,   nil,    11,    13,    17,    20,    24,    26,   nil,   nil,
   nil,    67,    41,   nil,   nil,    43,    44 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 "/" => 2,
 "*" => 3,
 "-" => 4,
 "+" => 5,
 "==" => 6,
 "!=" => 7,
 "<" => 8,
 ">" => 9,
 "<=" => 10,
 ">=" => 11,
 "&&" => 12,
 "||" => 13,
 :EOL => 14,
 :DEFVAR => 15,
 :TYPE => 16,
 :IDENT => 17,
 :DEFFUNC => 18,
 "(" => 19,
 ")" => 20,
 :VARREF => 21,
 "," => 22,
 "{" => 23,
 "}" => 24,
 :LABEL => 25,
 :COMMAND => 26,
 :MACRO => 27,
 "=" => 28,
 :COMMENT => 29,
 :IF => 30,
 :THEN => 31,
 :ENDIF => 32,
 :ELSE => 33,
 :ELSIF => 34,
 :FLAG_ON => 35,
 :FLAG_OFF => 36,
 :WHILE => 37,
 :ENDWHILE => 38,
 :SWITCH => 39,
 :ENDSWITCH => 40,
 :CASE => 41,
 :funcall => 42,
 :EVENT_START => 43,
 :EVENT_END => 44,
 :NUMBER => 45,
 :MACPARAM => 46 }

racc_use_result_var = true

racc_nt_base = 47

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'"/"',
'"*"',
'"-"',
'"+"',
'"=="',
'"!="',
'"<"',
'">"',
'"<="',
'">="',
'"&&"',
'"||"',
'EOL',
'DEFVAR',
'TYPE',
'IDENT',
'DEFFUNC',
'"("',
'")"',
'VARREF',
'","',
'"{"',
'"}"',
'LABEL',
'COMMAND',
'MACRO',
'"="',
'COMMENT',
'IF',
'THEN',
'ENDIF',
'ELSE',
'ELSIF',
'FLAG_ON',
'FLAG_OFF',
'WHILE',
'ENDWHILE',
'SWITCH',
'ENDSWITCH',
'CASE',
'funcall',
'EVENT_START',
'EVENT_END',
'NUMBER',
'MACPARAM',
'$start',
'program',
'stmt_list',
'stmt',
'stmt_block',
'comments',
'defvar_list',
'def_var',
'def_func',
'param',
'block_start',
'block_end',
'cmd',
'if_stmt',
'assign',
'callfunc',
'switch_stmt',
'while_stmt',
'args',
'cmp_expr',
'else_stmt',
'cmp_ident',
'expr',
'case_stmt_list',
'case_stmt',
'primary',
'arg']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'sp4.y', 45
  def _reduce_1( val, _values, result )
						result = RootNode.new( val[0] )
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 60
  def _reduce_2( val, _values, result )
						result = []
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 64
  def _reduce_3( val, _values, result )
						result.push val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 68
  def _reduce_4( val, _values, result )
						result.push val[1]
   result
  end
.,.,

 # reduce 5 omitted

module_eval <<'.,.,', 'sp4.y', 74
  def _reduce_6( val, _values, result )
						result.push val[1]
						#result.push RawNode.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 78
  def _reduce_7( val, _values, result )
						#result.push RawNode.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 82
  def _reduce_8( val, _values, result )
						#result.push RawNode.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 94
  def _reduce_9( val, _values, result )
						result = []
   result
  end
.,.,

 # reduce 10 omitted

module_eval <<'.,.,', 'sp4.y', 99
  def _reduce_11( val, _values, result )
						result.push val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 108
  def _reduce_12( val, _values, result )
						result = DefVarNode.new(val[1], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 118
  def _reduce_13( val, _values, result )
						result = DefFuncNode.new( val[1], val[2], val[4], val[7] )
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 122
  def _reduce_14( val, _values, result )
						result = DefFuncNode.new( val[1], val[2], nil, val[6] )
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 132
  def _reduce_15( val, _values, result )
						result = val
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 136
  def _reduce_16( val, _values, result )
						result.push val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 145
  def _reduce_17( val, _values, result )
						result = BlockNode.new(val[1], val[2])
   result
  end
.,.,

 # reduce 18 omitted

 # reduce 19 omitted

 # reduce 20 omitted

 # reduce 21 omitted

 # reduce 22 omitted

module_eval <<'.,.,', 'sp4.y', 177
  def _reduce_23( val, _values, result )
						result = RawNode.new(val[0]);
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 181
  def _reduce_24( val, _values, result )
						result = CmdNode.new( val, nil )
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 185
  def _reduce_25( val, _values, result )
						result = CmdNode.new( val[0].shift, val[0] )
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 189
  def _reduce_26( val, _values, result )
						result = RawNode.new(val[0]);
   result
  end
.,.,

 # reduce 27 omitted

 # reduce 28 omitted

 # reduce 29 omitted

 # reduce 30 omitted

 # reduce 31 omitted

module_eval <<'.,.,', 'sp4.y', 210
  def _reduce_32( val, _values, result )
						result = CallFuncNode.new( nil, val[0], nil )
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 214
  def _reduce_33( val, _values, result )
						result = CallFuncNode.new( nil, val[0], val[2] )
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 218
  def _reduce_34( val, _values, result )
						result = CallFuncNode.new( val[0], val[2], val[4] )
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 222
  def _reduce_35( val, _values, result )
						result = CallFuncNode.new( val[0], val[2], nil )
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 232
  def _reduce_36( val, _values, result )
						result = val
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 236
  def _reduce_37( val, _values, result )
						result.push val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 245
  def _reduce_38( val, _values, result )
						result = IfNode.new(val[1],val[3],val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 257
  def _reduce_39( val, _values, result )
						result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 261
  def _reduce_40( val, _values, result )
						result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 265
  def _reduce_41( val, _values, result )
						result = [IfNode.new(val[1], val[3], val[4])]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 282
  def _reduce_42( val, _values, result )
            left = "_PUSH_WORK #{val[0].sub(/\A\$/,"")}"
            right = "_PUSH_VALUE #{val[2]}"
            result = CompareNode.new(val[1], left, right)
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 288
  def _reduce_43( val, _values, result )
            left = "_PUSH_WORK #{val[0].sub(/\A\$/,"")}"
            right = "_PUSH_WORK #{val[2].sub(/\A\$/,"")}"
            result = CompareNode.new(val[1], left, right)
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 294
  def _reduce_44( val, _values, result )
            left = "_PUSH_FLAG #{val[2]}"
            right = "_PUSH_VALUE TRUE"
            result = CompareNode.new('CMPID_EQ', left, right)
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 300
  def _reduce_45( val, _values, result )
            left = "_PUSH_FLAG #{val[2].sub(/\A\$/,"")}"
            right = "_PUSH_VALUE TRUE"
            result = CompareNode.new('CMPID_EQ', left, right)
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 306
  def _reduce_46( val, _values, result )
            left = "_PUSH_FLAG #{val[2]}"
            right = "_PUSH_VALUE FALSE"
            result = CompareNode.new('CMPID_EQ', left, right)
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 312
  def _reduce_47( val, _values, result )
            left = "_PUSH_FLAG #{val[2].sub(/\A\$/,"")}"
            right = "_PUSH_VALUE FALSE"
            result = CompareNode.new('CMPID_EQ', left, right)
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 316
  def _reduce_48( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 320
  def _reduce_49( val, _values, result )
            result = LogicalCompareNode.new(val[1], val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 329
  def _reduce_50( val, _values, result )
						result = 'CMPID_EQ'	#result = 'EQ'
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 333
  def _reduce_51( val, _values, result )
						result = 'CMPID_NE'	#result = 'NE'
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 337
  def _reduce_52( val, _values, result )
						result = 'CMPID_GT'	#result = 'GT'
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 341
  def _reduce_53( val, _values, result )
						result = 'CMPID_LT'	#result = 'LT'
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 345
  def _reduce_54( val, _values, result )
						result = 'CMPID_GT_EQ'	#result = 'GE'
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 349
  def _reduce_55( val, _values, result )
						result = 'CMPID_LT_EQ'	#result = 'LE'
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 353
  def _reduce_56( val, _values, result )
            result = 'CMPID_AND'
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 357
  def _reduce_57( val, _values, result )
            result = 'CMPID_OR'
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 367
  def _reduce_58( val, _values, result )
            result = WhileNode.new(val[1], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 376
  def _reduce_59( val, _values, result )
            result = SwitchNode.new(val[1].sub(/\A\$/,""), val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 387
  def _reduce_60( val, _values, result )
            result = []
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 391
  def _reduce_61( val, _values, result )
            result = [ val[0] ]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 395
  def _reduce_62( val, _values, result )
            result.push val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 404
  def _reduce_63( val, _values, result )
            result = CaseNode.new(val[1], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 416
  def _reduce_64( val, _values, result )
						result = AssignNode.new(val[0], val[2], :VARREF)
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 420
  def _reduce_65( val, _values, result )
						result = AssignNode.new(val[0], val[2], nil)
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 424
  def _reduce_66( val, _values, result )
						result = AssignNode.new(val[0], val[2], funcall)
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 433
  def _reduce_67( val, _values, result )
						result = [val[0],val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 437
  def _reduce_68( val, _values, result )
						result = [val[0], ['('] + val[2] + [')'] ]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 441
  def _reduce_69( val, _values, result )
            result = [ val[0], "()" ]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 445
  def _reduce_70( val, _values, result )
						result = [val[0],val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 449
  def _reduce_71( val, _values, result )
            result = [ val[0], nil ]
   result
  end
.,.,

 # reduce 72 omitted

module_eval <<'.,.,', 'sp4.y', 463
  def _reduce_73( val, _values, result )
						result = val
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 467
  def _reduce_74( val, _values, result )
						result = val
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 471
  def _reduce_75( val, _values, result )
						result = val
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 475
  def _reduce_76( val, _values, result )
						result = val
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 479
  def _reduce_77( val, _values, result )
						result = val
   result
  end
.,.,

 # reduce 78 omitted

 # reduce 79 omitted

 # reduce 80 omitted

 # reduce 81 omitted

 # reduce 82 omitted

module_eval <<'.,.,', 'sp4.y', 508
  def _reduce_83( val, _values, result )
						result = val
   result
  end
.,.,

module_eval <<'.,.,', 'sp4.y', 513
  def _reduce_84( val, _values, result )
						result.push val[1]
						result.push val[2]
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module PmScript
